/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_PERCENT = 2,
  anon_sym_COLON = 3,
  sym_identifier = 4,
  sym_program = 5,
  sym_statement = 6,
  sym_macro_statement = 7,
  sym_label_declaration = 8,
  aux_sym_program_repeat1 = 9,
  aux_sym_statement_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COLON] = ":",
  [sym_identifier] = "identifier",
  [sym_program] = "program",
  [sym_statement] = "statement",
  [sym_macro_statement] = "macro_statement",
  [sym_label_declaration] = "label_declaration",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_statement_repeat1] = "statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_identifier] = sym_identifier,
  [sym_program] = sym_program,
  [sym_statement] = sym_statement,
  [sym_macro_statement] = sym_macro_statement,
  [sym_label_declaration] = sym_label_declaration,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_statement_repeat1] = aux_sym_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_label_declaration] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 8,
  [17] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '%') ADVANCE(3);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == ';') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {(TSStateId)(-1),},
  [16] = {(TSStateId)(-1),},
  [17] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_macro_statement] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(14),
    [sym_statement] = STATE(9),
    [sym_macro_statement] = STATE(1),
    [sym_label_declaration] = STATE(11),
    [aux_sym_program_repeat1] = STATE(2),
    [aux_sym_statement_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_statement] = STATE(9),
    [sym_macro_statement] = STATE(2),
    [sym_label_declaration] = STATE(11),
    [aux_sym_program_repeat1] = STATE(3),
    [aux_sym_statement_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(9),
    [sym_macro_statement] = STATE(3),
    [sym_label_declaration] = STATE(11),
    [aux_sym_program_repeat1] = STATE(3),
    [aux_sym_statement_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(18),
  },
  [STATE(4)] = {
    [sym_statement] = STATE(15),
    [sym_macro_statement] = STATE(4),
    [sym_label_declaration] = STATE(11),
    [aux_sym_statement_repeat1] = STATE(7),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_macro_statement] = STATE(5),
    [sym_label_declaration] = STATE(11),
    [aux_sym_statement_repeat1] = STATE(6),
    [anon_sym_SEMI] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
  [STATE(6)] = {
    [sym_macro_statement] = STATE(6),
    [sym_label_declaration] = STATE(11),
    [aux_sym_statement_repeat1] = STATE(6),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(27),
  },
  [STATE(7)] = {
    [sym_macro_statement] = STATE(7),
    [sym_label_declaration] = STATE(11),
    [aux_sym_statement_repeat1] = STATE(6),
    [anon_sym_SEMI] = ACTIONS(30),
    [anon_sym_PERCENT] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(8), 1,
      sym_macro_statement,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [12] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(9), 1,
      sym_macro_statement,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [24] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(10), 1,
      sym_macro_statement,
    ACTIONS(36), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      sym_identifier,
  [36] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(11), 1,
      sym_macro_statement,
    ACTIONS(38), 2,
      anon_sym_SEMI,
      sym_identifier,
  [47] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    STATE(12), 1,
      sym_macro_statement,
    ACTIONS(40), 2,
      anon_sym_SEMI,
      sym_identifier,
  [58] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(42), 1,
      anon_sym_COLON,
    STATE(13), 1,
      sym_macro_statement,
  [68] = 3,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(14), 1,
      sym_macro_statement,
  [78] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [82] = 1,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
  [86] = 1,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 12,
  [SMALL_STATE(10)] = 24,
  [SMALL_STATE(11)] = 36,
  [SMALL_STATE(12)] = 47,
  [SMALL_STATE(13)] = 58,
  [SMALL_STATE(14)] = 68,
  [SMALL_STATE(15)] = 78,
  [SMALL_STATE(16)] = 82,
  [SMALL_STATE(17)] = 86,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statement_repeat1, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_declaration, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [44] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_statement, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_extra_non_terminals_with_shared_rules(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
