// Code generated by transit. DO NOT EDIT.

// Package usql is the grammar usql for the Go runtime of transit. Language
// returns its language, and the constants name its symbols and its fields.
package usql

import (
	"embed"
	"encoding/json"
	"sync"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/abi"
)

// Language returns the language of the grammar usql. Its external scanner is
// the scanner that newScanner returns.
func Language() *transit.Language {
	return language()
}

// language builds the language once. The tables are static data, so this
// copies no table.
var language = sync.OnceValue(func() *transit.Language {
	return transit.NewLanguage(&abi.Language{
		ABIVersion:             15,
		SymbolCount:            51,
		AliasCount:             0,
		TokenCount:             33,
		ExternalTokenCount:     32,
		StateCount:             87,
		LargeStateCount:        2,
		ProductionIDCount:      5,
		FieldCount:             3,
		MaxAliasSequenceLength: 4,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		SymbolNames:            symbolNames,
		FieldNames:             fieldNames,
		FieldMapSlices:         fieldMapSlices,
		FieldMapEntries:        fieldMapEntries,
		SymbolMetadata:         symbolMetadata,
		PublicSymbolMap:        publicSymbolMap,
		AliasMap:               aliasMap,
		AliasSequences:         aliasSequences,
		LexModes:               lexModes,
		LexFn:                  lex,
		KeywordCaptureToken:    0,
		ExternalScanner: abi.ExternalScanner{
			States:    externalScannerStates,
			SymbolMap: externalScannerSymbolMap,
			Create:    func() abi.Scanner { return newScanner() },
		},
		PrimaryStateIDs:        primaryStateIDs,
		Name:                   "usql",
		MaxReservedWordSetSize: 0,
		SupertypeCount:         0,
		Metadata:               abi.LanguageMetadata{MajorVersion: 0, MinorVersion: 1, PatchVersion: 0},
	})
})

// Queries holds queries/ of the grammar usql: its own queries, and in
// queries/<grammar>/ the queries of another grammar that its tree-sitter.json
// lists (D84).
//
//go:embed queries
var Queries embed.FS

// nodeTypes is node-types.json of the grammar.
//
//go:embed node-types.json
var nodeTypes []byte

// NodeTypes returns the node types of node-types.json of the grammar usql: the
// fields and the children of each node, and the subtypes of each supertype.
// Each call returns a new slice.
func NodeTypes() []transit.NodeType {
	var types []transit.NodeType
	if err := json.Unmarshal(nodeTypes, &types); err != nil {
		// the generator writes node-types.json, so it is valid
		panic("usql: reading node-types.json: " + err.Error())
	}
	return types
}

// Keywords returns the keywords of the grammar usql: the tokens that the word
// token captures, and the reserved words. Each call returns a new slice.
func Keywords() []string {
	return nil
}

// The symbols of the grammar usql, as Node.KindID and Node.GrammarID
// return them. The comment of each one is its name.
const (
	BuiltinSymEnd            transit.Symbol = 0  // "end"
	SymSqlText               transit.Symbol = 1  // "_sql_text"
	SymString                transit.Symbol = 2  // "string"
	SymQuotedIdentifier      transit.Symbol = 3  // "quoted_identifier"
	SymDollarString          transit.Symbol = 4  // "dollar_string"
	SymComment               transit.Symbol = 5  // "comment"
	SymSemicolon             transit.Symbol = 6  // ";"
	SymBackslash             transit.Symbol = 7  // "_backslash"
	SymBackslashOptions      transit.Symbol = 8  // "_backslash_options"
	SymCommandBase           transit.Symbol = 9  // "_command_base"
	SymShellCommandName      transit.Symbol = 10 // "command_name"
	SymSeparatorCommandName  transit.Symbol = 11 // "command_name"
	SymModifier              transit.Symbol = 12 // "modifier"
	SymCommandEnd            transit.Symbol = 13 // "_command_end"
	SymWord                  transit.Symbol = 14 // "word"
	SymPipe                  transit.Symbol = 15 // "|"
	SymShellCommand          transit.Symbol = 16 // "shell_command"
	SymBacktickOpen          transit.Symbol = 17 // "`"
	SymBacktickText          transit.Symbol = 18 // "shell_command"
	SymBacktickClose         transit.Symbol = 19 // "`"
	SymOptionOpen            transit.Symbol = 20 // "("
	SymOptionClose           transit.Symbol = 21 // ")"
	SymOptionEquals          transit.Symbol = 22 // "="
	SymOptionWord            transit.Symbol = 23 // "word"
	SymSigilPlain            transit.Symbol = 24 // ":"
	SymSigilSingleQuote      transit.Symbol = 25 // ":'"
	SymSigilDoubleQuote      transit.Symbol = 26 // ":\""
	SymSigilBrace            transit.Symbol = 27 // ":{?"
	SymVariableName          transit.Symbol = 28 // "variable_name"
	SymCloseSingleQuote      transit.Symbol = 29 // "'"
	SymCloseDoubleQuote      transit.Symbol = 30 // "\""
	SymCloseBrace            transit.Symbol = 31 // "}"
	SymErrorSentinel         transit.Symbol = 32 // "_error_sentinel"
	SymSourceFile            transit.Symbol = 33 // "source_file"
	SymStatement             transit.Symbol = 34 // "statement"
	SymPiece                 transit.Symbol = 35 // "_piece"
	SymMetaCommand           transit.Symbol = 36 // "meta_command"
	SymCommandName           transit.Symbol = 37 // "command_name"
	SymOptionsCommandName    transit.Symbol = 38 // "command_name"
	SymArgument              transit.Symbol = 39 // "_argument"
	SymPipe2                 transit.Symbol = 40 // "pipe"
	SymBacktickCommand       transit.Symbol = 41 // "backtick_command"
	SymOptionList            transit.Symbol = 42 // "option_list"
	SymOption                transit.Symbol = 43 // "option"
	SymVariable              transit.Symbol = 44 // "variable"
	AuxSymSourceFileRepeat1  transit.Symbol = 45 // "source_file_repeat1"
	AuxSymStatementRepeat1   transit.Symbol = 46 // "statement_repeat1"
	AuxSymMetaCommandRepeat1 transit.Symbol = 47 // "meta_command_repeat1"
	AuxSymMetaCommandRepeat2 transit.Symbol = 48 // "meta_command_repeat2"
	AuxSymMetaCommandRepeat3 transit.Symbol = 49 // "meta_command_repeat3"
	AuxSymOptionListRepeat1  transit.Symbol = 50 // "option_list_repeat1"
)

// The fields of the grammar usql, as Node.ChildByFieldID takes them. The
// comment of each one is its name.
const (
	FieldKey   transit.FieldID = 1 // "key"
	FieldName  transit.FieldID = 2 // "name"
	FieldValue transit.FieldID = 3 // "value"
)

// The short names of the types of the tables.
type (
	action = abi.ParseAction
	header = abi.EntryHeader
	shift  = abi.ShiftAction
	reduce = abi.ReduceAction
)

// The kinds of a parse action.
const (
	typeShift   = abi.ParseActionTypeShift
	typeReduce  = abi.ParseActionTypeReduce
	typeAccept  = abi.ParseActionTypeAccept
	typeRecover = abi.ParseActionTypeRecover
)

// symbolNames is ts_symbol_names.
var symbolNames = []string{
	BuiltinSymEnd:            "end",
	SymSqlText:               "_sql_text",
	SymString:                "string",
	SymQuotedIdentifier:      "quoted_identifier",
	SymDollarString:          "dollar_string",
	SymComment:               "comment",
	SymSemicolon:             ";",
	SymBackslash:             "_backslash",
	SymBackslashOptions:      "_backslash_options",
	SymCommandBase:           "_command_base",
	SymShellCommandName:      "command_name",
	SymSeparatorCommandName:  "command_name",
	SymModifier:              "modifier",
	SymCommandEnd:            "_command_end",
	SymWord:                  "word",
	SymPipe:                  "|",
	SymShellCommand:          "shell_command",
	SymBacktickOpen:          "`",
	SymBacktickText:          "shell_command",
	SymBacktickClose:         "`",
	SymOptionOpen:            "(",
	SymOptionClose:           ")",
	SymOptionEquals:          "=",
	SymOptionWord:            "word",
	SymSigilPlain:            ":",
	SymSigilSingleQuote:      ":'",
	SymSigilDoubleQuote:      ":\"",
	SymSigilBrace:            ":{?",
	SymVariableName:          "variable_name",
	SymCloseSingleQuote:      "'",
	SymCloseDoubleQuote:      "\"",
	SymCloseBrace:            "}",
	SymErrorSentinel:         "_error_sentinel",
	SymSourceFile:            "source_file",
	SymStatement:             "statement",
	SymPiece:                 "_piece",
	SymMetaCommand:           "meta_command",
	SymCommandName:           "command_name",
	SymOptionsCommandName:    "command_name",
	SymArgument:              "_argument",
	SymPipe2:                 "pipe",
	SymBacktickCommand:       "backtick_command",
	SymOptionList:            "option_list",
	SymOption:                "option",
	SymVariable:              "variable",
	AuxSymSourceFileRepeat1:  "source_file_repeat1",
	AuxSymStatementRepeat1:   "statement_repeat1",
	AuxSymMetaCommandRepeat1: "meta_command_repeat1",
	AuxSymMetaCommandRepeat2: "meta_command_repeat2",
	AuxSymMetaCommandRepeat3: "meta_command_repeat3",
	AuxSymOptionListRepeat1:  "option_list_repeat1",
}

// symbolMetadata is ts_symbol_metadata.
var symbolMetadata = []abi.SymbolMetadata{
	BuiltinSymEnd:            {Named: true},
	SymSqlText:               {Named: true},
	SymString:                {Visible: true, Named: true},
	SymQuotedIdentifier:      {Visible: true, Named: true},
	SymDollarString:          {Visible: true, Named: true},
	SymComment:               {Visible: true, Named: true},
	SymSemicolon:             {Visible: true},
	SymBackslash:             {Named: true},
	SymBackslashOptions:      {Named: true},
	SymCommandBase:           {Named: true},
	SymShellCommandName:      {Visible: true, Named: true},
	SymSeparatorCommandName:  {Visible: true, Named: true},
	SymModifier:              {Visible: true, Named: true},
	SymCommandEnd:            {Named: true},
	SymWord:                  {Visible: true, Named: true},
	SymPipe:                  {Visible: true},
	SymShellCommand:          {Visible: true, Named: true},
	SymBacktickOpen:          {Visible: true},
	SymBacktickText:          {Visible: true, Named: true},
	SymBacktickClose:         {Visible: true},
	SymOptionOpen:            {Visible: true},
	SymOptionClose:           {Visible: true},
	SymOptionEquals:          {Visible: true},
	SymOptionWord:            {Visible: true, Named: true},
	SymSigilPlain:            {Visible: true},
	SymSigilSingleQuote:      {Visible: true},
	SymSigilDoubleQuote:      {Visible: true},
	SymSigilBrace:            {Visible: true},
	SymVariableName:          {Visible: true, Named: true},
	SymCloseSingleQuote:      {Visible: true},
	SymCloseDoubleQuote:      {Visible: true},
	SymCloseBrace:            {Visible: true},
	SymErrorSentinel:         {Named: true},
	SymSourceFile:            {Visible: true, Named: true},
	SymStatement:             {Visible: true, Named: true},
	SymPiece:                 {Named: true},
	SymMetaCommand:           {Visible: true, Named: true},
	SymCommandName:           {Visible: true, Named: true},
	SymOptionsCommandName:    {Visible: true, Named: true},
	SymArgument:              {Named: true},
	SymPipe2:                 {Visible: true, Named: true},
	SymBacktickCommand:       {Visible: true, Named: true},
	SymOptionList:            {Visible: true, Named: true},
	SymOption:                {Visible: true, Named: true},
	SymVariable:              {Visible: true, Named: true},
	AuxSymSourceFileRepeat1:  {},
	AuxSymStatementRepeat1:   {},
	AuxSymMetaCommandRepeat1: {},
	AuxSymMetaCommandRepeat2: {},
	AuxSymMetaCommandRepeat3: {},
	AuxSymOptionListRepeat1:  {},
}

// fieldNames is ts_field_names. The name at index 0 is empty, as it is
// NULL in C.
var fieldNames = []string{
	FieldKey:   "key",
	FieldName:  "name",
	FieldValue: "value",
}

// parseTable is ts_parse_table, one row of SymbolCount entries for each large state.
var parseTable = []uint16{
	// state 0
	1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0,
	// state 1
	5, 7, 7, 7, 7, 3, 9, 11, 13, 0, 15, 17, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 19, 21, 23, 25, 0, 0, 0, 0,
	0, 60, 3, 7, 3, 6, 5, 0, 0, 0, 0, 0, 7, 3, 7, 0,
	0, 0, 0,
}

// smallParseTable is ts_small_parse_table. The entries of a small state
// are its number of groups, and for each group its value, its number of
// symbols and the symbols.
var smallParseTable = []uint16{
	// state 2
	16, 3, 1, 5, 27, 1, 0, 32, 1, 6, 35, 1, 7, 38, 1, 8,
	41, 1, 10, 44, 1, 11, 47, 1, 24, 50, 1, 25, 53, 1, 26, 56,
	1, 27, 5, 1, 38, 6, 1, 37, 2, 3, 34, 36, 45, 7, 3, 35,
	44, 46, 29, 4, 1, 2, 3, 4,
	// state 3
	16, 3, 1, 5, 9, 1, 6, 11, 1, 7, 13, 1, 8, 15, 1, 10,
	17, 1, 11, 19, 1, 24, 21, 1, 25, 23, 1, 26, 25, 1, 27, 59,
	1, 0, 5, 1, 38, 6, 1, 37, 2, 3, 34, 36, 45, 7, 3, 35,
	44, 46, 7, 4, 1, 2, 3, 4,
	// state 4
	13, 3, 1, 5, 63, 1, 12, 65, 1, 13, 67, 1, 15, 69, 1, 17,
	71, 1, 20, 73, 1, 24, 75, 1, 25, 77, 1, 26, 79, 1, 27, 24,
	1, 47, 61, 3, 2, 3, 14, 11, 6, 39, 40, 41, 42, 44, 49,
	// state 5
	13, 3, 1, 5, 67, 1, 15, 69, 1, 17, 71, 1, 20, 73, 1, 24,
	75, 1, 25, 77, 1, 26, 79, 1, 27, 83, 1, 12, 85, 1, 13, 4,
	1, 47, 81, 3, 2, 3, 14, 9, 6, 39, 40, 41, 42, 44, 49,
	// state 6
	12, 3, 1, 5, 85, 1, 13, 89, 1, 12, 91, 1, 15, 93, 1, 17,
	95, 1, 24, 97, 1, 25, 99, 1, 26, 101, 1, 27, 10, 1, 47, 87,
	3, 2, 3, 14, 13, 5, 39, 40, 41, 44, 48,
	// state 7
	9, 3, 1, 5, 19, 1, 24, 21, 1, 25, 23, 1, 26, 25, 1, 27,
	107, 1, 6, 8, 3, 35, 44, 46, 105, 4, 1, 2, 3, 4, 103, 5,
	7, 8, 10, 11, 0,
	// state 8
	8, 3, 1, 5, 114, 1, 24, 117, 1, 25, 120, 1, 26, 123, 1, 27,
	8, 3, 35, 44, 46, 111, 4, 1, 2, 3, 4, 109, 6, 6, 7, 8,
	10, 11, 0,
	// state 9
	11, 3, 1, 5, 65, 1, 13, 67, 1, 15, 69, 1, 17, 71, 1, 20,
	73, 1, 24, 75, 1, 25, 77, 1, 26, 79, 1, 27, 126, 3, 2, 3,
	14, 12, 6, 39, 40, 41, 42, 44, 49,
	// state 10
	12, 3, 1, 5, 65, 1, 13, 91, 1, 15, 93, 1, 17, 95, 1, 24,
	97, 1, 25, 99, 1, 26, 101, 1, 27, 130, 1, 12, 25, 1, 47, 128,
	3, 2, 3, 14, 14, 5, 39, 40, 41, 44, 48,
	// state 11
	11, 3, 1, 5, 67, 1, 15, 69, 1, 17, 71, 1, 20, 73, 1, 24,
	75, 1, 25, 77, 1, 26, 79, 1, 27, 132, 1, 13, 126, 3, 2, 3,
	14, 12, 6, 39, 40, 41, 42, 44, 49,
	// state 12
	11, 3, 1, 5, 137, 1, 13, 139, 1, 15, 142, 1, 17, 145, 1, 20,
	148, 1, 24, 151, 1, 25, 154, 1, 26, 157, 1, 27, 134, 3, 2, 3,
	14, 12, 6, 39, 40, 41, 42, 44, 49,
	// state 13
	10, 3, 1, 5, 65, 1, 13, 91, 1, 15, 93, 1, 17, 95, 1, 24,
	97, 1, 25, 99, 1, 26, 101, 1, 27, 160, 3, 2, 3, 14, 15, 5,
	39, 40, 41, 44, 48,
	// state 14
	10, 3, 1, 5, 91, 1, 15, 93, 1, 17, 95, 1, 24, 97, 1, 25,
	99, 1, 26, 101, 1, 27, 132, 1, 13, 160, 3, 2, 3, 14, 15, 5,
	39, 40, 41, 44, 48,
	// state 15
	10, 3, 1, 5, 165, 1, 13, 167, 1, 15, 170, 1, 17, 173, 1, 24,
	176, 1, 25, 179, 1, 26, 182, 1, 27, 162, 3, 2, 3, 14, 15, 5,
	39, 40, 41, 44, 48,
	// state 16
	2, 3, 1, 5, 185, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 17
	2, 3, 1, 5, 187, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 18
	2, 3, 1, 5, 189, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 19
	2, 3, 1, 5, 191, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 20
	2, 3, 1, 5, 193, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 21
	2, 3, 1, 5, 195, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 22
	2, 3, 1, 5, 197, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 23
	2, 3, 1, 5, 103, 14, 1, 2, 3, 4, 6, 7, 8, 10, 11, 24,
	25, 26, 27, 0,
	// state 24
	4, 3, 1, 5, 201, 1, 12, 24, 1, 47, 199, 11, 2, 3, 13, 14,
	15, 17, 20, 24, 25, 26, 27,
	// state 25
	4, 3, 1, 5, 204, 1, 12, 25, 1, 47, 199, 10, 2, 3, 13, 14,
	15, 17, 24, 25, 26, 27,
	// state 26
	2, 3, 1, 5, 207, 12, 2, 3, 12, 13, 14, 15, 17, 20, 24, 25,
	26, 27,
	// state 27
	3, 3, 1, 5, 211, 1, 9, 209, 11, 2, 3, 12, 13, 14, 15, 17,
	24, 25, 26, 27,
	// state 28
	3, 3, 1, 5, 215, 1, 16, 213, 11, 2, 3, 13, 14, 15, 17, 20,
	24, 25, 26, 27,
	// state 29
	2, 3, 1, 5, 217, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 30
	2, 3, 1, 5, 219, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 31
	2, 3, 1, 5, 221, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 32
	2, 3, 1, 5, 223, 11, 2, 3, 12, 13, 14, 15, 17, 24, 25, 26,
	27,
	// state 33
	2, 3, 1, 5, 185, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 34
	2, 3, 1, 5, 225, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 35
	3, 3, 1, 5, 227, 1, 16, 213, 10, 2, 3, 13, 14, 15, 17, 24,
	25, 26, 27,
	// state 36
	2, 3, 1, 5, 229, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 37
	2, 3, 1, 5, 197, 11, 2, 3, 13, 14, 15, 17, 20, 24, 25, 26,
	27,
	// state 38
	2, 3, 1, 5, 225, 10, 2, 3, 13, 14, 15, 17, 24, 25, 26, 27,
	// state 39
	2, 3, 1, 5, 217, 10, 2, 3, 13, 14, 15, 17, 24, 25, 26, 27,
	// state 40
	2, 3, 1, 5, 229, 10, 2, 3, 13, 14, 15, 17, 24, 25, 26, 27,
	// state 41
	2, 3, 1, 5, 197, 10, 2, 3, 13, 14, 15, 17, 24, 25, 26, 27,
	// state 42
	2, 3, 1, 5, 185, 10, 2, 3, 13, 14, 15, 17, 24, 25, 26, 27,
	// state 43
	7, 3, 1, 5, 233, 1, 24, 235, 1, 25, 237, 1, 26, 239, 1, 27,
	49, 1, 44, 231, 3, 2, 3, 23,
	// state 44
	4, 3, 1, 5, 241, 1, 21, 243, 1, 23, 45, 2, 43, 50,
	// state 45
	4, 3, 1, 5, 245, 1, 21, 247, 1, 23, 45, 2, 43, 50,
	// state 46
	4, 3, 1, 5, 243, 1, 23, 250, 1, 21, 44, 2, 43, 50,
	// state 47
	3, 3, 1, 5, 254, 1, 22, 252, 2, 21, 23,
	// state 48
	3, 3, 1, 5, 85, 1, 13, 256, 1, 16,
	// state 49
	2, 3, 1, 5, 258, 2, 21, 23,
	// state 50
	3, 3, 1, 5, 260, 1, 18, 262, 1, 19,
	// state 51
	2, 3, 1, 5, 197, 2, 21, 23,
	// state 52
	2, 3, 1, 5, 185, 2, 21, 23,
	// state 53
	3, 3, 1, 5, 264, 1, 18, 266, 1, 19,
	// state 54
	2, 3, 1, 5, 268, 1, 28,
	// state 55
	2, 3, 1, 5, 270, 1, 31,
	// state 56
	2, 3, 1, 5, 272, 1, 28,
	// state 57
	2, 3, 1, 5, 274, 1, 28,
	// state 58
	2, 3, 1, 5, 276, 1, 28,
	// state 59
	2, 3, 1, 5, 278, 1, 19,
	// state 60
	2, 3, 1, 5, 280, 1, 0,
	// state 61
	2, 3, 1, 5, 282, 1, 9,
	// state 62
	2, 3, 1, 5, 65, 1, 13,
	// state 63
	2, 3, 1, 5, 284, 1, 28,
	// state 64
	2, 3, 1, 5, 286, 1, 28,
	// state 65
	2, 3, 1, 5, 288, 1, 29,
	// state 66
	2, 3, 1, 5, 288, 1, 30,
	// state 67
	2, 3, 1, 5, 288, 1, 31,
	// state 68
	2, 3, 1, 5, 270, 1, 29,
	// state 69
	2, 3, 1, 5, 290, 1, 19,
	// state 70
	2, 3, 1, 5, 292, 1, 28,
	// state 71
	2, 3, 1, 5, 294, 1, 29,
	// state 72
	2, 3, 1, 5, 294, 1, 30,
	// state 73
	2, 3, 1, 5, 294, 1, 31,
	// state 74
	2, 3, 1, 5, 270, 1, 30,
	// state 75
	2, 3, 1, 5, 296, 1, 29,
	// state 76
	2, 3, 1, 5, 296, 1, 30,
	// state 77
	2, 3, 1, 5, 296, 1, 31,
	// state 78
	2, 3, 1, 5, 298, 1, 28,
	// state 79
	2, 3, 1, 5, 300, 1, 28,
	// state 80
	2, 3, 1, 5, 302, 1, 28,
	// state 81
	2, 3, 1, 5, 304, 1, 28,
	// state 82
	2, 3, 1, 5, 306, 1, 28,
	// state 83
	2, 3, 1, 5, 308, 1, 28,
	// state 84
	2, 3, 1, 5, 310, 1, 28,
	// state 85
	2, 3, 1, 5, 312, 1, 28,
	// state 86
	2, 3, 1, 5, 314, 1, 28,
}

// smallParseTableMap is ts_small_parse_table_map.
var smallParseTableMap = []uint32{
	0, 56, 112, 159, 206, 249, 286, 321, 362, 405, 446, 487, 524, 561, 598, 618,
	638, 658, 678, 698, 718, 738, 758, 781, 803, 821, 841, 861, 878, 895, 912, 929,
	946, 963, 982, 999, 1016, 1032, 1048, 1064, 1080, 1096, 1120, 1134, 1148, 1162, 1173, 1183,
	1191, 1201, 1209, 1217, 1227, 1234, 1241, 1248, 1255, 1262, 1269, 1276, 1283, 1290, 1297, 1304,
	1311, 1318, 1325, 1332, 1339, 1346, 1353, 1360, 1367, 1374, 1381, 1388, 1395, 1402, 1409, 1416,
	1423, 1430, 1437, 1444, 1451,
}

// parseActions is ts_parse_actions. Each group of actions is one entry
// with the header of the group, and then its actions.
var parseActions = []abi.ParseActionEntry{
	{Entry: header{Count: 0}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeRecover}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{Extra: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 0, Symbol: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 7}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 27}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 61}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 48}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 18}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 63}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 56}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 57}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 58}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 7, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 23, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 27, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 61, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 48, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 18, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 63, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 56, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 57, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 45}}}, {Action: action{Type: typeShift, Shift: shift{State: 58, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 11}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 28}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 53}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 46}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 70}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 81}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 82}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 83}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 13}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 10}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 35}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 50}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 64}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 78}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 79}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 80}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}}, {Action: action{Type: typeShift, Shift: shift{State: 8, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}}, {Action: action{Type: typeShift, Shift: shift{State: 63, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}}, {Action: action{Type: typeShift, Shift: shift{State: 56, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}}, {Action: action{Type: typeShift, Shift: shift{State: 57, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 46}}}, {Action: action{Type: typeShift, Shift: shift{State: 58, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 12}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 20}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 12, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 28, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 53, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 46, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 70, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 81, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 82, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 49}}}, {Action: action{Type: typeShift, Shift: shift{State: 83, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 15}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 15, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 35, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 50, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 64, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 78, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 79, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 48}}}, {Action: action{Type: typeShift, Shift: shift{State: 80, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 44, ProductionID: 2}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 36, ProductionID: 1}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 36, ProductionID: 1}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 36, ProductionID: 1}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 36, ProductionID: 1}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 44, ProductionID: 2}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 47}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 47}}}, {Action: action{Type: typeShift, Shift: shift{State: 24, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 47}}}, {Action: action{Type: typeShift, Shift: shift{State: 25, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 38}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 32}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 40}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 41}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 42}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 42}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 40}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 38}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 41}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 49}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 54}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 84}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 85}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 86}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 31}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 47}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 50}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 50}}}, {Action: action{Type: typeShift, Shift: shift{State: 47, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 30}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 43, ProductionID: 3}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 43}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 62}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 43, ProductionID: 4}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 59}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 39}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 69}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 29}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 51}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 68}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 74}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 55}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 40}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeAccept}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 41}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 42}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 36}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 52}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 65}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 66}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 67}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 71}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 72}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 73}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 75}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 76}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 77}}},
}

// fieldMapSlices is ts_field_map_slices.
var fieldMapSlices = []abi.MapSlice{
	{},
	{Index: 0, Length: 1},
	{Index: 1, Length: 1},
	{Index: 2, Length: 1},
	{Index: 3, Length: 2},
}

// fieldMapEntries is ts_field_map_entries.
var fieldMapEntries = []abi.FieldMapEntry{
	{FieldID: 2, ChildIndex: 0},
	{FieldID: 2, ChildIndex: 1},
	{FieldID: 1, ChildIndex: 0},
	{FieldID: 1, ChildIndex: 0},
	{FieldID: 3, ChildIndex: 2},
}

// publicSymbolMap is ts_symbol_map.
var publicSymbolMap = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 12, 13, 14, 15,
	16, 17, 16, 17, 20, 21, 22, 14, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 10, 10, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50,
}

// aliasMap is ts_non_terminal_alias_map.
var aliasMap = []uint16{
	0,
}

// aliasSequences is ts_alias_sequences, MaxAliasSequenceLength entries for each production.
var aliasSequences = []uint16{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0,
}

// lexModes is ts_lex_modes.
var lexModes = []abi.LexerMode{
	{ExternalLexState: 1},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 3},
	{ExternalLexState: 3},
	{ExternalLexState: 4},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 5},
	{ExternalLexState: 4},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 3},
	{ExternalLexState: 4},
	{ExternalLexState: 3},
	{ExternalLexState: 7},
	{ExternalLexState: 8},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 4},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 9},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 6},
	{ExternalLexState: 10},
	{ExternalLexState: 11},
	{ExternalLexState: 11},
	{ExternalLexState: 11},
	{ExternalLexState: 12},
	{ExternalLexState: 13},
	{ExternalLexState: 11},
	{ExternalLexState: 14},
	{ExternalLexState: 11},
	{ExternalLexState: 11},
	{ExternalLexState: 14},
	{ExternalLexState: 15},
	{ExternalLexState: 16},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 17},
	{ExternalLexState: 18},
	{ExternalLexState: 19},
	{ExternalLexState: 20},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 21},
	{ExternalLexState: 22},
	{ExternalLexState: 16},
	{ExternalLexState: 21},
	{ExternalLexState: 17},
	{ExternalLexState: 15},
	{ExternalLexState: 21},
	{ExternalLexState: 22},
	{ExternalLexState: 16},
	{ExternalLexState: 22},
	{ExternalLexState: 21},
	{ExternalLexState: 22},
	{ExternalLexState: 16},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
	{ExternalLexState: 15},
}

// primaryStateIDs is ts_primary_state_ids.
var primaryStateIDs = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 24, 26, 27, 28, 29, 30, 31,
	32, 16, 34, 28, 36, 22, 34, 29, 36, 22, 16, 43, 44, 45, 46, 47,
	48, 49, 50, 22, 16, 50, 54, 55, 56, 57, 58, 59, 60, 61, 62, 54,
	54, 65, 66, 55, 65, 59, 54, 65, 66, 55, 66, 65, 66, 55, 56, 57,
	58, 56, 57, 58, 56, 57, 58,
}

// externalScannerStates is ts_external_scanner_states, one row of
// ExternalTokenCount entries for each external lex state.
var externalScannerStates = []bool{
	false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
	true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
	true, true, true, true, true, true, true, true, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, true, true, true, true, false, true, false, false, true, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, true, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, false, true, true, true, false, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, true, false, false, true, true, true, true, false, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, false, true, true, true, true, true, false, false, true, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false,
	false, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false,
	false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false,
}

// externalScannerSymbolMap is ts_external_scanner_symbol_map.
var externalScannerSymbolMap = []uint16{
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
}

// lex is the main lex function, which mainLexTable runs.
func lex(lexer *abi.Lexer, state uint16) bool {
	return mainLexTable.Lex(lexer, state)
}

// mainLexTable is the lex table of lex. The ranges of each state are sorted.
var mainLexTable = abi.LexTable{
	States: []abi.LexState{
		{Accept: 0, HasAccept: true, EOFState: 1, HasEOF: true},
		{Accept: 0, HasAccept: true},
	},
}
