// Code generated by transit. DO NOT EDIT.

package json_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/json"
)

// This example parses a text of the grammar json, the input of the corpus case
// "main/String content", and prints its tree. Then it compiles each query of
// the package, and prints the number of its patterns.
func ExampleLanguage() {
	language := json.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`
[
  "",
  "abc",
  "def\n",
  "ghi\t",
  "jkl\f",
  "//",
  "/**/"
]
`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(json.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(json.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (document (array (string) (string (string_content)) (string (string_content) (escape_sequence)) (string (string_content) (escape_sequence)) (string (string_content) (escape_sequence)) (string (string_content)) (string (string_content))))
	// patterns in queries/highlights.scm: 6
}
