// Code generated by transit. DO NOT EDIT.

// Package json is the grammar json for the Go runtime of transit. Language
// returns its language, and the constants name its symbols and its fields.
package json

import (
	"embed"
	"encoding/json"
	"sync"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/abi"
)

// Language returns the language of the grammar json.
func Language() *transit.Language {
	return language()
}

// language builds the language once. The tables are static data, so this
// copies no table.
var language = sync.OnceValue(func() *transit.Language {
	return transit.NewLanguage(&abi.Language{
		ABIVersion:             15,
		SymbolCount:            25,
		AliasCount:             0,
		TokenCount:             15,
		ExternalTokenCount:     0,
		StateCount:             32,
		LargeStateCount:        7,
		ProductionIDCount:      2,
		FieldCount:             2,
		MaxAliasSequenceLength: 4,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		SymbolNames:            symbolNames,
		FieldNames:             fieldNames,
		FieldMapSlices:         fieldMapSlices,
		FieldMapEntries:        fieldMapEntries,
		SymbolMetadata:         symbolMetadata,
		PublicSymbolMap:        publicSymbolMap,
		AliasMap:               aliasMap,
		AliasSequences:         aliasSequences,
		LexModes:               lexModes,
		LexFn:                  lex,
		KeywordCaptureToken:    0,
		PrimaryStateIDs:        primaryStateIDs,
		Name:                   "json",
		MaxReservedWordSetSize: 0,
		SupertypeCount:         1,
		SupertypeSymbols:       supertypeSymbols,
		SupertypeMapSlices:     supertypeMapSlices,
		SupertypeMapEntries:    supertypeMapEntries,
		Metadata:               abi.LanguageMetadata{MajorVersion: 0, MinorVersion: 24, PatchVersion: 8},
	})
})

// Queries holds queries/*.scm of the grammar json.
//
//go:embed queries/*.scm
var Queries embed.FS

// nodeTypes is node-types.json of the grammar.
//
//go:embed node-types.json
var nodeTypes []byte

// NodeTypes returns the node types of node-types.json of the grammar json: the
// fields and the children of each node, and the subtypes of each supertype.
// Each call returns a new slice.
func NodeTypes() []transit.NodeType {
	var types []transit.NodeType
	if err := json.Unmarshal(nodeTypes, &types); err != nil {
		// the generator writes node-types.json, so it is valid
		panic("json: reading node-types.json: " + err.Error())
	}
	return types
}

// Keywords returns the keywords of the grammar json: the tokens that the word
// token captures, and the reserved words. Each call returns a new slice.
func Keywords() []string {
	return nil
}

// The symbols of the grammar json, as Node.KindID and Node.GrammarID
// return them. The comment of each one is its name.
const (
	BuiltinSymEnd         transit.Symbol = 0  // "end"
	AnonSymLBRACE         transit.Symbol = 1  // "{"
	AnonSymCOMMA          transit.Symbol = 2  // ","
	AnonSymRBRACE         transit.Symbol = 3  // "}"
	AnonSymCOLON          transit.Symbol = 4  // ":"
	AnonSymLBRACK         transit.Symbol = 5  // "["
	AnonSymRBRACK         transit.Symbol = 6  // "]"
	AnonSymDQUOTE         transit.Symbol = 7  // "\""
	SymStringContent      transit.Symbol = 8  // "string_content"
	SymEscapeSequence     transit.Symbol = 9  // "escape_sequence"
	SymNumber             transit.Symbol = 10 // "number"
	SymTrue               transit.Symbol = 11 // "true"
	SymFalse              transit.Symbol = 12 // "false"
	SymNull               transit.Symbol = 13 // "null"
	SymComment            transit.Symbol = 14 // "comment"
	SymDocument           transit.Symbol = 15 // "document"
	SymValue              transit.Symbol = 16 // "_value"
	SymObject             transit.Symbol = 17 // "object"
	SymPair               transit.Symbol = 18 // "pair"
	SymArray              transit.Symbol = 19 // "array"
	SymString             transit.Symbol = 20 // "string"
	AuxSymStringContent   transit.Symbol = 21 // "_string_content"
	AuxSymDocumentRepeat1 transit.Symbol = 22 // "document_repeat1"
	AuxSymObjectRepeat1   transit.Symbol = 23 // "object_repeat1"
	AuxSymArrayRepeat1    transit.Symbol = 24 // "array_repeat1"
)

// The fields of the grammar json, as Node.ChildByFieldID takes them. The
// comment of each one is its name.
const (
	FieldKey   transit.FieldID = 1 // "key"
	FieldValue transit.FieldID = 2 // "value"
)

// The short names of the types of the tables.
type (
	action = abi.ParseAction
	header = abi.EntryHeader
	shift  = abi.ShiftAction
	reduce = abi.ReduceAction
)

// The kinds of a parse action.
const (
	typeShift   = abi.ParseActionTypeShift
	typeReduce  = abi.ParseActionTypeReduce
	typeAccept  = abi.ParseActionTypeAccept
	typeRecover = abi.ParseActionTypeRecover
)

// symbolNames is ts_symbol_names.
var symbolNames = []string{
	BuiltinSymEnd:         "end",
	AnonSymLBRACE:         "{",
	AnonSymCOMMA:          ",",
	AnonSymRBRACE:         "}",
	AnonSymCOLON:          ":",
	AnonSymLBRACK:         "[",
	AnonSymRBRACK:         "]",
	AnonSymDQUOTE:         "\"",
	SymStringContent:      "string_content",
	SymEscapeSequence:     "escape_sequence",
	SymNumber:             "number",
	SymTrue:               "true",
	SymFalse:              "false",
	SymNull:               "null",
	SymComment:            "comment",
	SymDocument:           "document",
	SymValue:              "_value",
	SymObject:             "object",
	SymPair:               "pair",
	SymArray:              "array",
	SymString:             "string",
	AuxSymStringContent:   "_string_content",
	AuxSymDocumentRepeat1: "document_repeat1",
	AuxSymObjectRepeat1:   "object_repeat1",
	AuxSymArrayRepeat1:    "array_repeat1",
}

// symbolMetadata is ts_symbol_metadata.
var symbolMetadata = []abi.SymbolMetadata{
	BuiltinSymEnd:         {Named: true},
	AnonSymLBRACE:         {Visible: true},
	AnonSymCOMMA:          {Visible: true},
	AnonSymRBRACE:         {Visible: true},
	AnonSymCOLON:          {Visible: true},
	AnonSymLBRACK:         {Visible: true},
	AnonSymRBRACK:         {Visible: true},
	AnonSymDQUOTE:         {Visible: true},
	SymStringContent:      {Visible: true, Named: true},
	SymEscapeSequence:     {Visible: true, Named: true},
	SymNumber:             {Visible: true, Named: true},
	SymTrue:               {Visible: true, Named: true},
	SymFalse:              {Visible: true, Named: true},
	SymNull:               {Visible: true, Named: true},
	SymComment:            {Visible: true, Named: true},
	SymDocument:           {Visible: true, Named: true},
	SymValue:              {Named: true, Supertype: true},
	SymObject:             {Visible: true, Named: true},
	SymPair:               {Visible: true, Named: true},
	SymArray:              {Visible: true, Named: true},
	SymString:             {Visible: true, Named: true},
	AuxSymStringContent:   {},
	AuxSymDocumentRepeat1: {},
	AuxSymObjectRepeat1:   {},
	AuxSymArrayRepeat1:    {},
}

// fieldNames is ts_field_names. The name at index 0 is empty, as it is
// NULL in C.
var fieldNames = []string{
	FieldKey:   "key",
	FieldValue: "value",
}

// parseTable is ts_parse_table, one row of SymbolCount entries for each large state.
var parseTable = []uint16{
	// state 0
	1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0,
	// state 1
	5, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 30,
	2, 8, 0, 8, 8, 0, 2, 0, 0,
	// state 2
	15, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 0,
	3, 8, 0, 8, 8, 0, 3, 0, 0,
	// state 3
	17, 19, 0, 0, 0, 22, 0, 25, 0, 0, 28, 28, 28, 28, 3, 0,
	3, 8, 0, 8, 8, 0, 3, 0, 0,
	// state 4
	0, 7, 0, 0, 0, 9, 31, 11, 0, 0, 13, 13, 13, 13, 3, 0,
	21, 8, 0, 8, 8, 0, 0, 0, 0,
	// state 5
	33, 33, 33, 33, 33, 33, 33, 33, 0, 0, 33, 33, 33, 33, 3, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0,
	// state 6
	35, 35, 35, 35, 35, 35, 35, 35, 0, 0, 35, 35, 35, 35, 3, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0,
}

// smallParseTable is ts_small_parse_table. The entries of a small state
// are its number of groups, and for each group its value, its number of
// symbols and the symbols.
var smallParseTable = []uint16{
	// state 7
	2, 3, 1, 14, 37, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 8
	2, 3, 1, 14, 39, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 9
	2, 3, 1, 14, 41, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 10
	7, 3, 1, 14, 7, 1, 1, 9, 1, 5, 11, 1, 7, 29, 1, 16,
	8, 3, 17, 19, 20, 13, 4, 10, 11, 12, 13,
	// state 11
	2, 3, 1, 14, 43, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 12
	2, 3, 1, 14, 45, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 13
	7, 3, 1, 14, 7, 1, 1, 9, 1, 5, 11, 1, 7, 28, 1, 16,
	8, 3, 17, 19, 20, 13, 4, 10, 11, 12, 13,
	// state 14
	2, 3, 1, 14, 47, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 15
	2, 3, 1, 14, 49, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12,
	13,
	// state 16
	5, 3, 1, 14, 11, 1, 7, 51, 1, 3, 20, 1, 18, 31, 1, 20,
	// state 17
	4, 53, 1, 7, 57, 1, 14, 18, 1, 21, 55, 2, 8, 9,
	// state 18
	4, 57, 1, 14, 59, 1, 7, 19, 1, 21, 61, 2, 8, 9,
	// state 19
	4, 57, 1, 14, 63, 1, 7, 19, 1, 21, 65, 2, 8, 9,
	// state 20
	4, 3, 1, 14, 68, 1, 2, 70, 1, 3, 22, 1, 23,
	// state 21
	4, 3, 1, 14, 72, 1, 2, 74, 1, 6, 24, 1, 24,
	// state 22
	4, 3, 1, 14, 68, 1, 2, 76, 1, 3, 25, 1, 23,
	// state 23
	4, 3, 1, 14, 11, 1, 7, 27, 1, 18, 31, 1, 20,
	// state 24
	4, 3, 1, 14, 72, 1, 2, 78, 1, 6, 26, 1, 24,
	// state 25
	4, 3, 1, 14, 80, 1, 2, 83, 1, 3, 25, 1, 23,
	// state 26
	4, 3, 1, 14, 85, 1, 2, 88, 1, 6, 26, 1, 24,
	// state 27
	2, 3, 1, 14, 83, 2, 2, 3,
	// state 28
	2, 3, 1, 14, 90, 2, 2, 3,
	// state 29
	2, 3, 1, 14, 88, 2, 2, 6,
	// state 30
	2, 3, 1, 14, 92, 1, 0,
	// state 31
	2, 3, 1, 14, 94, 1, 4,
}

// smallParseTableMap is ts_small_parse_table_map.
var smallParseTableMap = []uint32{
	0, 17, 34, 51, 78, 95, 112, 139, 156, 173, 189, 203, 217, 231, 244, 257,
	270, 283, 296, 309, 322, 330, 338, 346, 353,
}

// parseActions is ts_parse_actions. Each group of actions is one entry
// with the header of the group, and then its actions.
var parseActions = []abi.ParseActionEntry{
	{Entry: header{Count: 0}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeRecover}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{Extra: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 0, Symbol: 15}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 15}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 22}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 22}}}, {Action: action{Type: typeShift, Shift: shift{State: 16, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 22}}}, {Action: action{Type: typeShift, Shift: shift{State: 4, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 22}}}, {Action: action{Type: typeShift, Shift: shift{State: 17, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 22}}}, {Action: action{Type: typeShift, Shift: shift{State: 8, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 20}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 20}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 7}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 5}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 18}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{Extra: true}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 6}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 19}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 21}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 21}}}, {Action: action{Type: typeShift, Shift: shift{State: 19, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 11}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 10}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 12}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 15}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 23}}}, {Action: action{Type: typeShift, Shift: shift{State: 23, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 23}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 24}}}, {Action: action{Type: typeShift, Shift: shift{State: 10, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 18, ProductionID: 1}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeAccept}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 13}}},
}

// fieldMapSlices is ts_field_map_slices.
var fieldMapSlices = []abi.MapSlice{
	{},
	{Index: 0, Length: 2},
}

// fieldMapEntries is ts_field_map_entries.
var fieldMapEntries = []abi.FieldMapEntry{
	{FieldID: 1, ChildIndex: 0},
	{FieldID: 2, ChildIndex: 2},
}

// publicSymbolMap is ts_symbol_map.
var publicSymbolMap = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24,
}

// aliasMap is ts_non_terminal_alias_map.
var aliasMap = []uint16{
	0,
}

// aliasSequences is ts_alias_sequences, MaxAliasSequenceLength entries for each production.
var aliasSequences = []uint16{
	0, 0, 0, 0, 0, 0, 0, 0,
}

// lexModes is ts_lex_modes.
var lexModes = []abi.LexerMode{
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{LexState: 1},
	{LexState: 1},
	{LexState: 1},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
}

// primaryStateIDs is ts_primary_state_ids.
var primaryStateIDs = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
}

// supertypeSymbols is ts_supertype_symbols.
var supertypeSymbols = []uint16{
	16,
}

// supertypeMapSlices is ts_supertype_map_slices.
var supertypeMapSlices = []abi.MapSlice{
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{Index: 0, Length: 7},
}

// supertypeMapEntries is ts_supertype_map_entries.
var supertypeMapEntries = []uint16{
	19, 12, 13, 10, 17, 20, 11,
}

// lex is the main lex function, which mainLexTable runs.
func lex(lexer *abi.Lexer, state uint16) bool {
	return mainLexTable.Lex(lexer, state)
}

// mainLexTable is the lex table of lex. The ranges of each state are sorted.
var mainLexTable = abi.LexTable{
	States: []abi.LexState{
		{Count: 17, EOFState: 21, HasEOF: true},
		{Start: 17, Count: 14},
		{Start: 31, Count: 4},
		{Start: 35, Count: 2},
		{Start: 37, Count: 6},
		{Start: 43, Count: 4},
		{Start: 47, Count: 2},
		{Start: 49, Count: 2},
		{Start: 51, Count: 1},
		{Start: 52, Count: 1},
		{Start: 53, Count: 1},
		{Start: 54, Count: 1},
		{Start: 55, Count: 1},
		{Start: 56, Count: 1},
		{Start: 57, Count: 1},
		{Start: 58, Count: 1},
		{Start: 59, Count: 1},
		{Start: 60, Count: 1},
		{Start: 61, Count: 8},
		{Start: 69, Count: 1},
		{Start: 70, Count: 16, EOFState: 21, HasEOF: true},
		{Start: 86, Accept: 0, HasAccept: true},
		{Start: 86, Accept: 1, HasAccept: true},
		{Start: 86, Accept: 2, HasAccept: true},
		{Start: 86, Accept: 3, HasAccept: true},
		{Start: 86, Accept: 4, HasAccept: true},
		{Start: 86, Accept: 5, HasAccept: true},
		{Start: 86, Accept: 6, HasAccept: true},
		{Start: 86, Accept: 7, HasAccept: true},
		{Start: 86, Count: 7, Accept: 8, HasAccept: true},
		{Start: 93, Count: 9, Accept: 8, HasAccept: true},
		{Start: 102, Count: 7, Accept: 8, HasAccept: true},
		{Start: 109, Count: 11, Accept: 8, HasAccept: true},
		{Start: 120, Count: 5, Accept: 8, HasAccept: true},
		{Start: 125, Accept: 9, HasAccept: true},
		{Start: 125, Count: 3, Accept: 10, HasAccept: true},
		{Start: 128, Count: 4, Accept: 10, HasAccept: true},
		{Start: 132, Count: 3, Accept: 10, HasAccept: true},
		{Start: 135, Count: 1, Accept: 10, HasAccept: true},
		{Start: 136, Accept: 11, HasAccept: true},
		{Start: 136, Accept: 12, HasAccept: true},
		{Start: 136, Accept: 13, HasAccept: true},
		{Start: 136, Accept: 14, HasAccept: true},
		{Start: 136, Count: 3, Accept: 14, HasAccept: true},
	},
	Ranges: []abi.LexRange{
		{Lo: '\t', Hi: '\r', State: 20, Skip: true}, {Lo: ' ', Hi: ' ', State: 20, Skip: true}, {Lo: '"', Hi: '"', State: 28}, {Lo: ',', Hi: ',', State: 23},
		{Lo: '-', Hi: '-', State: 7}, {Lo: '/', Hi: '/', State: 3}, {Lo: '0', Hi: '0', State: 35}, {Lo: '1', Hi: '9', State: 36},
		{Lo: ':', Hi: ':', State: 25}, {Lo: '[', Hi: '[', State: 26}, {Lo: '\\', Hi: '\\', State: 18}, {Lo: ']', Hi: ']', State: 27},
		{Lo: 'f', Hi: 'f', State: 8}, {Lo: 'n', Hi: 'n', State: 17}, {Lo: 't', Hi: 't', State: 14}, {Lo: '{', Hi: '{', State: 22},
		{Lo: '}', Hi: '}', State: 24}, {Lo: -2147483648, Hi: -1, State: 33}, {Lo: 0x01, Hi: 0x08, State: 33}, {Lo: '\t', Hi: '\t', State: 32},
		{Lo: '\n', Hi: '\n', State: 2, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 32}, {Lo: 0x0e, Hi: 0x1f, State: 33}, {Lo: ' ', Hi: ' ', State: 32},
		{Lo: '!', Hi: '!', State: 33}, {Lo: '"', Hi: '"', State: 28}, {Lo: '#', Hi: '.', State: 33}, {Lo: '/', Hi: '/', State: 29},
		{Lo: '0', Hi: '[', State: 33}, {Lo: '\\', Hi: '\\', State: 18}, {Lo: ']', Hi: 0x7fffffff, State: 33}, {Lo: '\t', Hi: '\r', State: 2, Skip: true},
		{Lo: ' ', Hi: ' ', State: 2, Skip: true}, {Lo: '"', Hi: '"', State: 28}, {Lo: '/', Hi: '/', State: 3}, {Lo: '*', Hi: '*', State: 5},
		{Lo: '/', Hi: '/', State: 43}, {Lo: -2147483648, Hi: -1, State: 5}, {Lo: 0x01, Hi: ')', State: 5}, {Lo: '*', Hi: '*', State: 4},
		{Lo: '+', Hi: '.', State: 5}, {Lo: '/', Hi: '/', State: 42}, {Lo: '0', Hi: 0x7fffffff, State: 5}, {Lo: -2147483648, Hi: -1, State: 5},
		{Lo: 0x01, Hi: ')', State: 5}, {Lo: '*', Hi: '*', State: 4}, {Lo: '+', Hi: 0x7fffffff, State: 5}, {Lo: '-', Hi: '-', State: 19},
		{Lo: '0', Hi: '9', State: 38}, {Lo: '0', Hi: '0', State: 35}, {Lo: '1', Hi: '9', State: 36}, {Lo: 'a', Hi: 'a', State: 11},
		{Lo: 'e', Hi: 'e', State: 39}, {Lo: 'e', Hi: 'e', State: 40}, {Lo: 'l', Hi: 'l', State: 15}, {Lo: 'l', Hi: 'l', State: 41},
		{Lo: 'l', Hi: 'l', State: 12}, {Lo: 'r', Hi: 'r', State: 16}, {Lo: 's', Hi: 's', State: 10}, {Lo: 'u', Hi: 'u', State: 9},
		{Lo: 'u', Hi: 'u', State: 13}, {Lo: '"', Hi: '"', State: 34}, {Lo: '/', Hi: '/', State: 34}, {Lo: '\\', Hi: '\\', State: 34},
		{Lo: 'b', Hi: 'b', State: 34}, {Lo: 'f', Hi: 'f', State: 34}, {Lo: 'n', Hi: 'n', State: 34}, {Lo: 'r', Hi: 'r', State: 34},
		{Lo: 't', Hi: 'u', State: 34}, {Lo: '0', Hi: '9', State: 38}, {Lo: '\t', Hi: '\r', State: 20, Skip: true}, {Lo: ' ', Hi: ' ', State: 20, Skip: true},
		{Lo: '"', Hi: '"', State: 28}, {Lo: ',', Hi: ',', State: 23}, {Lo: '-', Hi: '-', State: 7}, {Lo: '/', Hi: '/', State: 3},
		{Lo: '0', Hi: '0', State: 35}, {Lo: '1', Hi: '9', State: 36}, {Lo: ':', Hi: ':', State: 25}, {Lo: '[', Hi: '[', State: 26},
		{Lo: ']', Hi: ']', State: 27}, {Lo: 'f', Hi: 'f', State: 8}, {Lo: 'n', Hi: 'n', State: 17}, {Lo: 't', Hi: 't', State: 14},
		{Lo: '{', Hi: '{', State: 22}, {Lo: '}', Hi: '}', State: 24}, {Lo: -2147483648, Hi: -1, State: 33}, {Lo: 0x01, Hi: '\t', State: 33},
		{Lo: 0x0b, Hi: '!', State: 33}, {Lo: '#', Hi: ')', State: 33}, {Lo: '*', Hi: '*', State: 31}, {Lo: '+', Hi: '[', State: 33},
		{Lo: ']', Hi: 0x7fffffff, State: 33}, {Lo: -2147483648, Hi: -1, State: 31}, {Lo: 0x01, Hi: '\t', State: 31}, {Lo: 0x0b, Hi: '!', State: 31},
		{Lo: '#', Hi: ')', State: 31}, {Lo: '*', Hi: '*', State: 30}, {Lo: '+', Hi: '.', State: 31}, {Lo: '/', Hi: '/', State: 33},
		{Lo: '0', Hi: '[', State: 31}, {Lo: ']', Hi: 0x7fffffff, State: 31}, {Lo: -2147483648, Hi: -1, State: 31}, {Lo: 0x01, Hi: '\t', State: 31},
		{Lo: 0x0b, Hi: '!', State: 31}, {Lo: '#', Hi: ')', State: 31}, {Lo: '*', Hi: '*', State: 30}, {Lo: '+', Hi: '[', State: 31},
		{Lo: ']', Hi: 0x7fffffff, State: 31}, {Lo: -2147483648, Hi: -1, State: 33}, {Lo: 0x01, Hi: 0x08, State: 33}, {Lo: '\t', Hi: '\t', State: 32},
		{Lo: 0x0b, Hi: '\r', State: 32}, {Lo: 0x0e, Hi: 0x1f, State: 33}, {Lo: ' ', Hi: ' ', State: 32}, {Lo: '!', Hi: '!', State: 33},
		{Lo: '#', Hi: '.', State: 33}, {Lo: '/', Hi: '/', State: 29}, {Lo: '0', Hi: '[', State: 33}, {Lo: ']', Hi: 0x7fffffff, State: 33},
		{Lo: -2147483648, Hi: -1, State: 33}, {Lo: 0x01, Hi: '\t', State: 33}, {Lo: 0x0b, Hi: '!', State: 33}, {Lo: '#', Hi: '[', State: 33},
		{Lo: ']', Hi: 0x7fffffff, State: 33}, {Lo: '.', Hi: '.', State: 37}, {Lo: 'E', Hi: 'E', State: 6}, {Lo: 'e', Hi: 'e', State: 6},
		{Lo: '.', Hi: '.', State: 37}, {Lo: '0', Hi: '9', State: 36}, {Lo: 'E', Hi: 'E', State: 6}, {Lo: 'e', Hi: 'e', State: 6},
		{Lo: '0', Hi: '9', State: 37}, {Lo: 'E', Hi: 'E', State: 6}, {Lo: 'e', Hi: 'e', State: 6}, {Lo: '0', Hi: '9', State: 38},
		{Lo: -2147483648, Hi: -1, State: 43}, {Lo: 0x01, Hi: '\t', State: 43}, {Lo: 0x0b, Hi: 0x7fffffff, State: 43},
	},
}
