// Code generated by transit. DO NOT EDIT.

// Package embeddedtemplate is the grammar embedded_template for the Go runtime
// of transit. Language returns its language, and the constants name its symbols
// and its fields.
package embeddedtemplate

import (
	"embed"
	"encoding/json"
	"sync"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/abi"
)

// Language returns the language of the grammar embedded_template.
func Language() *transit.Language {
	return language()
}

// language builds the language once. The tables are static data, so this
// copies no table.
var language = sync.OnceValue(func() *transit.Language {
	return transit.NewLanguage(&abi.Language{
		ABIVersion:             15,
		SymbolCount:            30,
		AliasCount:             1,
		TokenCount:             20,
		ExternalTokenCount:     0,
		StateCount:             29,
		LargeStateCount:        4,
		ProductionIDCount:      2,
		FieldCount:             0,
		MaxAliasSequenceLength: 3,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		SymbolNames:            symbolNames,
		SymbolMetadata:         symbolMetadata,
		PublicSymbolMap:        publicSymbolMap,
		AliasMap:               aliasMap,
		AliasSequences:         aliasSequences,
		LexModes:               lexModes,
		LexFn:                  lex,
		KeywordCaptureToken:    0,
		PrimaryStateIDs:        primaryStateIDs,
		Name:                   "embedded_template",
		MaxReservedWordSetSize: 0,
		SupertypeCount:         0,
		Metadata:               abi.LanguageMetadata{MajorVersion: 0, MinorVersion: 25, PatchVersion: 0},
	})
})

// Queries holds queries/ of the grammar embedded_template: its own queries, and
// in queries/<grammar>/ the queries of another grammar that its
// tree-sitter.json lists (D84).
//
//go:embed queries
var Queries embed.FS

// nodeTypes is node-types.json of the grammar.
//
//go:embed node-types.json
var nodeTypes []byte

// NodeTypes returns the node types of node-types.json of the grammar embedded_template: the
// fields and the children of each node, and the subtypes of each supertype.
// Each call returns a new slice.
func NodeTypes() []transit.NodeType {
	var types []transit.NodeType
	if err := json.Unmarshal(nodeTypes, &types); err != nil {
		// the generator writes node-types.json, so it is valid
		panic("embeddedtemplate: reading node-types.json: " + err.Error())
	}
	return types
}

// Keywords returns the keywords of the grammar embedded_template: the tokens that the word
// token captures, and the reserved words. Each call returns a new slice.
func Keywords() []string {
	return nil
}

// The symbols of the grammar embedded_template, as Node.KindID and Node.GrammarID
// return them. The comment of each one is its name.
const (
	BuiltinSymEnd            transit.Symbol = 0  // "end"
	AuxSymCodeToken1         transit.Symbol = 1  // "code_token1"
	AnonSymPERCENTPERCENTGT  transit.Symbol = 2  // "%%>"
	AuxSymContentToken1      transit.Symbol = 3  // "content_token1"
	AnonSymLTPERCENTPERCENT  transit.Symbol = 4  // "<%%"
	AnonSymLTPERCENT         transit.Symbol = 5  // "<%"
	AnonSymLTPERCENT2        transit.Symbol = 6  // "<%_"
	AnonSymLTPERCENTPIPE     transit.Symbol = 7  // "<%|"
	AnonSymLTPERCENTTILDE    transit.Symbol = 8  // "<%~"
	AnonSymPERCENTGT         transit.Symbol = 9  // "%>"
	AnonSymDASHPERCENTGT     transit.Symbol = 10 // "-%>"
	AnonSymPERCENTGT2        transit.Symbol = 11 // "_%>"
	AnonSymLTPERCENTEQ       transit.Symbol = 12 // "<%="
	AnonSymLTPERCENTEQEQ     transit.Symbol = 13 // "<%=="
	AnonSymLTPERCENTPIPEEQ   transit.Symbol = 14 // "<%|="
	AnonSymLTPERCENTPIPEEQEQ transit.Symbol = 15 // "<%|=="
	AnonSymLTPERCENTDASH     transit.Symbol = 16 // "<%-"
	AnonSymEQPERCENTGT       transit.Symbol = 17 // "=%>"
	AnonSymLTPERCENTPOUND    transit.Symbol = 18 // "<%#"
	AnonSymLTPERCENTgraphql  transit.Symbol = 19 // "<%graphql"
	SymTemplate              transit.Symbol = 20 // "template"
	SymCode                  transit.Symbol = 21 // "code"
	SymContent               transit.Symbol = 22 // "content"
	SymDirective             transit.Symbol = 23 // "directive"
	SymOutputDirective       transit.Symbol = 24 // "output_directive"
	SymCommentDirective      transit.Symbol = 25 // "comment_directive"
	SymGraphqlDirective      transit.Symbol = 26 // "graphql_directive"
	AuxSymTemplateRepeat1    transit.Symbol = 27 // "template_repeat1"
	AuxSymCodeRepeat1        transit.Symbol = 28 // "code_repeat1"
	AuxSymContentRepeat1     transit.Symbol = 29 // "content_repeat1"
	AliasSymComment          transit.Symbol = 30 // "comment"
)

// The short names of the types of the tables.
type (
	action = abi.ParseAction
	header = abi.EntryHeader
	shift  = abi.ShiftAction
	reduce = abi.ReduceAction
)

// The kinds of a parse action.
const (
	typeShift   = abi.ParseActionTypeShift
	typeReduce  = abi.ParseActionTypeReduce
	typeAccept  = abi.ParseActionTypeAccept
	typeRecover = abi.ParseActionTypeRecover
)

// symbolNames is ts_symbol_names.
var symbolNames = []string{
	BuiltinSymEnd:            "end",
	AuxSymCodeToken1:         "code_token1",
	AnonSymPERCENTPERCENTGT:  "%%>",
	AuxSymContentToken1:      "content_token1",
	AnonSymLTPERCENTPERCENT:  "<%%",
	AnonSymLTPERCENT:         "<%",
	AnonSymLTPERCENT2:        "<%_",
	AnonSymLTPERCENTPIPE:     "<%|",
	AnonSymLTPERCENTTILDE:    "<%~",
	AnonSymPERCENTGT:         "%>",
	AnonSymDASHPERCENTGT:     "-%>",
	AnonSymPERCENTGT2:        "_%>",
	AnonSymLTPERCENTEQ:       "<%=",
	AnonSymLTPERCENTEQEQ:     "<%==",
	AnonSymLTPERCENTPIPEEQ:   "<%|=",
	AnonSymLTPERCENTPIPEEQEQ: "<%|==",
	AnonSymLTPERCENTDASH:     "<%-",
	AnonSymEQPERCENTGT:       "=%>",
	AnonSymLTPERCENTPOUND:    "<%#",
	AnonSymLTPERCENTgraphql:  "<%graphql",
	SymTemplate:              "template",
	SymCode:                  "code",
	SymContent:               "content",
	SymDirective:             "directive",
	SymOutputDirective:       "output_directive",
	SymCommentDirective:      "comment_directive",
	SymGraphqlDirective:      "graphql_directive",
	AuxSymTemplateRepeat1:    "template_repeat1",
	AuxSymCodeRepeat1:        "code_repeat1",
	AuxSymContentRepeat1:     "content_repeat1",
	AliasSymComment:          "comment",
}

// symbolMetadata is ts_symbol_metadata.
var symbolMetadata = []abi.SymbolMetadata{
	BuiltinSymEnd:            {Named: true},
	AuxSymCodeToken1:         {},
	AnonSymPERCENTPERCENTGT:  {Visible: true},
	AuxSymContentToken1:      {},
	AnonSymLTPERCENTPERCENT:  {Visible: true},
	AnonSymLTPERCENT:         {Visible: true},
	AnonSymLTPERCENT2:        {Visible: true},
	AnonSymLTPERCENTPIPE:     {Visible: true},
	AnonSymLTPERCENTTILDE:    {Visible: true},
	AnonSymPERCENTGT:         {Visible: true},
	AnonSymDASHPERCENTGT:     {Visible: true},
	AnonSymPERCENTGT2:        {Visible: true},
	AnonSymLTPERCENTEQ:       {Visible: true},
	AnonSymLTPERCENTEQEQ:     {Visible: true},
	AnonSymLTPERCENTPIPEEQ:   {Visible: true},
	AnonSymLTPERCENTPIPEEQEQ: {Visible: true},
	AnonSymLTPERCENTDASH:     {Visible: true},
	AnonSymEQPERCENTGT:       {Visible: true},
	AnonSymLTPERCENTPOUND:    {Visible: true},
	AnonSymLTPERCENTgraphql:  {Visible: true},
	SymTemplate:              {Visible: true, Named: true},
	SymCode:                  {Visible: true, Named: true},
	SymContent:               {Visible: true, Named: true},
	SymDirective:             {Visible: true, Named: true},
	SymOutputDirective:       {Visible: true, Named: true},
	SymCommentDirective:      {Visible: true, Named: true},
	SymGraphqlDirective:      {Visible: true, Named: true},
	AuxSymTemplateRepeat1:    {},
	AuxSymCodeRepeat1:        {},
	AuxSymContentRepeat1:     {},
	AliasSymComment:          {Visible: true, Named: true},
}

// parseTable is ts_parse_table, one row of SymbolCount entries for each large state.
var parseTable = []uint16{
	// state 0
	1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	// state 1
	3, 0, 0, 5, 7, 9, 11, 9, 11, 0, 0, 0, 13, 15, 13, 15,
	15, 0, 17, 19, 26, 0, 2, 2, 2, 2, 2, 2, 0, 4,
	// state 2
	21, 0, 0, 5, 7, 9, 11, 9, 11, 0, 0, 0, 13, 15, 13, 15,
	15, 0, 17, 19, 0, 0, 3, 3, 3, 3, 3, 3, 0, 4,
	// state 3
	23, 0, 0, 25, 28, 31, 34, 31, 34, 0, 0, 0, 37, 40, 37, 40,
	40, 0, 43, 46, 0, 0, 3, 3, 3, 3, 3, 3, 0, 4,
}

// smallParseTable is ts_small_parse_table. The entries of a small state
// are its number of groups, and for each group its value, its number of
// symbols and the symbols.
var smallParseTable = []uint16{
	// state 4
	5, 51, 1, 3, 53, 1, 4, 5, 1, 29, 55, 4, 5, 7, 12, 14,
	49, 8, 0, 6, 8, 13, 15, 16, 18, 19,
	// state 5
	5, 59, 1, 3, 62, 1, 4, 5, 1, 29, 65, 4, 5, 7, 12, 14,
	57, 8, 0, 6, 8, 13, 15, 16, 18, 19,
	// state 6
	2, 69, 5, 3, 5, 7, 12, 14, 67, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 7
	2, 73, 5, 3, 5, 7, 12, 14, 71, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 8
	2, 77, 5, 3, 5, 7, 12, 14, 75, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 9
	2, 81, 5, 3, 5, 7, 12, 14, 79, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 10
	2, 85, 5, 3, 5, 7, 12, 14, 83, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 11
	2, 89, 5, 3, 5, 7, 12, 14, 87, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 12
	2, 93, 5, 3, 5, 7, 12, 14, 91, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 13
	2, 97, 5, 3, 5, 7, 12, 14, 95, 9, 0, 4, 6, 8, 13, 15,
	16, 18, 19,
	// state 14
	5, 99, 1, 1, 101, 1, 2, 19, 1, 28, 25, 1, 21, 103, 3, 9,
	10, 17,
	// state 15
	5, 105, 1, 1, 107, 1, 2, 16, 1, 28, 24, 1, 21, 109, 3, 9,
	10, 11,
	// state 16
	4, 111, 1, 1, 113, 1, 2, 17, 1, 28, 115, 3, 9, 10, 11,
	// state 17
	4, 117, 1, 1, 120, 1, 2, 17, 1, 28, 123, 3, 9, 10, 11,
	// state 18
	4, 125, 1, 1, 128, 1, 2, 18, 1, 28, 123, 3, 9, 10, 17,
	// state 19
	4, 131, 1, 1, 133, 1, 2, 18, 1, 28, 115, 3, 9, 10, 17,
	// state 20
	5, 135, 1, 1, 137, 1, 2, 139, 1, 9, 22, 1, 28, 28, 1, 21,
	// state 21
	5, 135, 1, 1, 137, 1, 2, 141, 1, 9, 22, 1, 28, 27, 1, 21,
	// state 22
	4, 115, 1, 9, 143, 1, 1, 145, 1, 2, 23, 1, 28,
	// state 23
	4, 123, 1, 9, 147, 1, 1, 150, 1, 2, 23, 1, 28,
	// state 24
	1, 153, 3, 9, 10, 11,
	// state 25
	1, 155, 3, 9, 10, 17,
	// state 26
	1, 157, 1, 0,
	// state 27
	1, 159, 1, 9,
	// state 28
	1, 161, 1, 9,
}

// smallParseTableMap is ts_small_parse_table_map.
var smallParseTableMap = []uint32{
	0, 26, 52, 71, 90, 109, 128, 147, 166, 185, 204, 222, 240, 255, 270, 285,
	300, 316, 332, 345, 358, 364, 370, 374, 378,
}

// parseActions is ts_parse_actions. Each group of actions is one entry
// with the header of the group, and then its actions.
var parseActions = []abi.ParseActionEntry{
	{Entry: header{Count: 0}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeRecover}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 0, Symbol: 20}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 15}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 15}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 20}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 20}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 4, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 4, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 15, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 15, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 14, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 14, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 20, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 27}}}, {Action: action{Type: typeShift, Shift: shift{State: 21, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 22}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 5}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 5}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}}, {Action: action{Type: typeShift, Shift: shift{State: 5, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}}, {Action: action{Type: typeShift, Shift: shift{State: 5, Repetition: true}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 23}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 24}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 26}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 23}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 25}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 26}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 24}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 25, ProductionID: 1}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 25, ProductionID: 1}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 7}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 6}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 21}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 17, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 17, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 18, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 18, Repetition: true}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 18}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 18}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 10}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 11}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 23}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 23, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}}, {Action: action{Type: typeShift, Shift: shift{State: 23, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 12}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeAccept}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 13}}},
}

// publicSymbolMap is ts_symbol_map.
var publicSymbolMap = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
}

// aliasMap is ts_non_terminal_alias_map.
var aliasMap = []uint16{
	21, 2, 21, 30, 0,
}

// aliasSequences is ts_alias_sequences, MaxAliasSequenceLength entries for each production.
var aliasSequences = []uint16{
	0, 0, 0, 0, 30, 0,
}

// lexModes is ts_lex_modes.
var lexModes = []abi.LexerMode{
	{},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 14},
	{LexState: 2},
	{LexState: 1},
	{LexState: 1},
	{LexState: 1},
	{LexState: 2},
	{LexState: 2},
	{LexState: 3},
	{LexState: 3},
	{LexState: 3},
	{LexState: 3},
	{},
	{},
	{},
	{},
	{},
}

// primaryStateIDs is ts_primary_state_ids.
var primaryStateIDs = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 17, 16, 20, 21, 16, 17, 24, 25, 26, 27, 28,
}

// lex is the main lex function, which mainLexTable runs.
func lex(lexer *abi.Lexer, state uint16) bool {
	return mainLexTable.Lex(lexer, state)
}

// mainLexTable is the lex table of lex. The ranges of each state are sorted.
var mainLexTable = abi.LexTable{
	States: []abi.LexState{
		{Count: 10, EOFState: 15, HasEOF: true},
		{Start: 10, Count: 10},
		{Start: 20, Count: 10},
		{Start: 30, Count: 10},
		{Start: 40, Count: 1},
		{Start: 41, Count: 1},
		{Start: 42, Count: 1},
		{Start: 43, Count: 1},
		{Start: 44, Count: 1},
		{Start: 45, Count: 1},
		{Start: 46, Count: 1},
		{Start: 47, Count: 1},
		{Start: 48, Count: 1},
		{Start: 49, Count: 1},
		{Start: 50, Count: 4, EOFState: 15, HasEOF: true},
		{Start: 54, Accept: 0, HasAccept: true},
		{Start: 54, Accept: 1, HasAccept: true},
		{Start: 54, Count: 2, Accept: 1, HasAccept: true},
		{Start: 56, Count: 1, Accept: 1, HasAccept: true},
		{Start: 57, Count: 1, Accept: 1, HasAccept: true},
		{Start: 58, Count: 1, Accept: 1, HasAccept: true},
		{Start: 59, Count: 6, Accept: 1, HasAccept: true},
		{Start: 65, Accept: 2, HasAccept: true},
		{Start: 65, Count: 1, Accept: 3, HasAccept: true},
		{Start: 66, Count: 3, Accept: 3, HasAccept: true},
		{Start: 69, Accept: 4, HasAccept: true},
		{Start: 69, Count: 8, Accept: 5, HasAccept: true},
		{Start: 77, Accept: 6, HasAccept: true},
		{Start: 77, Count: 1, Accept: 7, HasAccept: true},
		{Start: 78, Accept: 8, HasAccept: true},
		{Start: 78, Accept: 9, HasAccept: true},
		{Start: 78, Accept: 10, HasAccept: true},
		{Start: 78, Accept: 11, HasAccept: true},
		{Start: 78, Count: 1, Accept: 12, HasAccept: true},
		{Start: 79, Accept: 13, HasAccept: true},
		{Start: 79, Count: 1, Accept: 14, HasAccept: true},
		{Start: 80, Accept: 15, HasAccept: true},
		{Start: 80, Accept: 16, HasAccept: true},
		{Start: 80, Accept: 17, HasAccept: true},
		{Start: 80, Accept: 18, HasAccept: true},
		{Start: 80, Accept: 19, HasAccept: true},
	},
	Ranges: []abi.LexRange{
		{Lo: -2147483648, Hi: -1, State: 21}, {Lo: 0x01, Hi: '$', State: 21}, {Lo: '%', Hi: '%', State: 17}, {Lo: '&', Hi: ',', State: 21},
		{Lo: '-', Hi: '-', State: 18}, {Lo: '.', Hi: '<', State: 21}, {Lo: '=', Hi: '=', State: 19}, {Lo: '>', Hi: '^', State: 21},
		{Lo: '_', Hi: '_', State: 20}, {Lo: '`', Hi: 0x7fffffff, State: 21}, {Lo: -2147483648, Hi: -1, State: 21}, {Lo: 0x01, Hi: '$', State: 21},
		{Lo: '%', Hi: '%', State: 17}, {Lo: '&', Hi: ',', State: 21}, {Lo: '-', Hi: '-', State: 18}, {Lo: '.', Hi: '<', State: 21},
		{Lo: '=', Hi: '=', State: 16}, {Lo: '>', Hi: '^', State: 21}, {Lo: '_', Hi: '_', State: 20}, {Lo: '`', Hi: 0x7fffffff, State: 21},
		{Lo: -2147483648, Hi: -1, State: 21}, {Lo: 0x01, Hi: '$', State: 21}, {Lo: '%', Hi: '%', State: 17}, {Lo: '&', Hi: ',', State: 21},
		{Lo: '-', Hi: '-', State: 18}, {Lo: '.', Hi: '<', State: 21}, {Lo: '=', Hi: '=', State: 19}, {Lo: '>', Hi: '^', State: 21},
		{Lo: '_', Hi: '_', State: 16}, {Lo: '`', Hi: 0x7fffffff, State: 21}, {Lo: -2147483648, Hi: -1, State: 21}, {Lo: 0x01, Hi: '$', State: 21},
		{Lo: '%', Hi: '%', State: 17}, {Lo: '&', Hi: ',', State: 21}, {Lo: '-', Hi: '-', State: 16}, {Lo: '.', Hi: '<', State: 21},
		{Lo: '=', Hi: '=', State: 16}, {Lo: '>', Hi: '^', State: 21}, {Lo: '_', Hi: '_', State: 16}, {Lo: '`', Hi: 0x7fffffff, State: 21},
		{Lo: '>', Hi: '>', State: 22}, {Lo: '>', Hi: '>', State: 31}, {Lo: '>', Hi: '>', State: 38}, {Lo: '>', Hi: '>', State: 32},
		{Lo: 'a', Hi: 'a', State: 11}, {Lo: 'h', Hi: 'h', State: 12}, {Lo: 'l', Hi: 'l', State: 40}, {Lo: 'p', Hi: 'p', State: 9},
		{Lo: 'q', Hi: 'q', State: 10}, {Lo: 'r', Hi: 'r', State: 8}, {Lo: -2147483648, Hi: -1, State: 24}, {Lo: 0x01, Hi: ';', State: 24},
		{Lo: '<', Hi: '<', State: 23}, {Lo: '=', Hi: 0x7fffffff, State: 24}, {Lo: '%', Hi: '%', State: 4}, {Lo: '>', Hi: '>', State: 30},
		{Lo: '%', Hi: '%', State: 5}, {Lo: '%', Hi: '%', State: 6}, {Lo: '%', Hi: '%', State: 7}, {Lo: -2147483648, Hi: -1, State: 21},
		{Lo: 0x01, Hi: '$', State: 21}, {Lo: '&', Hi: ',', State: 21}, {Lo: '.', Hi: '<', State: 21}, {Lo: '>', Hi: '^', State: 21},
		{Lo: '`', Hi: 0x7fffffff, State: 21}, {Lo: '%', Hi: '%', State: 26}, {Lo: -2147483648, Hi: -1, State: 24}, {Lo: 0x01, Hi: ';', State: 24},
		{Lo: '=', Hi: 0x7fffffff, State: 24}, {Lo: '#', Hi: '#', State: 39}, {Lo: '%', Hi: '%', State: 25}, {Lo: '-', Hi: '-', State: 37},
		{Lo: '=', Hi: '=', State: 33}, {Lo: '_', Hi: '_', State: 27}, {Lo: 'g', Hi: 'g', State: 13}, {Lo: '|', Hi: '|', State: 28},
		{Lo: '~', Hi: '~', State: 29}, {Lo: '=', Hi: '=', State: 35}, {Lo: '=', Hi: '=', State: 34}, {Lo: '=', Hi: '=', State: 36},
	},
}
