/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_if = 1,
  anon_sym_SLASH = 2,
  sym_regex = 3,
  sym_number = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  sym_expression = 7,
  sym_conditional = 8,
  sym_quotient = 9,
  sym_parenthesized = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_if] = "if",
  [anon_sym_SLASH] = "/",
  [sym_regex] = "regex",
  [sym_number] = "number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_expression] = "expression",
  [sym_conditional] = "conditional",
  [sym_quotient] = "quotient",
  [sym_parenthesized] = "parenthesized",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_regex] = sym_regex,
  [sym_number] = sym_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_expression] = sym_expression,
  [sym_conditional] = sym_conditional,
  [sym_quotient] = sym_quotient,
  [sym_parenthesized] = sym_parenthesized,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_quotient] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_regex);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_expression] = STATE(12),
    [sym_conditional] = STATE(7),
    [sym_quotient] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [anon_sym_if] = ACTIONS(3),
    [sym_regex] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(13),
    [sym_conditional] = STATE(7),
    [sym_quotient] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [anon_sym_if] = ACTIONS(3),
    [sym_regex] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(8),
    [sym_conditional] = STATE(7),
    [sym_quotient] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [anon_sym_if] = ACTIONS(3),
    [sym_regex] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(10),
    [sym_conditional] = STATE(7),
    [sym_quotient] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [anon_sym_if] = ACTIONS(3),
    [sym_regex] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(14),
    [sym_conditional] = STATE(7),
    [sym_quotient] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [anon_sym_if] = ACTIONS(3),
    [sym_regex] = ACTIONS(5),
    [sym_number] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(9), 4,
      anon_sym_if,
      sym_regex,
      sym_number,
      anon_sym_LPAREN,
  [7] = 1,
    ACTIONS(11), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [13] = 1,
    ACTIONS(13), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [19] = 1,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [25] = 1,
    ACTIONS(15), 3,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [31] = 2,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_parenthesized,
  [38] = 2,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_SLASH,
  [45] = 2,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
  [52] = 2,
    ACTIONS(21), 1,
      anon_sym_SLASH,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 7,
  [SMALL_STATE(8)] = 13,
  [SMALL_STATE(9)] = 19,
  [SMALL_STATE(10)] = 25,
  [SMALL_STATE(11)] = 31,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 45,
  [SMALL_STATE(14)] = 52,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 3, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quotient, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lexical_conflicts_due_to_state_merging(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lexical_conflicts_due_to_state_merging",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
