// Code generated by transit. DO NOT EDIT.

package ydb_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/ydb"
)

// This example parses a text of the grammar yql, the input of the corpus case
// "basics/Simple select literal", and prints its tree. Then it compiles each
// query of the package, and prints the number of its patterns.
func ExampleLanguage() {
	language := ydb.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`
SELECT 1;
`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(ydb.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(ydb.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (source_file (select_statement (select_body (select_clause (select_list (select_item (integer_literal)))))))
	// patterns in queries/highlights.scm: 207
	// patterns in queries/locals.scm: 14
}
