// Code generated by transit. DO NOT EDIT.

package php_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/php/php"
)

// This example parses a text of the grammar php, the input of the corpus case
// "bugs/Parse error when using self as constant", and prints its tree. Then it
// compiles each query of the package, and prints the number of its patterns.
func ExampleLanguage() {
	language := php.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`
<?php
define('self', 'value');
var_dump(self);
`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(php.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(php.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (program (php_tag) (expression_statement (function_call_expression function: (name) arguments: (arguments (argument (string (string_content))) (argument (string (string_content)))))) (expression_statement (function_call_expression function: (name) arguments: (arguments (argument (name))))))
	// patterns in queries/highlights.scm: 40
	// patterns in queries/injections-text.scm: 1
	// patterns in queries/injections.scm: 3
	// patterns in queries/tags.scm: 12
}
