// Code generated by transit. DO NOT EDIT.

package java_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/java"
)

// This example parses a text of the grammar java, the input of the corpus case
// "comments/comments and literals", and prints its tree. Then it compiles each
// query of the package, and prints the number of its patterns.
func ExampleLanguage() {
	language := java.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`
123;
// comment
`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(java.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(java.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (program (expression_statement (decimal_integer_literal)) (line_comment))
	// patterns in queries/highlights.scm: 25
	// patterns in queries/tags.scm: 7
}
