// Code generated by transit. DO NOT EDIT.

// Package html is the grammar html for the Go runtime of transit. Language
// returns its language, and the constants name its symbols and its fields.
package html

import (
	"embed"
	"encoding/json"
	"sync"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/abi"
)

// Language returns the language of the grammar html. Its external scanner is
// the scanner that newScanner returns.
func Language() *transit.Language {
	return language()
}

// language builds the language once. The tables are static data, so this
// copies no table.
var language = sync.OnceValue(func() *transit.Language {
	return transit.NewLanguage(&abi.Language{
		ABIVersion:             15,
		SymbolCount:            41,
		AliasCount:             0,
		TokenCount:             25,
		ExternalTokenCount:     9,
		StateCount:             94,
		LargeStateCount:        2,
		ProductionIDCount:      1,
		FieldCount:             0,
		MaxAliasSequenceLength: 4,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		SymbolNames:            symbolNames,
		SymbolMetadata:         symbolMetadata,
		PublicSymbolMap:        publicSymbolMap,
		AliasMap:               aliasMap,
		AliasSequences:         aliasSequences,
		LexModes:               lexModes,
		LexFn:                  lex,
		KeywordCaptureToken:    0,
		ExternalScanner: abi.ExternalScanner{
			States:    externalScannerStates,
			SymbolMap: externalScannerSymbolMap,
			Create:    func() abi.Scanner { return newScanner() },
		},
		PrimaryStateIDs:        primaryStateIDs,
		Name:                   "html",
		MaxReservedWordSetSize: 0,
		SupertypeCount:         0,
		Metadata:               abi.LanguageMetadata{MajorVersion: 0, MinorVersion: 23, PatchVersion: 2},
	})
})

// Queries holds queries/ of the grammar html: its own queries, and in
// queries/<grammar>/ the queries of another grammar that its tree-sitter.json
// lists (D84).
//
//go:embed queries
var Queries embed.FS

// nodeTypes is node-types.json of the grammar.
//
//go:embed node-types.json
var nodeTypes []byte

// NodeTypes returns the node types of node-types.json of the grammar html: the
// fields and the children of each node, and the subtypes of each supertype.
// Each call returns a new slice.
func NodeTypes() []transit.NodeType {
	var types []transit.NodeType
	if err := json.Unmarshal(nodeTypes, &types); err != nil {
		// the generator writes node-types.json, so it is valid
		panic("html: reading node-types.json: " + err.Error())
	}
	return types
}

// Keywords returns the keywords of the grammar html: the tokens that the word
// token captures, and the reserved words. Each call returns a new slice.
func Keywords() []string {
	return nil
}

// The symbols of the grammar html, as Node.KindID and Node.GrammarID
// return them. The comment of each one is its name.
const (
	BuiltinSymEnd                    transit.Symbol = 0  // "end"
	AnonSymLTBANG                    transit.Symbol = 1  // "<!"
	AuxSymDoctypeToken1              transit.Symbol = 2  // "doctype_token1"
	AnonSymGT                        transit.Symbol = 3  // ">"
	SymDoctype                       transit.Symbol = 4  // "doctype"
	AnonSymLT                        transit.Symbol = 5  // "<"
	AnonSymSLASHGT                   transit.Symbol = 6  // "/>"
	AnonSymLTSLASH                   transit.Symbol = 7  // "</"
	AnonSymEQ                        transit.Symbol = 8  // "="
	SymAttributeName                 transit.Symbol = 9  // "attribute_name"
	SymAttributeValue                transit.Symbol = 10 // "attribute_value"
	SymEntity                        transit.Symbol = 11 // "entity"
	AnonSymSQUOTE                    transit.Symbol = 12 // "'"
	AuxSymQuotedAttributeValueToken1 transit.Symbol = 13 // "attribute_value"
	AnonSymDQUOTE                    transit.Symbol = 14 // "\""
	AuxSymQuotedAttributeValueToken2 transit.Symbol = 15 // "attribute_value"
	SymText                          transit.Symbol = 16 // "text"
	SymStartTagName                  transit.Symbol = 17 // "tag_name"
	SymScriptStartTagName            transit.Symbol = 18 // "tag_name"
	SymStyleStartTagName             transit.Symbol = 19 // "tag_name"
	SymEndTagName                    transit.Symbol = 20 // "tag_name"
	SymErroneousEndTagName           transit.Symbol = 21 // "erroneous_end_tag_name"
	SymImplicitEndTag                transit.Symbol = 22 // "_implicit_end_tag"
	SymRawText                       transit.Symbol = 23 // "raw_text"
	SymComment                       transit.Symbol = 24 // "comment"
	SymDocument                      transit.Symbol = 25 // "document"
	SymDoctype2                      transit.Symbol = 26 // "doctype"
	SymNode                          transit.Symbol = 27 // "_node"
	SymElement                       transit.Symbol = 28 // "element"
	SymScriptElement                 transit.Symbol = 29 // "script_element"
	SymStyleElement                  transit.Symbol = 30 // "style_element"
	SymStartTag                      transit.Symbol = 31 // "start_tag"
	SymScriptStartTag                transit.Symbol = 32 // "start_tag"
	SymStyleStartTag                 transit.Symbol = 33 // "start_tag"
	SymSelfClosingTag                transit.Symbol = 34 // "self_closing_tag"
	SymEndTag                        transit.Symbol = 35 // "end_tag"
	SymErroneousEndTag               transit.Symbol = 36 // "erroneous_end_tag"
	SymAttribute                     transit.Symbol = 37 // "attribute"
	SymQuotedAttributeValue          transit.Symbol = 38 // "quoted_attribute_value"
	AuxSymDocumentRepeat1            transit.Symbol = 39 // "document_repeat1"
	AuxSymStartTagRepeat1            transit.Symbol = 40 // "start_tag_repeat1"
)

// The short names of the types of the tables.
type (
	action = abi.ParseAction
	header = abi.EntryHeader
	shift  = abi.ShiftAction
	reduce = abi.ReduceAction
)

// The kinds of a parse action.
const (
	typeShift   = abi.ParseActionTypeShift
	typeReduce  = abi.ParseActionTypeReduce
	typeAccept  = abi.ParseActionTypeAccept
	typeRecover = abi.ParseActionTypeRecover
)

// symbolNames is ts_symbol_names.
var symbolNames = []string{
	BuiltinSymEnd:                    "end",
	AnonSymLTBANG:                    "<!",
	AuxSymDoctypeToken1:              "doctype_token1",
	AnonSymGT:                        ">",
	SymDoctype:                       "doctype",
	AnonSymLT:                        "<",
	AnonSymSLASHGT:                   "/>",
	AnonSymLTSLASH:                   "</",
	AnonSymEQ:                        "=",
	SymAttributeName:                 "attribute_name",
	SymAttributeValue:                "attribute_value",
	SymEntity:                        "entity",
	AnonSymSQUOTE:                    "'",
	AuxSymQuotedAttributeValueToken1: "attribute_value",
	AnonSymDQUOTE:                    "\"",
	AuxSymQuotedAttributeValueToken2: "attribute_value",
	SymText:                          "text",
	SymStartTagName:                  "tag_name",
	SymScriptStartTagName:            "tag_name",
	SymStyleStartTagName:             "tag_name",
	SymEndTagName:                    "tag_name",
	SymErroneousEndTagName:           "erroneous_end_tag_name",
	SymImplicitEndTag:                "_implicit_end_tag",
	SymRawText:                       "raw_text",
	SymComment:                       "comment",
	SymDocument:                      "document",
	SymDoctype2:                      "doctype",
	SymNode:                          "_node",
	SymElement:                       "element",
	SymScriptElement:                 "script_element",
	SymStyleElement:                  "style_element",
	SymStartTag:                      "start_tag",
	SymScriptStartTag:                "start_tag",
	SymStyleStartTag:                 "start_tag",
	SymSelfClosingTag:                "self_closing_tag",
	SymEndTag:                        "end_tag",
	SymErroneousEndTag:               "erroneous_end_tag",
	SymAttribute:                     "attribute",
	SymQuotedAttributeValue:          "quoted_attribute_value",
	AuxSymDocumentRepeat1:            "document_repeat1",
	AuxSymStartTagRepeat1:            "start_tag_repeat1",
}

// symbolMetadata is ts_symbol_metadata.
var symbolMetadata = []abi.SymbolMetadata{
	BuiltinSymEnd:                    {Named: true},
	AnonSymLTBANG:                    {Visible: true},
	AuxSymDoctypeToken1:              {},
	AnonSymGT:                        {Visible: true},
	SymDoctype:                       {Visible: true},
	AnonSymLT:                        {Visible: true},
	AnonSymSLASHGT:                   {Visible: true},
	AnonSymLTSLASH:                   {Visible: true},
	AnonSymEQ:                        {Visible: true},
	SymAttributeName:                 {Visible: true, Named: true},
	SymAttributeValue:                {Visible: true, Named: true},
	SymEntity:                        {Visible: true, Named: true},
	AnonSymSQUOTE:                    {Visible: true},
	AuxSymQuotedAttributeValueToken1: {Visible: true, Named: true},
	AnonSymDQUOTE:                    {Visible: true},
	AuxSymQuotedAttributeValueToken2: {Visible: true, Named: true},
	SymText:                          {Visible: true, Named: true},
	SymStartTagName:                  {Visible: true, Named: true},
	SymScriptStartTagName:            {Visible: true, Named: true},
	SymStyleStartTagName:             {Visible: true, Named: true},
	SymEndTagName:                    {Visible: true, Named: true},
	SymErroneousEndTagName:           {Visible: true, Named: true},
	SymImplicitEndTag:                {Named: true},
	SymRawText:                       {Visible: true, Named: true},
	SymComment:                       {Visible: true, Named: true},
	SymDocument:                      {Visible: true, Named: true},
	SymDoctype2:                      {Visible: true, Named: true},
	SymNode:                          {Named: true},
	SymElement:                       {Visible: true, Named: true},
	SymScriptElement:                 {Visible: true, Named: true},
	SymStyleElement:                  {Visible: true, Named: true},
	SymStartTag:                      {Visible: true, Named: true},
	SymScriptStartTag:                {Visible: true, Named: true},
	SymStyleStartTag:                 {Visible: true, Named: true},
	SymSelfClosingTag:                {Visible: true, Named: true},
	SymEndTag:                        {Visible: true, Named: true},
	SymErroneousEndTag:               {Visible: true, Named: true},
	SymAttribute:                     {Visible: true, Named: true},
	SymQuotedAttributeValue:          {Visible: true, Named: true},
	AuxSymDocumentRepeat1:            {},
	AuxSymStartTagRepeat1:            {},
}

// parseTable is ts_parse_table, one row of SymbolCount entries for each large state.
var parseTable = []uint16{
	// state 0
	1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
	0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0,
	// state 1
	5, 7, 0, 0, 0, 9, 0, 11, 0, 0, 0, 13, 0, 0, 0, 0,
	13, 0, 0, 0, 0, 0, 0, 0, 3, 83, 7, 7, 7, 7, 7, 2,
	48, 53, 33, 0, 7, 0, 0, 7, 0,
}

// smallParseTable is ts_small_parse_table. The entries of a small state
// are its number of groups, and for each group its value, its number of
// symbols and the symbols.
var smallParseTable = []uint16{
	// state 2
	12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 19, 1, 7, 23, 1, 22,
	5, 1, 31, 21, 1, 34, 32, 1, 35, 54, 1, 32, 55, 1, 33, 21,
	2, 11, 16, 3, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 3
	12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 19, 1, 7, 27, 1, 22,
	5, 1, 31, 14, 1, 35, 21, 1, 34, 54, 1, 32, 55, 1, 33, 25,
	2, 11, 16, 6, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 4
	12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 29, 1, 7, 31, 1, 22,
	5, 1, 31, 21, 1, 34, 27, 1, 35, 54, 1, 32, 55, 1, 33, 25,
	2, 11, 16, 6, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 5
	12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 29, 1, 7, 35, 1, 22,
	5, 1, 31, 21, 1, 34, 22, 1, 35, 54, 1, 32, 55, 1, 33, 33,
	2, 11, 16, 4, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 6
	11, 3, 1, 24, 37, 1, 1, 40, 1, 5, 43, 1, 7, 49, 1, 22,
	5, 1, 31, 21, 1, 34, 54, 1, 32, 55, 1, 33, 46, 2, 11, 16,
	6, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 7
	11, 3, 1, 24, 7, 1, 1, 9, 1, 5, 11, 1, 7, 51, 1, 0,
	2, 1, 31, 33, 1, 34, 48, 1, 32, 53, 1, 33, 53, 2, 11, 16,
	8, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 8
	11, 3, 1, 24, 49, 1, 0, 55, 1, 1, 58, 1, 5, 61, 1, 7,
	2, 1, 31, 33, 1, 34, 48, 1, 32, 53, 1, 33, 64, 2, 11, 16,
	8, 7, 26, 27, 28, 29, 30, 36, 39,
	// state 9
	3, 3, 1, 24, 69, 1, 5, 67, 5, 22, 1, 7, 11, 16,
	// state 10
	3, 3, 1, 24, 73, 1, 5, 71, 5, 0, 1, 7, 11, 16,
	// state 11
	3, 3, 1, 24, 77, 1, 5, 75, 5, 22, 1, 7, 11, 16,
	// state 12
	3, 3, 1, 24, 81, 1, 5, 79, 5, 0, 1, 7, 11, 16,
	// state 13
	3, 3, 1, 24, 85, 1, 5, 83, 5, 0, 1, 7, 11, 16,
	// state 14
	3, 3, 1, 24, 89, 1, 5, 87, 5, 0, 1, 7, 11, 16,
	// state 15
	3, 3, 1, 24, 93, 1, 5, 91, 5, 0, 1, 7, 11, 16,
	// state 16
	3, 3, 1, 24, 97, 1, 5, 95, 5, 0, 1, 7, 11, 16,
	// state 17
	3, 3, 1, 24, 101, 1, 5, 99, 5, 0, 1, 7, 11, 16,
	// state 18
	3, 3, 1, 24, 105, 1, 5, 103, 5, 22, 1, 7, 11, 16,
	// state 19
	3, 3, 1, 24, 109, 1, 5, 107, 5, 0, 1, 7, 11, 16,
	// state 20
	3, 3, 1, 24, 69, 1, 5, 67, 5, 0, 1, 7, 11, 16,
	// state 21
	3, 3, 1, 24, 113, 1, 5, 111, 5, 22, 1, 7, 11, 16,
	// state 22
	3, 3, 1, 24, 117, 1, 5, 115, 5, 22, 1, 7, 11, 16,
	// state 23
	3, 3, 1, 24, 109, 1, 5, 107, 5, 22, 1, 7, 11, 16,
	// state 24
	3, 3, 1, 24, 73, 1, 5, 71, 5, 22, 1, 7, 11, 16,
	// state 25
	3, 3, 1, 24, 81, 1, 5, 79, 5, 22, 1, 7, 11, 16,
	// state 26
	3, 3, 1, 24, 85, 1, 5, 83, 5, 22, 1, 7, 11, 16,
	// state 27
	3, 3, 1, 24, 89, 1, 5, 87, 5, 22, 1, 7, 11, 16,
	// state 28
	3, 3, 1, 24, 93, 1, 5, 91, 5, 22, 1, 7, 11, 16,
	// state 29
	3, 3, 1, 24, 97, 1, 5, 95, 5, 22, 1, 7, 11, 16,
	// state 30
	3, 3, 1, 24, 101, 1, 5, 99, 5, 22, 1, 7, 11, 16,
	// state 31
	3, 3, 1, 24, 121, 1, 5, 119, 5, 22, 1, 7, 11, 16,
	// state 32
	3, 3, 1, 24, 117, 1, 5, 115, 5, 0, 1, 7, 11, 16,
	// state 33
	3, 3, 1, 24, 113, 1, 5, 111, 5, 0, 1, 7, 11, 16,
	// state 34
	3, 3, 1, 24, 121, 1, 5, 119, 5, 0, 1, 7, 11, 16,
	// state 35
	4, 3, 1, 24, 125, 1, 9, 123, 2, 3, 6, 35, 2, 37, 40,
	// state 36
	5, 3, 1, 24, 128, 1, 3, 130, 1, 6, 132, 1, 9, 35, 2, 37,
	40,
	// state 37
	5, 3, 1, 24, 132, 1, 9, 134, 1, 3, 136, 1, 6, 38, 2, 37,
	40,
	// state 38
	5, 3, 1, 24, 128, 1, 3, 132, 1, 9, 138, 1, 6, 35, 2, 37,
	40,
	// state 39
	5, 3, 1, 24, 132, 1, 9, 134, 1, 3, 140, 1, 6, 36, 2, 37,
	40,
	// state 40
	4, 3, 1, 24, 142, 1, 3, 144, 1, 9, 41, 2, 37, 40,
	// state 41
	4, 3, 1, 24, 123, 1, 3, 146, 1, 9, 41, 2, 37, 40,
	// state 42
	4, 3, 1, 24, 144, 1, 9, 149, 1, 3, 40, 2, 37, 40,
	// state 43
	4, 3, 1, 24, 144, 1, 9, 151, 1, 3, 44, 2, 37, 40,
	// state 44
	4, 3, 1, 24, 144, 1, 9, 153, 1, 3, 41, 2, 37, 40,
	// state 45
	3, 3, 1, 24, 157, 1, 8, 155, 3, 3, 6, 9,
	// state 46
	5, 3, 1, 24, 159, 1, 10, 161, 1, 12, 163, 1, 14, 56, 1, 38,
	// state 47
	5, 3, 1, 24, 165, 1, 10, 167, 1, 12, 169, 1, 14, 58, 1, 38,
	// state 48
	4, 3, 1, 24, 171, 1, 7, 173, 1, 23, 19, 1, 35,
	// state 49
	2, 3, 1, 24, 175, 3, 3, 6, 9,
	// state 50
	2, 3, 1, 24, 177, 3, 3, 6, 9,
	// state 51
	3, 3, 1, 24, 179, 1, 8, 155, 2, 3, 9,
	// state 52
	4, 3, 1, 24, 181, 1, 17, 183, 1, 18, 185, 1, 19,
	// state 53
	4, 3, 1, 24, 171, 1, 7, 187, 1, 23, 10, 1, 35,
	// state 54
	4, 3, 1, 24, 189, 1, 7, 191, 1, 23, 23, 1, 35,
	// state 55
	4, 3, 1, 24, 189, 1, 7, 193, 1, 23, 24, 1, 35,
	// state 56
	2, 3, 1, 24, 195, 3, 3, 6, 9,
	// state 57
	4, 3, 1, 24, 183, 1, 18, 185, 1, 19, 197, 1, 17,
	// state 58
	2, 3, 1, 24, 195, 2, 3, 9,
	// state 59
	3, 3, 1, 24, 199, 1, 20, 201, 1, 21,
	// state 60
	3, 3, 1, 24, 171, 1, 7, 16, 1, 35,
	// state 61
	2, 3, 1, 24, 203, 2, 23, 7,
	// state 62
	3, 3, 1, 24, 205, 1, 14, 207, 1, 15,
	// state 63
	2, 3, 1, 24, 175, 2, 3, 9,
	// state 64
	2, 3, 1, 24, 177, 2, 3, 9,
	// state 65
	2, 3, 1, 24, 209, 2, 23, 7,
	// state 66
	2, 3, 1, 24, 211, 2, 23, 7,
	// state 67
	2, 3, 1, 24, 213, 2, 23, 7,
	// state 68
	3, 3, 1, 24, 201, 1, 21, 215, 1, 20,
	// state 69
	3, 3, 1, 24, 189, 1, 7, 28, 1, 35,
	// state 70
	3, 3, 1, 24, 189, 1, 7, 29, 1, 35,
	// state 71
	3, 3, 1, 24, 171, 1, 7, 15, 1, 35,
	// state 72
	3, 3, 1, 24, 205, 1, 12, 217, 1, 13,
	// state 73
	3, 3, 1, 24, 219, 1, 12, 221, 1, 13,
	// state 74
	3, 3, 1, 24, 219, 1, 14, 223, 1, 15,
	// state 75
	2, 3, 1, 24, 225, 1, 14,
	// state 76
	2, 3, 1, 24, 227, 1, 14,
	// state 77
	2, 3, 1, 24, 229, 1, 4,
	// state 78
	2, 3, 1, 24, 227, 1, 12,
	// state 79
	2, 3, 1, 24, 231, 1, 3,
	// state 80
	2, 3, 1, 24, 233, 1, 3,
	// state 81
	2, 3, 1, 24, 235, 1, 2,
	// state 82
	2, 3, 1, 24, 237, 1, 3,
	// state 83
	2, 3, 1, 24, 239, 1, 0,
	// state 84
	2, 3, 1, 24, 241, 1, 3,
	// state 85
	2, 3, 1, 24, 243, 1, 21,
	// state 86
	2, 3, 1, 24, 225, 1, 12,
	// state 87
	2, 3, 1, 24, 245, 1, 3,
	// state 88
	2, 3, 1, 24, 215, 1, 20,
	// state 89
	2, 3, 1, 24, 201, 1, 21,
	// state 90
	2, 3, 1, 24, 247, 1, 2,
	// state 91
	2, 3, 1, 24, 249, 1, 3,
	// state 92
	2, 3, 1, 24, 199, 1, 20,
	// state 93
	2, 3, 1, 24, 251, 1, 4,
}

// smallParseTableMap is ts_small_parse_table_map.
var smallParseTableMap = []uint32{
	0, 44, 88, 132, 176, 217, 258, 299, 313, 327, 341, 355, 369, 383, 397, 411,
	425, 439, 453, 467, 481, 495, 509, 523, 537, 551, 565, 579, 593, 607, 621, 635,
	649, 663, 678, 695, 712, 729, 746, 760, 774, 788, 802, 816, 828, 844, 860, 873,
	882, 891, 902, 915, 928, 941, 954, 963, 976, 984, 994, 1004, 1012, 1022, 1030, 1038,
	1046, 1054, 1062, 1072, 1082, 1092, 1102, 1112, 1122, 1132, 1139, 1146, 1153, 1160, 1167, 1174,
	1181, 1188, 1195, 1202, 1209, 1216, 1223, 1230, 1237, 1244, 1251, 1258,
}

// parseActions is ts_parse_actions. Each group of actions is one entry
// with the header of the group, and then its actions.
var parseActions = []abi.ParseActionEntry{
	{Entry: header{Count: 0}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeRecover}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{Extra: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 0, Symbol: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 77}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 52}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 85}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 7}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 93}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 57}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 68}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 3}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 32}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 6}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 59}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 27}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 22}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 93, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 57, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 89, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 6, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 77, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 52, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 85, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 39}}}, {Action: action{Type: typeShift, Shift: shift{State: 8, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 35}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 35}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 31}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 31}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 34}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 36}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 36}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 28}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 28}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 29}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 29}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 30}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 30}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 26}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 31}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 31}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 28}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 28}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 28}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 34}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 40}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 40}}}, {Action: action{Type: typeShift, Shift: shift{State: 45, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 18}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 45}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 11}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 31}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 12}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 67}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 51}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 40}}}, {Action: action{Type: typeShift, Shift: shift{State: 51, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 66}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 61}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 65}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 46}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 56}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 72}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 62}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 58}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 73}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 74}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 88}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 71}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 38}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 38}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 47}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 39}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 43}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 42}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 60}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 92}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 69}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 70}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 82}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 91}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 32}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 49}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 76}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 32}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 87}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 78}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 63}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 86}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 75}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 64}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 50}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 81}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 30}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 79}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeAccept}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 13}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 84}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 20}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 80}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 90}}},
}

// publicSymbolMap is ts_symbol_map.
var publicSymbolMap = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 10, 14, 10,
	16, 17, 17, 17, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	31, 31, 34, 35, 36, 37, 38, 39, 40,
}

// aliasMap is ts_non_terminal_alias_map.
var aliasMap = []uint16{
	0,
}

// aliasSequences is ts_alias_sequences, MaxAliasSequenceLength entries for each production.
var aliasSequences = []uint16{
	0, 0, 0, 0,
}

// lexModes is ts_lex_modes.
var lexModes = []abi.LexerMode{
	{ExternalLexState: 1},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 3},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 17, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 1, ExternalLexState: 2},
	{LexState: 1, ExternalLexState: 2},
	{ExternalLexState: 5},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 4},
	{LexState: 5, ExternalLexState: 2},
	{ExternalLexState: 6},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{LexState: 5, ExternalLexState: 4},
	{ExternalLexState: 6},
	{LexState: 5, ExternalLexState: 2},
	{ExternalLexState: 7},
	{ExternalLexState: 2},
	{ExternalLexState: 5},
	{LexState: 2, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{LexState: 5, ExternalLexState: 2},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 5},
	{ExternalLexState: 7},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{LexState: 4, ExternalLexState: 2},
	{LexState: 4, ExternalLexState: 2},
	{LexState: 2, ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{LexState: 15, ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 8},
	{ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 9},
	{ExternalLexState: 8},
	{LexState: 15, ExternalLexState: 2},
	{ExternalLexState: 2},
	{ExternalLexState: 9},
	{ExternalLexState: 2},
}

// primaryStateIDs is ts_primary_state_ids.
var primaryStateIDs = []uint16{
	0, 1, 2, 3, 3, 2, 6, 7, 6, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 9, 21, 22, 19, 10, 12, 13, 14, 15, 16, 17, 31,
	22, 21, 31, 35, 36, 37, 36, 37, 40, 35, 42, 43, 44, 45, 46, 46,
	48, 49, 50, 45, 52, 53, 48, 53, 56, 52, 56, 59, 60, 61, 62, 49,
	50, 65, 66, 67, 59, 69, 60, 69, 72, 72, 62, 75, 75, 77, 78, 79,
	79, 81, 82, 83, 84, 85, 78, 82, 88, 85, 81, 84, 88, 77,
}

// externalScannerStates is ts_external_scanner_states, one row of
// ExternalTokenCount entries for each external lex state.
var externalScannerStates = []bool{
	false, false, false, false, false, false, false, false, false,
	true, true, true, true, true, true, true, true, true,
	false, false, false, false, false, false, false, false, true,
	false, false, false, false, false, false, true, false, true,
	false, false, false, false, false, true, false, false, true,
	false, false, false, false, false, false, false, true, true,
	true, true, true, false, false, false, false, false, true,
	false, false, false, true, true, false, false, false, true,
	false, false, false, false, true, false, false, false, true,
	false, false, false, true, false, false, false, false, true,
}

// externalScannerSymbolMap is ts_external_scanner_symbol_map.
var externalScannerSymbolMap = []uint16{
	17, 18, 19, 20, 21, 6, 22, 23, 24,
}

// lex is the main lex function, which mainLexTable runs.
func lex(lexer *abi.Lexer, state uint16) bool {
	return mainLexTable.Lex(lexer, state)
}

// mainLexTable is the lex table of lex. The ranges of each state are sorted.
var mainLexTable = abi.LexTable{
	States: []abi.LexState{
		{Count: 11, EOFState: 18, HasEOF: true},
		{Start: 11, Count: 11},
		{Start: 22, Count: 8},
		{Start: 30, Count: 3},
		{Start: 33, Count: 8},
		{Start: 41, Count: 13},
		{Start: 54, Count: 1},
		{Start: 55, Count: 2},
		{Start: 57, Count: 2},
		{Start: 59, Count: 2},
		{Start: 61, Count: 2},
		{Start: 63, Count: 2},
		{Start: 65, Count: 3},
		{Start: 68, Count: 2},
		{Start: 70, Count: 9},
		{Start: 79, Count: 7},
		{Start: 86, Count: 3},
		{Start: 89, Count: 11, EOFState: 18, HasEOF: true},
		{Start: 100, Accept: 0, HasAccept: true},
		{Start: 100, Accept: 1, HasAccept: true},
		{Start: 100, Count: 7, Accept: 2, HasAccept: true},
		{Start: 107, Count: 3, Accept: 2, HasAccept: true},
		{Start: 110, Accept: 3, HasAccept: true},
		{Start: 110, Accept: 4, HasAccept: true},
		{Start: 110, Count: 2, Accept: 5, HasAccept: true},
		{Start: 112, Accept: 6, HasAccept: true},
		{Start: 112, Accept: 7, HasAccept: true},
		{Start: 112, Accept: 8, HasAccept: true},
		{Start: 112, Count: 8, Accept: 9, HasAccept: true},
		{Start: 120, Count: 7, Accept: 10, HasAccept: true},
		{Start: 127, Accept: 11, HasAccept: true},
		{Start: 127, Count: 1, Accept: 11, HasAccept: true},
		{Start: 128, Count: 2, Accept: 11, HasAccept: true},
		{Start: 130, Count: 2, Accept: 11, HasAccept: true},
		{Start: 132, Count: 2, Accept: 11, HasAccept: true},
		{Start: 134, Count: 2, Accept: 11, HasAccept: true},
		{Start: 136, Count: 4, Accept: 11, HasAccept: true},
		{Start: 140, Count: 4, Accept: 11, HasAccept: true},
		{Start: 144, Count: 4, Accept: 11, HasAccept: true},
		{Start: 148, Count: 4, Accept: 11, HasAccept: true},
		{Start: 152, Count: 4, Accept: 11, HasAccept: true},
		{Start: 156, Count: 3, Accept: 11, HasAccept: true},
		{Start: 159, Count: 3, Accept: 11, HasAccept: true},
		{Start: 162, Count: 3, Accept: 11, HasAccept: true},
		{Start: 165, Count: 3, Accept: 11, HasAccept: true},
		{Start: 168, Count: 3, Accept: 11, HasAccept: true},
		{Start: 171, Count: 3, Accept: 11, HasAccept: true},
		{Start: 174, Count: 3, Accept: 11, HasAccept: true},
		{Start: 177, Count: 3, Accept: 11, HasAccept: true},
		{Start: 180, Count: 3, Accept: 11, HasAccept: true},
		{Start: 183, Count: 3, Accept: 11, HasAccept: true},
		{Start: 186, Count: 3, Accept: 11, HasAccept: true},
		{Start: 189, Count: 3, Accept: 11, HasAccept: true},
		{Start: 192, Count: 3, Accept: 11, HasAccept: true},
		{Start: 195, Count: 3, Accept: 11, HasAccept: true},
		{Start: 198, Count: 3, Accept: 11, HasAccept: true},
		{Start: 201, Count: 3, Accept: 11, HasAccept: true},
		{Start: 204, Count: 3, Accept: 11, HasAccept: true},
		{Start: 207, Count: 3, Accept: 11, HasAccept: true},
		{Start: 210, Count: 3, Accept: 11, HasAccept: true},
		{Start: 213, Count: 3, Accept: 11, HasAccept: true},
		{Start: 216, Count: 3, Accept: 11, HasAccept: true},
		{Start: 219, Count: 3, Accept: 11, HasAccept: true},
		{Start: 222, Count: 3, Accept: 11, HasAccept: true},
		{Start: 225, Count: 3, Accept: 11, HasAccept: true},
		{Start: 228, Count: 3, Accept: 11, HasAccept: true},
		{Start: 231, Count: 3, Accept: 11, HasAccept: true},
		{Start: 234, Count: 3, Accept: 11, HasAccept: true},
		{Start: 237, Count: 3, Accept: 11, HasAccept: true},
		{Start: 240, Count: 3, Accept: 11, HasAccept: true},
		{Start: 243, Accept: 12, HasAccept: true},
		{Start: 243, Count: 7, Accept: 13, HasAccept: true},
		{Start: 250, Count: 3, Accept: 13, HasAccept: true},
		{Start: 253, Accept: 14, HasAccept: true},
		{Start: 253, Count: 7, Accept: 15, HasAccept: true},
		{Start: 260, Count: 3, Accept: 15, HasAccept: true},
		{Start: 263, Count: 9, Accept: 16, HasAccept: true},
	},
	Ranges: []abi.LexRange{
		{Lo: '\t', Hi: '\r', State: 0, Skip: true}, {Lo: ' ', Hi: ' ', State: 0, Skip: true}, {Lo: '"', Hi: '"', State: 73}, {Lo: '&', Hi: '&', State: 3},
		{Lo: '\'', Hi: '\'', State: 70}, {Lo: '/', Hi: '/', State: 6}, {Lo: '<', Hi: '<', State: 24}, {Lo: '=', Hi: '=', State: 27},
		{Lo: '>', Hi: '>', State: 22}, {Lo: 'D', Hi: 'D', State: 9}, {Lo: 'd', Hi: 'd', State: 9}, {Lo: -2147483648, Hi: -1, State: 29},
		{Lo: 0x01, Hi: 0x08, State: 29}, {Lo: '\t', Hi: '\r', State: 1, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 29}, {Lo: ' ', Hi: ' ', State: 1, Skip: true},
		{Lo: '!', Hi: '!', State: 29}, {Lo: '"', Hi: '"', State: 73}, {Lo: '#', Hi: '&', State: 29}, {Lo: '\'', Hi: '\'', State: 70},
		{Lo: '(', Hi: ';', State: 29}, {Lo: '?', Hi: 0x7fffffff, State: 29}, {Lo: -2147483648, Hi: -1, State: 75}, {Lo: 0x01, Hi: 0x08, State: 75},
		{Lo: '\t', Hi: '\r', State: 74}, {Lo: 0x0e, Hi: 0x1f, State: 75}, {Lo: ' ', Hi: ' ', State: 74}, {Lo: '!', Hi: '!', State: 75},
		{Lo: '"', Hi: '"', State: 73}, {Lo: '#', Hi: 0x7fffffff, State: 75}, {Lo: '#', Hi: '#', State: 12}, {Lo: 'A', Hi: 'Z', State: 69},
		{Lo: 'a', Hi: 'z', State: 69}, {Lo: -2147483648, Hi: -1, State: 72}, {Lo: 0x01, Hi: 0x08, State: 72}, {Lo: '\t', Hi: '\r', State: 71},
		{Lo: 0x0e, Hi: 0x1f, State: 72}, {Lo: ' ', Hi: ' ', State: 71}, {Lo: '!', Hi: '&', State: 72}, {Lo: '\'', Hi: '\'', State: 70},
		{Lo: '(', Hi: 0x7fffffff, State: 72}, {Lo: -2147483648, Hi: -1, State: 28}, {Lo: 0x01, Hi: 0x08, State: 28}, {Lo: '\t', Hi: '\r', State: 5, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 28}, {Lo: ' ', Hi: ' ', State: 5, Skip: true}, {Lo: '!', Hi: '!', State: 28}, {Lo: '#', Hi: '&', State: 28},
		{Lo: '(', Hi: '.', State: 28}, {Lo: '/', Hi: '/', State: 6}, {Lo: '0', Hi: ';', State: 28}, {Lo: '=', Hi: '=', State: 27},
		{Lo: '>', Hi: '>', State: 22}, {Lo: '?', Hi: 0x7fffffff, State: 28}, {Lo: '>', Hi: '>', State: 25}, {Lo: 'C', Hi: 'C', State: 11},
		{Lo: 'c', Hi: 'c', State: 11}, {Lo: 'E', Hi: 'E', State: 23}, {Lo: 'e', Hi: 'e', State: 23}, {Lo: 'O', Hi: 'O', State: 7},
		{Lo: 'o', Hi: 'o', State: 7}, {Lo: 'P', Hi: 'P', State: 8}, {Lo: 'p', Hi: 'p', State: 8}, {Lo: 'T', Hi: 'T', State: 13},
		{Lo: 't', Hi: 't', State: 13}, {Lo: '0', Hi: '9', State: 35}, {Lo: 'X', Hi: 'X', State: 16}, {Lo: 'x', Hi: 'x', State: 16},
		{Lo: 'Y', Hi: 'Y', State: 10}, {Lo: 'y', Hi: 'y', State: 10}, {Lo: -2147483648, Hi: -1, State: 76}, {Lo: 0x01, Hi: 0x08, State: 76},
		{Lo: '\t', Hi: '\r', State: 14}, {Lo: 0x0e, Hi: 0x1f, State: 76}, {Lo: ' ', Hi: ' ', State: 14}, {Lo: '!', Hi: '%', State: 76},
		{Lo: '\'', Hi: ';', State: 76}, {Lo: '=', Hi: '=', State: 76}, {Lo: '?', Hi: 0x7fffffff, State: 76}, {Lo: -2147483648, Hi: -1, State: 21},
		{Lo: 0x01, Hi: 0x08, State: 21}, {Lo: '\t', Hi: '\r', State: 20}, {Lo: 0x0e, Hi: 0x1f, State: 21}, {Lo: ' ', Hi: ' ', State: 20},
		{Lo: '!', Hi: '=', State: 21}, {Lo: '?', Hi: 0x7fffffff, State: 21}, {Lo: '0', Hi: '9', State: 40}, {Lo: 'A', Hi: 'F', State: 40},
		{Lo: 'a', Hi: 'f', State: 40}, {Lo: -2147483648, Hi: -1, State: 76}, {Lo: 0x01, Hi: 0x08, State: 76}, {Lo: '\t', Hi: '\r', State: 17, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 76}, {Lo: ' ', Hi: ' ', State: 17, Skip: true}, {Lo: '!', Hi: '%', State: 76}, {Lo: '&', Hi: '&', State: 3},
		{Lo: '\'', Hi: ';', State: 76}, {Lo: '<', Hi: '<', State: 24}, {Lo: '=', Hi: '=', State: 76}, {Lo: '?', Hi: 0x7fffffff, State: 76},
		{Lo: -2147483648, Hi: -1, State: 21}, {Lo: 0x01, Hi: 0x08, State: 21}, {Lo: '\t', Hi: '\r', State: 20}, {Lo: 0x0e, Hi: 0x1f, State: 21},
		{Lo: ' ', Hi: ' ', State: 20}, {Lo: '!', Hi: '=', State: 21}, {Lo: '?', Hi: 0x7fffffff, State: 21}, {Lo: -2147483648, Hi: -1, State: 21},
		{Lo: 0x01, Hi: '=', State: 21}, {Lo: '?', Hi: 0x7fffffff, State: 21}, {Lo: '!', Hi: '!', State: 19}, {Lo: '/', Hi: '/', State: 26},
		{Lo: -2147483648, Hi: -1, State: 28}, {Lo: 0x01, Hi: 0x08, State: 28}, {Lo: 0x0e, Hi: 0x1f, State: 28}, {Lo: '!', Hi: '!', State: 28},
		{Lo: '#', Hi: '&', State: 28}, {Lo: '(', Hi: '.', State: 28}, {Lo: '0', Hi: ';', State: 28}, {Lo: '?', Hi: 0x7fffffff, State: 28},
		{Lo: -2147483648, Hi: -1, State: 29}, {Lo: 0x01, Hi: 0x08, State: 29}, {Lo: 0x0e, Hi: 0x1f, State: 29}, {Lo: '!', Hi: '!', State: 29},
		{Lo: '#', Hi: '&', State: 29}, {Lo: '(', Hi: ';', State: 29}, {Lo: '?', Hi: 0x7fffffff, State: 29}, {Lo: ';', Hi: ';', State: 30},
		{Lo: '0', Hi: '9', State: 31}, {Lo: ';', Hi: ';', State: 30}, {Lo: '0', Hi: '9', State: 32}, {Lo: ';', Hi: ';', State: 30},
		{Lo: '0', Hi: '9', State: 33}, {Lo: ';', Hi: ';', State: 30}, {Lo: '0', Hi: '9', State: 34}, {Lo: ';', Hi: ';', State: 30},
		{Lo: '0', Hi: '9', State: 31}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'F', State: 31}, {Lo: 'a', Hi: 'f', State: 31},
		{Lo: '0', Hi: '9', State: 36}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'F', State: 36}, {Lo: 'a', Hi: 'f', State: 36},
		{Lo: '0', Hi: '9', State: 37}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'F', State: 37}, {Lo: 'a', Hi: 'f', State: 37},
		{Lo: '0', Hi: '9', State: 38}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'F', State: 38}, {Lo: 'a', Hi: 'f', State: 38},
		{Lo: '0', Hi: '9', State: 39}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'F', State: 39}, {Lo: 'a', Hi: 'f', State: 39},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 31}, {Lo: 'a', Hi: 'z', State: 31}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 41}, {Lo: 'a', Hi: 'z', State: 41}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 42},
		{Lo: 'a', Hi: 'z', State: 42}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 43}, {Lo: 'a', Hi: 'z', State: 43},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 44}, {Lo: 'a', Hi: 'z', State: 44}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 45}, {Lo: 'a', Hi: 'z', State: 45}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 46},
		{Lo: 'a', Hi: 'z', State: 46}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 47}, {Lo: 'a', Hi: 'z', State: 47},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 48}, {Lo: 'a', Hi: 'z', State: 48}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 49}, {Lo: 'a', Hi: 'z', State: 49}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 50},
		{Lo: 'a', Hi: 'z', State: 50}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 51}, {Lo: 'a', Hi: 'z', State: 51},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 52}, {Lo: 'a', Hi: 'z', State: 52}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 53}, {Lo: 'a', Hi: 'z', State: 53}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 54},
		{Lo: 'a', Hi: 'z', State: 54}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 55}, {Lo: 'a', Hi: 'z', State: 55},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 56}, {Lo: 'a', Hi: 'z', State: 56}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 57}, {Lo: 'a', Hi: 'z', State: 57}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 58},
		{Lo: 'a', Hi: 'z', State: 58}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 59}, {Lo: 'a', Hi: 'z', State: 59},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 60}, {Lo: 'a', Hi: 'z', State: 60}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 61}, {Lo: 'a', Hi: 'z', State: 61}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 62},
		{Lo: 'a', Hi: 'z', State: 62}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 63}, {Lo: 'a', Hi: 'z', State: 63},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 64}, {Lo: 'a', Hi: 'z', State: 64}, {Lo: ';', Hi: ';', State: 30},
		{Lo: 'A', Hi: 'Z', State: 65}, {Lo: 'a', Hi: 'z', State: 65}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 66},
		{Lo: 'a', Hi: 'z', State: 66}, {Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 67}, {Lo: 'a', Hi: 'z', State: 67},
		{Lo: ';', Hi: ';', State: 30}, {Lo: 'A', Hi: 'Z', State: 68}, {Lo: 'a', Hi: 'z', State: 68}, {Lo: -2147483648, Hi: -1, State: 72},
		{Lo: 0x01, Hi: 0x08, State: 72}, {Lo: '\t', Hi: '\r', State: 71}, {Lo: 0x0e, Hi: 0x1f, State: 72}, {Lo: ' ', Hi: ' ', State: 71},
		{Lo: '!', Hi: '&', State: 72}, {Lo: '(', Hi: 0x7fffffff, State: 72}, {Lo: -2147483648, Hi: -1, State: 72}, {Lo: 0x01, Hi: '&', State: 72},
		{Lo: '(', Hi: 0x7fffffff, State: 72}, {Lo: -2147483648, Hi: -1, State: 75}, {Lo: 0x01, Hi: 0x08, State: 75}, {Lo: '\t', Hi: '\r', State: 74},
		{Lo: 0x0e, Hi: 0x1f, State: 75}, {Lo: ' ', Hi: ' ', State: 74}, {Lo: '!', Hi: '!', State: 75}, {Lo: '#', Hi: 0x7fffffff, State: 75},
		{Lo: -2147483648, Hi: -1, State: 75}, {Lo: 0x01, Hi: '!', State: 75}, {Lo: '#', Hi: 0x7fffffff, State: 75}, {Lo: -2147483648, Hi: -1, State: 76},
		{Lo: 0x01, Hi: 0x08, State: 76}, {Lo: '\t', Hi: '\r', State: 14}, {Lo: 0x0e, Hi: 0x1f, State: 76}, {Lo: ' ', Hi: ' ', State: 14},
		{Lo: '!', Hi: '%', State: 76}, {Lo: '\'', Hi: ';', State: 76}, {Lo: '=', Hi: '=', State: 76}, {Lo: '?', Hi: 0x7fffffff, State: 76},
	},
}
