/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 23
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 8
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_COLON = 1,
  sym_block = 2,
  sym_do_block = 3,
  sym_identifier = 4,
  sym_expression = 5,
  sym_function_call = 6,
  sym_scope_resolution = 7,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_COLON] = "::",
  [sym_block] = "block",
  [sym_do_block] = "do_block",
  [sym_identifier] = "identifier",
  [sym_expression] = "expression",
  [sym_function_call] = "function_call",
  [sym_scope_resolution] = "scope_resolution",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_block] = sym_block,
  [sym_do_block] = sym_do_block,
  [sym_identifier] = sym_identifier,
  [sym_expression] = sym_expression,
  [sym_function_call] = sym_function_call,
  [sym_scope_resolution] = sym_scope_resolution,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_do_block] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_resolution] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 9,
  [17] = 10,
  [18] = 11,
  [19] = 19,
  [20] = 13,
  [21] = 21,
  [22] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == '{') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'n') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(9);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_block);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_do_block);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_block] = ACTIONS(1),
    [sym_do_block] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_expression] = STATE(15),
    [sym_function_call] = STATE(17),
    [sym_scope_resolution] = STATE(17),
    [anon_sym_COLON_COLON] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(8),
    [sym_function_call] = STATE(10),
    [sym_scope_resolution] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_COLON_COLON] = ACTIONS(7),
    [sym_block] = ACTIONS(9),
    [sym_do_block] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(12),
    [sym_function_call] = STATE(10),
    [sym_scope_resolution] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_COLON_COLON] = ACTIONS(7),
    [sym_block] = ACTIONS(15),
    [sym_do_block] = ACTIONS(7),
    [sym_identifier] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(16),
    [sym_function_call] = STATE(17),
    [sym_scope_resolution] = STATE(17),
    [anon_sym_COLON_COLON] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(9),
    [sym_function_call] = STATE(10),
    [sym_scope_resolution] = STATE(10),
    [anon_sym_COLON_COLON] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(22),
    [sym_function_call] = STATE(17),
    [sym_scope_resolution] = STATE(17),
    [anon_sym_COLON_COLON] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(14),
    [sym_function_call] = STATE(10),
    [sym_scope_resolution] = STATE(10),
    [anon_sym_COLON_COLON] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_COLON_COLON,
    ACTIONS(25), 1,
      sym_block,
    ACTIONS(27), 1,
      sym_do_block,
  [13] = 1,
    ACTIONS(29), 4,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
      sym_block,
      sym_do_block,
  [20] = 1,
    ACTIONS(7), 4,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
      sym_block,
      sym_do_block,
  [27] = 1,
    ACTIONS(21), 4,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
      sym_block,
      sym_do_block,
  [34] = 3,
    ACTIONS(23), 1,
      anon_sym_COLON_COLON,
    ACTIONS(31), 1,
      sym_block,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      sym_do_block,
  [45] = 1,
    ACTIONS(33), 4,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
      sym_block,
      sym_do_block,
  [52] = 1,
    ACTIONS(35), 4,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
      sym_block,
      sym_do_block,
  [59] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_COLON_COLON,
  [66] = 1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [71] = 1,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [76] = 1,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [81] = 1,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [86] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [91] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [96] = 1,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 13,
  [SMALL_STATE(10)] = 20,
  [SMALL_STATE(11)] = 27,
  [SMALL_STATE(12)] = 34,
  [SMALL_STATE(13)] = 45,
  [SMALL_STATE(14)] = 52,
  [SMALL_STATE(15)] = 59,
  [SMALL_STATE(16)] = 66,
  [SMALL_STATE(17)] = 71,
  [SMALL_STATE(18)] = 76,
  [SMALL_STATE(19)] = 81,
  [SMALL_STATE(20)] = 86,
  [SMALL_STATE(21)] = 91,
  [SMALL_STATE(22)] = 96,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_resolution, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_resolution, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_precedence_on_subsequence(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "precedence_on_subsequence",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
