// Code generated by transit. DO NOT EDIT.

package sql_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/sql"
)

// This example parses a text of the grammar sql, the input of the corpus case
// "alter/Alter table and add column", and prints its tree. Then it compiles
// each query of the package, and prints the number of its patterns.
func ExampleLanguage() {
	language := sql.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`
ALTER TABLE my_table
  ADD COLUMN val3 VARCHAR(100) NOT NULL;
`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(sql.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(sql.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (program (statement (alter_table (keyword_alter) (keyword_table) (object_reference name: (identifier)) (add_column (keyword_add) (keyword_column) (column_definition name: (identifier) type: (varchar (keyword_varchar) size: (literal)) (keyword_not) (keyword_null))))))
	// patterns in queries/highlights.scm: 24
	// patterns in queries/indents.scm: 7
}
