// Code generated by transit. DO NOT EDIT.

package cql_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/cql"
)

// This example parses a text of the grammar cql, the input of the corpus case
// "alterKeyspace/ALTER KEYSPACE keyspace WITH REPLICATION = { 'foo' : 'bar',
// 'baz' : 5};", and prints its tree. Then it compiles each query of the
// package, and prints the number of its patterns.
func ExampleLanguage() {
	language := cql.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`ALTER KEYSPACE keyspace WITH REPLICATION = { 'foo' : 'bar', 'baz' : 5};`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(cql.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(cql.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (source_file (alter_keyspace (keyspace_name) (replication_list (replication_list_item) (replication_list_item))))
	// patterns in queries/highlights.scm: 61
}
