package golang

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/corpus"
)

// This file writes example_test.go of a grammar package, the example that
// pkg.go.dev shows for the function Language (D53, D115). It ports no
// upstream file.

// exampleCase is the corpus case whose input the example parses.
type exampleCase struct {
	// name is the path of the case, such as "main/Simple".
	name string
	// input is the text of the case, and tree is its tree as Node.String
	// prints it.
	input []byte
	tree  string
}

// Example returns example_test.go of the grammar package pkg in dir, whose
// language is language. Its function ExampleLanguage parses the input of
// the first corpus case of the package that passes, and prints the tree of
// the input. Then it compiles each query file of the package, and prints the
// number of its patterns. The block Output of the example holds what it
// prints, so go test makes sure of it.
//
// The generator cannot parse, because it has no external scanner. So the
// tree of the case is its expected tree in the corpus, which the corpus test
// compares with the tree that the package parses. The tree that Node.String
// prints holds the names of the fields, and an expected tree can leave them
// out. So the example takes the first case that passes whose expected tree
// holds the names of its fields, or holds no node of a type that has a
// field in nodeTypes, the types of node-types.json. A case that passes is
// not in testdata/failing.txt, expects no error, has no attribute :cst, and
// runs in the package (D83). The example also leaves out a case whose input
// is blank, because its tree shows little. An expected tree that names no field and holds
// a node ERROR does not count, because nodeTypes gives no field of ERROR.
// When no case counts, as in a package with no corpus, the example only
// compiles the queries. When the package has no query either, it prints the
// name of the language.
//
// The example compiles each query with language, so the language needs no
// lexer and no external scanner here. The generator gives the tables of the
// grammar, and the generator test gives the language of the package.
func Example(dir, pkg string, language *transit.Language, nodeTypes []transit.NodeType, opts Options) (string, error) {
	importPath, err := packageImportPath(dir)
	if err != nil {
		return "", err
	}
	var c *exampleCase
	if opts.Corpus {
		if c, err = findExampleCase(dir, language, nodeTypes); err != nil {
			return "", err
		}
	}
	var queries []string
	if opts.Queries {
		if queries, err = queryPatterns(dir, language); err != nil {
			return "", err
		}
	}
	var b writer
	b.WriteString("// Code generated by transit. DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "_test\n\n")
	var imports []string
	if c != nil {
		imports = append(imports, "context")
	}
	imports = append(imports, "fmt")
	if len(queries) != 0 {
		imports = append(imports, "io/fs")
	}
	if c != nil || len(queries) != 0 {
		imports = append(imports, "log")
	}
	if len(queries) != 0 {
		imports = append(imports, "path")
	}
	b.WriteString("import (\n")
	for _, p := range imports {
		b.WriteString("\t" + strconv.Quote(p) + "\n")
	}
	b.WriteString("\n")
	if c != nil || len(queries) != 0 {
		b.WriteString("\t\"github.com/xo/transit\"\n")
	}
	if path.Base(importPath) == pkg {
		b.WriteString("\t" + strconv.Quote(importPath) + "\n")
	} else {
		b.WriteString("\t" + pkg + " " + strconv.Quote(importPath) + "\n")
	}
	b.WriteString(")\n\n")

	var output []string
	var doc string
	grammar := language.Name()
	if grammar == "" {
		grammar = pkg
	}
	switch {
	case c != nil && len(queries) != 0:
		doc = fmt.Sprintf("This example parses a text of the grammar %s, the input of the corpus case %s, and prints its tree. Then it compiles each query of the package, and prints the number of its patterns.", grammar, strconv.Quote(c.name))
	case c != nil:
		doc = fmt.Sprintf("This example parses a text of the grammar %s, the input of the corpus case %s, and prints its tree.", grammar, strconv.Quote(c.name))
	case len(queries) != 0:
		doc = fmt.Sprintf("This example compiles each query of the package %s, and prints the number of its patterns.", pkg)
	default:
		doc = fmt.Sprintf("This example prints the name of the language of the package %s.", pkg)
	}
	b.comment(doc)
	b.WriteString("func ExampleLanguage() {\n")
	b.WriteString("\tlanguage := " + pkg + ".Language()\n")
	if c != nil {
		b.WriteString("\tparser := transit.NewParser()\n")
		b.WriteString("\tif err := parser.SetLanguage(language); err != nil {\n\t\tlog.Fatal(err)\n\t}\n")
		b.WriteString("\tsrc := []byte(" + goString(c.input) + ")\n")
		b.WriteString("\ttree, err := parser.Parse(context.Background(), src, nil)\n")
		b.WriteString("\tif err != nil {\n\t\tlog.Fatal(err)\n\t}\n")
		b.WriteString("\tfmt.Println(tree.RootNode())\n")
		output = append(output, c.tree)
	}
	if len(queries) != 0 {
		b.printf(`	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(%[1]s.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %%s: %%w", name, err)
		}
		fmt.Printf("patterns in %%s: %%d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(%[1]s.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
`, pkg)
		output = append(output, queries...)
	}
	if c == nil && len(queries) == 0 {
		b.WriteString("\tfmt.Println(language.Name())\n")
		output = append(output, language.Name())
	}
	b.WriteString("\t// Output:\n")
	for _, line := range output {
		b.WriteString("\t// " + line + "\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// findExampleCase returns the case of the corpus of the package in dir that
// Example parses, or nil when no case is such a case.
func findExampleCase(dir string, language *transit.Language, nodeTypes []transit.NodeType) (*exampleCase, error) {
	root, err := corpus.Parse(filepath.Join(dir, "testdata", "corpus"))
	if err != nil {
		return nil, fmt.Errorf("reading the corpus of %s: %w", dir, err)
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return nil, fmt.Errorf("finding the folder %s: %w", dir, err)
	}
	m, err := corpus.ReadModuleIn(abs, language.Name())
	if err != nil {
		return nil, err
	}
	failing, err := corpus.ReadFailing(dir)
	if err != nil {
		return nil, err
	}
	withFields := map[string]bool{"ERROR": true}
	for _, nt := range nodeTypes {
		if nt.Named && len(nt.Fields) != 0 {
			withFields[nt.Kind] = true
		}
	}
	for name, e := range corpus.Cases(root) {
		a := e.Attributes
		switch {
		case slices.Contains(failing, name),
			a.Expectation != corpus.ExpectPass,
			a.CST,
			len(bytes.TrimSpace(e.Input)) == 0,
			!a.Platform,
			m.Owner(a) != m.Own,
			!e.HasFields && holdsKind(e.Output, withFields):
			continue
		}
		holds := true
		for _, l := range a.Languages {
			holds = holds && m.Holds(language.Name(), l)
		}
		if holds {
			return &exampleCase{name: name, input: e.Input, tree: e.Output}, nil
		}
	}
	return nil, nil
}

// holdsKind reports whether the tree sexp, as Node.String prints it, holds
// a node of one of the kinds.
func holdsKind(sexp string, kinds map[string]bool) bool {
	for _, part := range strings.Split(sexp, "(")[1:] {
		kind, _, _ := strings.Cut(part, " ")
		if kinds[strings.TrimRight(kind, ")")] {
			return true
		}
	}
	return false
}

// queryPatterns compiles each query file of the package in dir, in the
// order in which fs.WalkDir finds it in the embedded files Queries of the
// package, and returns the line that the example prints for each. go:embed
// leaves out a file or a folder whose name starts with "." or "_", so this
// does too.
func queryPatterns(dir string, language *transit.Language) ([]string, error) {
	fsys := os.DirFS(dir)
	var lines []string
	err := fs.WalkDir(fsys, "queries", func(name string, d fs.DirEntry, err error) error {
		switch {
		case err != nil:
			return err
		case name != "queries" && (strings.HasPrefix(d.Name(), ".") || strings.HasPrefix(d.Name(), "_")):
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		case d.IsDir() || path.Ext(name) != ".scm":
			return nil
		}
		text, err := fs.ReadFile(fsys, name)
		if err != nil {
			return fmt.Errorf("reading the query file %s: %w", name, err)
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling the query file %s: %w", name, err)
		}
		lines = append(lines, fmt.Sprintf("patterns in %s: %d", name, query.PatternCount()))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("compiling the queries of %s: %w", dir, err)
	}
	return lines, nil
}

// packageImportPath returns the import path of the package in dir: the
// module path of the nearest go.mod, in dir or in a folder above it, and
// the path of dir in the folder of that go.mod. When no folder holds a
// go.mod, it is the name of the folder of the package.
func packageImportPath(dir string) (string, error) {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("finding the folder %s: %w", dir, err)
	}
	for moduleDir := abs; ; {
		if isFile(filepath.Join(moduleDir, "go.mod")) {
			modulePath, err := readModulePath(moduleDir)
			if err != nil {
				return "", err
			}
			rel, err := filepath.Rel(moduleDir, abs)
			if err != nil {
				return "", fmt.Errorf("finding the folder of the package: %w", err)
			}
			return path.Join(modulePath, filepath.ToSlash(rel)), nil
		}
		parent := filepath.Dir(moduleDir)
		if parent == moduleDir {
			// no go.mod names the module of the package
			return filepath.Base(abs), nil
		}
		moduleDir = parent
	}
}

// goString returns a Go literal of the text b: a raw string when the text
// is valid UTF-8 and holds no "`" and only printable characters, tabs and
// newlines, and else an interpreted string.
func goString(b []byte) string {
	raw := utf8.Valid(b) && !strings.ContainsFunc(string(b), func(r rune) bool {
		return r == '`' || r != '\n' && r != '\t' && !unicode.IsPrint(r)
	})
	if raw {
		return "`" + string(b) + "`"
	}
	return strconv.Quote(string(b))
}
