// Code generated by transit. DO NOT EDIT.

package sqlserver_test

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/sqlserver"
)

// This example parses a text of the grammar TSQL, the input of the corpus case
// "assignment_operator/assignment_operator PlusEqual", and prints its tree.
// Then it compiles each query of the package, and prints the number of its
// patterns.
func ExampleLanguage() {
	language := sqlserver.Language()
	parser := transit.NewParser()
	if err := parser.SetLanguage(language); err != nil {
		log.Fatal(err)
	}
	src := []byte(`select @foo+=baz`)
	tree, err := parser.Parse(context.Background(), src, nil)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(tree.RootNode())
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(sqlserver.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(sqlserver.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// (tsql_file (batch (sql_clauses (dml_clause (select_statement_standalone (select_statement (query_expression (query_specification (select) (select_list (select_list_elem (LOCAL_ID_) (assignment_operator) (expression (full_column_name (id_)))))))))))))
	// patterns in queries/highlights.scm: 35
}
