package main

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// rustFile is one table file of regex-syntax, after the parse.
type rustFile struct {
	command   string // the ucd-generate command that made the file
	unicode   string // the Unicode version of the tables
	generator string // the version of ucd-generate
	items     []*item
}

// item is one `pub const NAME: TYPE = VALUE;` of a table file.
type item struct {
	name string
	typ  *rustType
	val  *value
}

// rustTypeKind is the kind of a Rust type.
type rustTypeKind int

// The kinds of Rust type that the table files use.
const (
	typeRef   rustTypeKind = iota // &'static T
	typeSlice                     // [T]
	typeTuple                     // (T, U)
	typeChar                      // char
	typeStr                       // str
)

// rustType is a Rust type of a table file.
type rustType struct {
	kind  rustTypeKind
	elems []*rustType // the type that a reference or a slice holds, or the types of a tuple
}

// String returns the type in a short form, without the lifetimes and the
// spaces, such as &[(char,char)].
func (t *rustType) String() string {
	switch t.kind {
	case typeRef:
		return "&" + t.elems[0].String()
	case typeSlice:
		return "[" + t.elems[0].String() + "]"
	case typeTuple:
		s := make([]string, len(t.elems))
		for i, e := range t.elems {
			s[i] = e.String()
		}
		return "(" + strings.Join(s, ",") + ")"
	case typeChar:
		return "char"
	case typeStr:
		return "str"
	}
	return fmt.Sprintf("type kind %d", t.kind)
}

// valueKind is the kind of a Rust value.
type valueKind int

// The kinds of Rust value that the table files use.
const (
	valArray  valueKind = iota // &[a, b]
	valTuple                   // (a, b)
	valChar                    // 'a'
	valString                  // "a"
	valName                    // the name of another item of the file
)

// value is a Rust value of a table file.
type value struct {
	kind  valueKind
	elems []*value // the elements of an array or a tuple
	r     rune     // the value of a char
	s     string   // the value of a string, or a name
	line  int
	col   int
}

// The lines of the header that ucd-generate writes.
var (
	headerFirst     = "// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:"
	headerCommand   = regexp.MustCompile(`^//   (ucd-generate [ -~]+)$`)
	headerUnicode   = regexp.MustCompile(`^// Unicode version: ([0-9]+\.[0-9]+\.[0-9]+)\.$`)
	headerGenerator = regexp.MustCompile(`^// ucd-generate ([0-9]+\.[0-9]+\.[0-9]+) is available on crates\.io\.$`)
)

// parser reads the tokens of one Rust file.
type parser struct {
	toks []token
	pos  int
}

// parseFile parses the text of a table file.
func parseFile(src string) (*rustFile, error) {
	toks, err := lex(src)
	if err != nil {
		return nil, err
	}
	p := &parser{toks: toks}
	f, err := p.header()
	if err != nil {
		return nil, err
	}
	for p.peek().kind != tokEOF {
		it, err := p.item()
		if err != nil {
			t := p.toks[max(p.pos-1, 0)]
			return nil, fmt.Errorf("%d:%d: %w", t.line, t.col, err)
		}
		f.items = append(f.items, it)
	}
	if len(f.items) == 0 {
		return nil, errors.New("reading a table file with no items")
	}
	return f, nil
}

// peek returns the token at the position.
func (p *parser) peek() token {
	return p.toks[p.pos]
}

// next returns the token at the position and moves past it. It stays on the
// last token, which has the kind tokEOF.
func (p *parser) next() token {
	t := p.toks[p.pos]
	if t.kind != tokEOF {
		p.pos++
	}
	return t
}

// isPunct reports whether the token at the position is the punctuation text.
func (p *parser) isPunct(text string) bool {
	t := p.peek()
	return t.kind == tokPunct && t.text == text
}

// expect moves past a token with the kind and the text, and fails on any other
// token.
func (p *parser) expect(kind tokenKind, text string) error {
	t := p.next()
	if t.kind != kind || t.text != text {
		return fmt.Errorf("expecting %s %q, got: %s", kind, text, t)
	}
	return nil
}

// header reads the comment that ucd-generate writes at the top of each file.
func (p *parser) header() (*rustFile, error) {
	var lines []string
	for p.peek().kind == tokComment {
		lines = append(lines, "//"+p.next().text)
	}
	if len(lines) != 7 || lines[0] != headerFirst || lines[1] != "//" || lines[3] != "//" || lines[5] != "//" {
		return nil, fmt.Errorf("reading a header that is not the header of ucd-generate: %q", lines)
	}
	f := &rustFile{}
	for _, h := range []struct {
		re   *regexp.Regexp
		line string
		dst  *string
	}{
		{headerCommand, lines[2], &f.command},
		{headerUnicode, lines[4], &f.unicode},
		{headerGenerator, lines[6], &f.generator},
	} {
		m := h.re.FindStringSubmatch(h.line)
		if m == nil {
			return nil, fmt.Errorf("reading the header line %q, which does not match %s", h.line, h.re)
		}
		*h.dst = m[1]
	}
	return f, nil
}

// item reads `pub const NAME: TYPE = VALUE;`.
func (p *parser) item() (*item, error) {
	if t := p.peek(); t.kind == tokComment {
		return nil, errors.New("reading a comment after the header, which the converter does not keep")
	}
	if err := p.expect(tokIdent, "pub"); err != nil {
		return nil, err
	}
	if err := p.expect(tokIdent, "const"); err != nil {
		return nil, err
	}
	name := p.next()
	if name.kind != tokIdent {
		return nil, fmt.Errorf("expecting the name of a const, got: %s", name)
	}
	if err := p.expect(tokPunct, ":"); err != nil {
		return nil, err
	}
	typ, err := p.rustType()
	if err != nil {
		return nil, err
	}
	if err := p.expect(tokPunct, "="); err != nil {
		return nil, err
	}
	val, err := p.value()
	if err != nil {
		return nil, err
	}
	if err := p.expect(tokPunct, ";"); err != nil {
		return nil, err
	}
	return &item{name: name.text, typ: typ, val: val}, nil
}

// rustType reads a type.
func (p *parser) rustType() (*rustType, error) {
	t := p.next()
	switch {
	case t.kind == tokPunct && t.text == "&":
		if l := p.peek(); l.kind == tokLifetime {
			if l.text != "static" {
				return nil, fmt.Errorf("reading %s, which is not 'static", l)
			}
			p.next()
		}
		elem, err := p.rustType()
		if err != nil {
			return nil, err
		}
		return &rustType{kind: typeRef, elems: []*rustType{elem}}, nil
	case t.kind == tokPunct && t.text == "[":
		elem, err := p.rustType()
		if err != nil {
			return nil, err
		}
		if err := p.expect(tokPunct, "]"); err != nil {
			return nil, err
		}
		return &rustType{kind: typeSlice, elems: []*rustType{elem}}, nil
	case t.kind == tokPunct && t.text == "(":
		var elems []*rustType
		for !p.isPunct(")") {
			e, err := p.rustType()
			if err != nil {
				return nil, err
			}
			elems = append(elems, e)
			if !p.isPunct(",") {
				break
			}
			p.next()
		}
		if err := p.expect(tokPunct, ")"); err != nil {
			return nil, err
		}
		if len(elems) < 2 {
			return nil, fmt.Errorf("reading a tuple type with %d elements, which the converter does not read", len(elems))
		}
		return &rustType{kind: typeTuple, elems: elems}, nil
	case t.kind == tokIdent && t.text == "char":
		return &rustType{kind: typeChar}, nil
	case t.kind == tokIdent && t.text == "str":
		return &rustType{kind: typeStr}, nil
	}
	return nil, fmt.Errorf("reading %s as a type, which the converter does not read", t)
}

// value reads a value.
func (p *parser) value() (*value, error) {
	t := p.next()
	v := &value{line: t.line, col: t.col}
	switch {
	case t.kind == tokPunct && t.text == "&":
		if err := p.expect(tokPunct, "["); err != nil {
			return nil, err
		}
		v.kind = valArray
		elems, err := p.values("]")
		if err != nil {
			return nil, err
		}
		v.elems = elems
		return v, nil
	case t.kind == tokPunct && t.text == "(":
		v.kind = valTuple
		elems, err := p.values(")")
		if err != nil {
			return nil, err
		}
		if len(elems) < 2 {
			return nil, fmt.Errorf("reading a tuple with %d elements, which the converter does not read", len(elems))
		}
		v.elems = elems
		return v, nil
	case t.kind == tokChar:
		v.kind = valChar
		v.r = t.r
		return v, nil
	case t.kind == tokString:
		v.kind = valString
		v.s = t.text
		return v, nil
	case t.kind == tokIdent:
		v.kind = valName
		v.s = t.text
		return v, nil
	}
	return nil, fmt.Errorf("reading %s as a value, which the converter does not read", t)
}

// values reads the values of an array or a tuple, separated by commas, up to
// the closing punctuation. A comma can follow the last value.
func (p *parser) values(end string) ([]*value, error) {
	var elems []*value
	for !p.isPunct(end) {
		e, err := p.value()
		if err != nil {
			return nil, err
		}
		elems = append(elems, e)
		if !p.isPunct(",") {
			break
		}
		p.next()
	}
	if err := p.expect(tokPunct, end); err != nil {
		return nil, err
	}
	return elems, nil
}

// parseModules returns the names of the modules that mod.rs declares, in the
// order of the file. It skips each attribute, such as #[cfg(...)].
func parseModules(src string) ([]string, error) {
	toks, err := lex(src)
	if err != nil {
		return nil, err
	}
	p := &parser{toks: toks}
	var mods []string
	for p.peek().kind != tokEOF {
		t := p.peek()
		switch {
		case t.kind == tokComment:
			p.next()
		case t.kind == tokPunct && t.text == "#":
			if err := p.skipAttribute(); err != nil {
				return nil, fmt.Errorf("%d:%d: %w", t.line, t.col, err)
			}
		default:
			name, err := p.module()
			if err != nil {
				return nil, fmt.Errorf("%d:%d: %w", t.line, t.col, err)
			}
			mods = append(mods, name)
		}
	}
	if len(mods) == 0 {
		return nil, errors.New("reading a mod.rs that declares no modules")
	}
	return mods, nil
}

// skipAttribute moves past #[...], with the brackets and the parentheses in
// it.
func (p *parser) skipAttribute() error {
	if err := p.expect(tokPunct, "#"); err != nil {
		return err
	}
	if err := p.expect(tokPunct, "["); err != nil {
		return err
	}
	var open []string
	for {
		t := p.next()
		switch {
		case t.kind == tokEOF:
			return errors.New("reading an attribute that does not end")
		case t.kind == tokPunct && (t.text == "[" || t.text == "("):
			open = append(open, t.text)
		case t.kind == tokPunct && (t.text == "]" || t.text == ")"):
			if len(open) == 0 {
				if t.text != "]" {
					return fmt.Errorf("reading an attribute that closes with %q", t.text)
				}
				return nil
			}
			want := map[string]string{"[": "]", "(": ")"}[open[len(open)-1]]
			if t.text != want {
				return fmt.Errorf("reading %q in an attribute, where %q closes it", t.text, want)
			}
			open = open[:len(open)-1]
		}
	}
}

// module reads `pub mod NAME;`.
func (p *parser) module() (string, error) {
	if err := p.expect(tokIdent, "pub"); err != nil {
		return "", err
	}
	if err := p.expect(tokIdent, "mod"); err != nil {
		return "", err
	}
	name := p.next()
	if name.kind != tokIdent {
		return "", fmt.Errorf("expecting the name of a module, got: %s", name)
	}
	if err := p.expect(tokPunct, ";"); err != nil {
		return "", err
	}
	return name.text, nil
}
