// Code generated by transit. DO NOT EDIT.

package javascript

import (
	"testing"

	"github.com/xo/transit/internal/grammartest"
)

// TestCorpus parses each case of testdata/corpus, and compares its tree with
// the expected tree, as tree-sitter test does.
func TestCorpus(t *testing.T) {
	t.Parallel()
	grammartest.Corpus(t, Language(), "testdata/corpus")
}

// TestQueries makes sure that each file of queries compiles.
func TestQueries(t *testing.T) {
	t.Parallel()
	grammartest.Queries(t, Language(), Queries)
}

// TestHighlight highlights each file of testdata/highlight as the
// highlighter of upstream does, and checks the assertions in its comments.
// The part of the test that looks for each capture name in the package
// styles waits for phase 5, because that package does not exist yet.
func TestHighlight(t *testing.T) {
	t.Parallel()
	grammartest.Highlight(t, Language(), Queries, "testdata/highlight")
}

// TestNodeTypes makes sure that each node type is a symbol of the language.
func TestNodeTypes(t *testing.T) {
	t.Parallel()
	grammartest.NodeTypes(t, Language(), NodeTypes())
}

// TestKeywords makes sure that each keyword is a symbol of the language.
func TestKeywords(t *testing.T) {
	t.Parallel()
	grammartest.Keywords(t, Language(), Keywords())
}

// TestGenerator generates the package again, and compares the files with
// the files of the package and the hashes of grammars/grammars.json.
func TestGenerator(t *testing.T) {
	t.Parallel()
	grammartest.Generator(t, Language())
}
