// Code generated by transit. DO NOT EDIT.

// Package jsdoc is the grammar jsdoc for the Go runtime of transit. Language
// returns its language, and the constants name its symbols and its fields.
package jsdoc

import (
	"embed"
	"encoding/json"
	"sync"

	"github.com/xo/transit"
	"github.com/xo/transit/internal/abi"
)

// Language returns the language of the grammar jsdoc. Its external scanner is
// the scanner that newScanner returns.
func Language() *transit.Language {
	return language()
}

// language builds the language once. The tables are static data, so this
// copies no table.
var language = sync.OnceValue(func() *transit.Language {
	return transit.NewLanguage(&abi.Language{
		ABIVersion:             15,
		SymbolCount:            31,
		AliasCount:             0,
		TokenCount:             19,
		ExternalTokenCount:     1,
		StateCount:             51,
		LargeStateCount:        2,
		ProductionIDCount:      1,
		FieldCount:             0,
		MaxAliasSequenceLength: 6,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		SymbolNames:            symbolNames,
		SymbolMetadata:         symbolMetadata,
		PublicSymbolMap:        publicSymbolMap,
		AliasMap:               aliasMap,
		AliasSequences:         aliasSequences,
		LexModes:               lexModes,
		LexFn:                  lex,
		KeywordCaptureToken:    0,
		ExternalScanner: abi.ExternalScanner{
			States:    externalScannerStates,
			SymbolMap: externalScannerSymbolMap,
			Create:    func() abi.Scanner { return newScanner() },
		},
		PrimaryStateIDs:        primaryStateIDs,
		Name:                   "jsdoc",
		MaxReservedWordSetSize: 0,
		SupertypeCount:         0,
		Metadata:               abi.LanguageMetadata{MajorVersion: 0, MinorVersion: 23, PatchVersion: 2},
	})
})

// Queries holds queries/ of the grammar jsdoc: its own queries, and in
// queries/<grammar>/ the queries of another grammar that its tree-sitter.json
// lists (D84).
//
//go:embed queries
var Queries embed.FS

// nodeTypes is node-types.json of the grammar.
//
//go:embed node-types.json
var nodeTypes []byte

// NodeTypes returns the node types of node-types.json of the grammar jsdoc: the
// fields and the children of each node, and the subtypes of each supertype.
// Each call returns a new slice.
func NodeTypes() []transit.NodeType {
	var types []transit.NodeType
	if err := json.Unmarshal(nodeTypes, &types); err != nil {
		// the generator writes node-types.json, so it is valid
		panic("jsdoc: reading node-types.json: " + err.Error())
	}
	return types
}

// Keywords returns the keywords of the grammar jsdoc: the tokens that the word
// token captures, and the reserved words. Each call returns a new slice.
func Keywords() []string {
	return nil
}

// The symbols of the grammar jsdoc, as Node.KindID and Node.GrammarID
// return them. The comment of each one is its name.
const (
	BuiltinSymEnd             transit.Symbol = 0  // "end"
	AnonSymLBRACE             transit.Symbol = 1  // "{"
	AnonSymRBRACE             transit.Symbol = 2  // "}"
	SymInlineTagFalsePositive transit.Symbol = 3  // "_inline_tag_false_positive"
	SymTagNameWithArgument    transit.Symbol = 4  // "tag_name"
	SymTagNameWithType        transit.Symbol = 5  // "tag_name"
	SymTagName                transit.Symbol = 6  // "tag_name"
	AnonSymCOLON              transit.Symbol = 7  // ":"
	AnonSymSLASH              transit.Symbol = 8  // "/"
	AnonSymDOT                transit.Symbol = 9  // "."
	AnonSymPOUND              transit.Symbol = 10 // "#"
	AnonSymTILDE              transit.Symbol = 11 // "~"
	AnonSymLBRACK             transit.Symbol = 12 // "["
	AnonSymRBRACK             transit.Symbol = 13 // "]"
	SymIdentifier             transit.Symbol = 14 // "identifier"
	SymText                   transit.Symbol = 15 // "_text"
	SymBegin                  transit.Symbol = 16 // "_begin"
	AnonSymSLASH2             transit.Symbol = 17 // "/"
	SymType                   transit.Symbol = 18 // "type"
	SymDocument               transit.Symbol = 19 // "document"
	SymDescription            transit.Symbol = 20 // "description"
	SymTag                    transit.Symbol = 21 // "tag"
	SymInlineTag              transit.Symbol = 22 // "inline_tag"
	SymExpression             transit.Symbol = 23 // "_expression"
	SymQualifiedExpression    transit.Symbol = 24 // "qualified_expression"
	SymPathExpression         transit.Symbol = 25 // "path_expression"
	SymMemberExpression       transit.Symbol = 26 // "member_expression"
	SymOptionalIdentifier     transit.Symbol = 27 // "optional_identifier"
	SymEnd                    transit.Symbol = 28 // "_end"
	AuxSymDocumentRepeat1     transit.Symbol = 29 // "document_repeat1"
	AuxSymDescriptionRepeat1  transit.Symbol = 30 // "description_repeat1"
)

// The short names of the types of the tables.
type (
	action = abi.ParseAction
	header = abi.EntryHeader
	shift  = abi.ShiftAction
	reduce = abi.ReduceAction
)

// The kinds of a parse action.
const (
	typeShift   = abi.ParseActionTypeShift
	typeReduce  = abi.ParseActionTypeReduce
	typeAccept  = abi.ParseActionTypeAccept
	typeRecover = abi.ParseActionTypeRecover
)

// symbolNames is ts_symbol_names.
var symbolNames = []string{
	BuiltinSymEnd:             "end",
	AnonSymLBRACE:             "{",
	AnonSymRBRACE:             "}",
	SymInlineTagFalsePositive: "_inline_tag_false_positive",
	SymTagNameWithArgument:    "tag_name",
	SymTagNameWithType:        "tag_name",
	SymTagName:                "tag_name",
	AnonSymCOLON:              ":",
	AnonSymSLASH:              "/",
	AnonSymDOT:                ".",
	AnonSymPOUND:              "#",
	AnonSymTILDE:              "~",
	AnonSymLBRACK:             "[",
	AnonSymRBRACK:             "]",
	SymIdentifier:             "identifier",
	SymText:                   "_text",
	SymBegin:                  "_begin",
	AnonSymSLASH2:             "/",
	SymType:                   "type",
	SymDocument:               "document",
	SymDescription:            "description",
	SymTag:                    "tag",
	SymInlineTag:              "inline_tag",
	SymExpression:             "_expression",
	SymQualifiedExpression:    "qualified_expression",
	SymPathExpression:         "path_expression",
	SymMemberExpression:       "member_expression",
	SymOptionalIdentifier:     "optional_identifier",
	SymEnd:                    "_end",
	AuxSymDocumentRepeat1:     "document_repeat1",
	AuxSymDescriptionRepeat1:  "description_repeat1",
}

// symbolMetadata is ts_symbol_metadata.
var symbolMetadata = []abi.SymbolMetadata{
	BuiltinSymEnd:             {Named: true},
	AnonSymLBRACE:             {Visible: true},
	AnonSymRBRACE:             {Visible: true},
	SymInlineTagFalsePositive: {Named: true},
	SymTagNameWithArgument:    {Visible: true, Named: true},
	SymTagNameWithType:        {Visible: true, Named: true},
	SymTagName:                {Visible: true, Named: true},
	AnonSymCOLON:              {Visible: true},
	AnonSymSLASH:              {Visible: true},
	AnonSymDOT:                {Visible: true},
	AnonSymPOUND:              {Visible: true},
	AnonSymTILDE:              {Visible: true},
	AnonSymLBRACK:             {Visible: true},
	AnonSymRBRACK:             {Visible: true},
	SymIdentifier:             {Visible: true, Named: true},
	SymText:                   {Named: true},
	SymBegin:                  {Named: true},
	AnonSymSLASH2:             {Visible: true},
	SymType:                   {Visible: true, Named: true},
	SymDocument:               {Visible: true, Named: true},
	SymDescription:            {Visible: true, Named: true},
	SymTag:                    {Visible: true, Named: true},
	SymInlineTag:              {Visible: true, Named: true},
	SymExpression:             {Named: true},
	SymQualifiedExpression:    {Visible: true, Named: true},
	SymPathExpression:         {Visible: true, Named: true},
	SymMemberExpression:       {Visible: true, Named: true},
	SymOptionalIdentifier:     {Visible: true, Named: true},
	SymEnd:                    {Named: true},
	AuxSymDocumentRepeat1:     {},
	AuxSymDescriptionRepeat1:  {},
}

// parseTable is ts_parse_table, one row of SymbolCount entries for each large state.
var parseTable = []uint16{
	// state 0
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	// state 1
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
}

// smallParseTable is ts_small_parse_table. The entries of a small state
// are its number of groups, and for each group its value, its number of
// symbols and the symbols.
var smallParseTable = []uint16{
	// state 2
	8, 5, 1, 1, 9, 1, 12, 11, 1, 14, 13, 1, 15, 15, 1, 17,
	29, 1, 20, 7, 3, 4, 5, 6, 6, 5, 23, 24, 25, 26, 27,
	// state 3
	7, 9, 1, 12, 11, 1, 14, 13, 1, 15, 19, 1, 17, 32, 1, 20,
	17, 3, 4, 5, 6, 11, 5, 23, 24, 25, 26, 27,
	// state 4
	4, 23, 1, 7, 25, 1, 8, 27, 3, 9, 10, 11, 21, 5, 4, 5,
	6, 15, 17,
	// state 5
	6, 29, 1, 1, 31, 1, 3, 35, 1, 15, 37, 1, 17, 9, 2, 22,
	30, 33, 3, 4, 5, 6,
	// state 6
	5, 13, 1, 15, 43, 1, 17, 28, 1, 20, 39, 3, 4, 5, 6, 41,
	3, 9, 10, 11,
	// state 7
	8, 13, 1, 15, 45, 1, 4, 47, 1, 5, 49, 1, 6, 51, 1, 17,
	20, 1, 20, 41, 1, 28, 21, 2, 21, 29,
	// state 8
	6, 53, 1, 1, 56, 1, 3, 61, 1, 15, 64, 1, 17, 8, 2, 22,
	30, 59, 3, 4, 5, 6,
	// state 9
	6, 29, 1, 1, 66, 1, 3, 70, 1, 15, 72, 1, 17, 8, 2, 22,
	30, 68, 3, 4, 5, 6,
	// state 10
	3, 23, 1, 7, 74, 4, 4, 5, 6, 15, 76, 4, 9, 10, 11, 17,
	// state 11
	5, 13, 1, 15, 80, 1, 17, 30, 1, 20, 41, 3, 9, 10, 11, 78,
	3, 4, 5, 6,
	// state 12
	2, 82, 4, 4, 5, 6, 15, 84, 4, 9, 10, 11, 17,
	// state 13
	2, 86, 4, 4, 5, 6, 15, 88, 4, 9, 10, 11, 17,
	// state 14
	2, 90, 4, 4, 5, 6, 15, 92, 4, 9, 10, 11, 17,
	// state 15
	2, 74, 4, 4, 5, 6, 15, 76, 4, 9, 10, 11, 17,
	// state 16
	2, 96, 2, 3, 17, 94, 5, 1, 4, 5, 6, 15,
	// state 17
	5, 13, 1, 15, 15, 1, 17, 98, 1, 1, 29, 1, 20, 7, 3, 4,
	5, 6,
	// state 18
	6, 45, 1, 4, 47, 1, 5, 49, 1, 6, 100, 1, 17, 40, 1, 28,
	23, 2, 21, 29,
	// state 19
	3, 9, 1, 12, 11, 1, 14, 13, 5, 23, 24, 25, 26, 27,
	// state 20
	6, 45, 1, 4, 47, 1, 5, 49, 1, 6, 102, 1, 17, 38, 1, 28,
	18, 2, 21, 29,
	// state 21
	6, 45, 1, 4, 47, 1, 5, 49, 1, 6, 102, 1, 17, 38, 1, 28,
	23, 2, 21, 29,
	// state 22
	4, 72, 1, 2, 104, 1, 1, 106, 2, 3, 15, 26, 2, 22, 30,
	// state 23
	5, 108, 1, 4, 111, 1, 5, 114, 1, 6, 117, 1, 17, 23, 2, 21,
	29,
	// state 24
	4, 13, 1, 15, 15, 1, 17, 29, 1, 20, 7, 3, 4, 5, 6,
	// state 25
	4, 13, 1, 15, 19, 1, 17, 32, 1, 20, 17, 3, 4, 5, 6,
	// state 26
	4, 64, 1, 2, 119, 1, 1, 122, 2, 3, 15, 26, 2, 22, 30,
	// state 27
	4, 37, 1, 2, 104, 1, 1, 125, 2, 3, 15, 22, 2, 22, 30,
	// state 28
	2, 129, 1, 17, 127, 3, 4, 5, 6,
	// state 29
	2, 43, 1, 17, 39, 3, 4, 5, 6,
	// state 30
	2, 133, 1, 17, 131, 3, 4, 5, 6,
	// state 31
	2, 94, 1, 1, 96, 3, 2, 3, 15,
	// state 32
	2, 80, 1, 17, 78, 3, 4, 5, 6,
	// state 33
	2, 135, 1, 15, 47, 1, 20,
	// state 34
	2, 137, 1, 14, 15, 1, 24,
	// state 35
	2, 135, 1, 15, 49, 1, 20,
	// state 36
	1, 139, 1, 14,
	// state 37
	1, 141, 1, 2,
	// state 38
	1, 143, 1, 0,
	// state 39
	1, 145, 1, 0,
	// state 40
	1, 147, 1, 0,
	// state 41
	1, 149, 1, 0,
	// state 42
	1, 151, 1, 2,
	// state 43
	1, 153, 1, 18,
	// state 44
	1, 155, 1, 14,
	// state 45
	1, 157, 1, 13,
	// state 46
	1, 159, 1, 18,
	// state 47
	1, 161, 1, 2,
	// state 48
	1, 163, 1, 6,
	// state 49
	1, 165, 1, 2,
	// state 50
	1, 167, 1, 6,
}

// smallParseTableMap is ts_small_parse_table_map.
var smallParseTableMap = []uint32{
	0, 31, 59, 78, 100, 120, 146, 168, 190, 206, 226, 239, 252, 265, 278, 290,
	308, 328, 342, 362, 382, 397, 414, 429, 444, 459, 474, 483, 492, 501, 510, 519,
	526, 533, 540, 544, 548, 552, 556, 560, 564, 568, 572, 576, 580, 584, 588, 592,
	596,
}

// parseActions is ts_parse_actions. Each group of actions is one entry
// with the header of the group, and then its actions.
var parseActions = []abi.ParseActionEntry{
	{Entry: header{Count: 0}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeRecover}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 7}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 43}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 44}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 4}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 5}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 21}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 21}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 23}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 36}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 23}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 48}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 20}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 9}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 1, Symbol: 20}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 34}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 21}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 2}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 17}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 41}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}}, {Action: action{Type: typeShift, Shift: shift{State: 48, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}}, {Action: action{Type: typeShift, Shift: shift{State: 8, Repetition: true}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}}, {Action: action{Type: typeShift, Shift: shift{State: 8, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 20}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 8}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 20}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 26}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 26}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 5, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 5, Symbol: 21}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 27}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 27}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 24}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 24}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 25}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 22}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 46}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 40}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 38}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeShift, Shift: shift{State: 50}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 26}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}}, {Action: action{Type: typeShift, Shift: shift{State: 2, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}}, {Action: action{Type: typeShift, Shift: shift{State: 17, Repetition: true}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}}, {Action: action{Type: typeShift, Shift: shift{State: 24, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 29}}},
	{Entry: header{Count: 2}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}}, {Action: action{Type: typeShift, Shift: shift{State: 50, Repetition: true}}},
	{Entry: header{Count: 2, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 30}}}, {Action: action{Type: typeShift, Shift: shift{State: 26, Repetition: true}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 22}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 21}}},
	{Entry: header{Count: 1}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 6, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 6, Symbol: 21}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 27}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 10}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 14}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 25}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 3, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeAccept}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 4, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeReduce, Reduce: reduce{ChildCount: 2, Symbol: 19}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 3}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 42}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 45}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 12}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 37}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 16}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 33}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 31}}},
	{Entry: header{Count: 1, Reusable: true}}, {Action: action{Type: typeShift, Shift: shift{State: 35}}},
}

// publicSymbolMap is ts_symbol_map.
var publicSymbolMap = []uint16{
	0, 1, 2, 3, 6, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 8, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
}

// aliasMap is ts_non_terminal_alias_map.
var aliasMap = []uint16{
	0,
}

// aliasSequences is ts_alias_sequences, MaxAliasSequenceLength entries for each production.
var aliasSequences = []uint16{
	0, 0, 0, 0, 0, 0,
}

// lexModes is ts_lex_modes.
var lexModes = []abi.LexerMode{
	{ExternalLexState: 1},
	{LexState: 2},
	{LexState: 4},
	{LexState: 4},
	{LexState: 7},
	{LexState: 9},
	{LexState: 11},
	{LexState: 9},
	{LexState: 9},
	{LexState: 9},
	{LexState: 6},
	{LexState: 11},
	{LexState: 11},
	{LexState: 11},
	{LexState: 11},
	{LexState: 11},
	{LexState: 9},
	{LexState: 15},
	{LexState: 4},
	{},
	{LexState: 4},
	{LexState: 4},
	{LexState: 13},
	{LexState: 4},
	{LexState: 9},
	{LexState: 9},
	{LexState: 13},
	{LexState: 13},
	{LexState: 4},
	{LexState: 4},
	{LexState: 4},
	{LexState: 13},
	{LexState: 4},
	{LexState: 13},
	{},
	{LexState: 13},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{ExternalLexState: 1},
	{},
	{LexState: 2},
	{ExternalLexState: 1},
	{},
	{LexState: 2},
	{},
	{LexState: 2},
}

// primaryStateIDs is ts_primary_state_ids.
var primaryStateIDs = []uint16{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 9, 23, 24, 25, 8, 5, 28, 29, 30, 16,
	32, 33, 34, 33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 47, 48,
}

// externalScannerStates is ts_external_scanner_states, one row of
// ExternalTokenCount entries for each external lex state.
var externalScannerStates = []bool{
	false,
	true,
}

// externalScannerSymbolMap is ts_external_scanner_symbol_map.
var externalScannerSymbolMap = []uint16{
	18,
}

// lex is the main lex function, which mainLexTable runs.
func lex(lexer *abi.Lexer, state uint16) bool {
	return mainLexTable.Lex(lexer, state)
}

// mainLexTable is the lex table of lex. The ranges of each state are sorted.
var mainLexTable = abi.LexTable{
	States: []abi.LexState{
		{Count: 31, EOFState: 21, HasEOF: true},
		{Start: 31, Count: 7},
		{Start: 38, Count: 7},
		{Start: 45, Count: 23},
		{Start: 68, Count: 23},
		{Start: 91, Count: 21},
		{Start: 112, Count: 21},
		{Start: 133, Count: 21},
		{Start: 154, Count: 16},
		{Start: 170, Count: 16},
		{Start: 186, Count: 19},
		{Start: 205, Count: 19},
		{Start: 224, Count: 14},
		{Start: 238, Count: 14},
		{Start: 252, Count: 16},
		{Start: 268, Count: 16},
		{Start: 284, Count: 7},
		{Start: 291, Count: 18},
		{Start: 309, Count: 3},
		{Start: 312, Count: 31, EOFState: 21, HasEOF: true},
		{Start: 343, Count: 31, EOFState: 21, HasEOF: true},
		{Start: 374, Accept: 0, HasAccept: true},
		{Start: 374, Accept: 1, HasAccept: true},
		{Start: 374, Count: 4, Accept: 1, HasAccept: true},
		{Start: 378, Accept: 2, HasAccept: true},
		{Start: 378, Accept: 3, HasAccept: true},
		{Start: 378, Count: 5, Accept: 3, HasAccept: true},
		{Start: 383, Count: 5, Accept: 4, HasAccept: true},
		{Start: 388, Count: 5, Accept: 4, HasAccept: true},
		{Start: 393, Count: 3, Accept: 4, HasAccept: true},
		{Start: 396, Count: 5, Accept: 5, HasAccept: true},
		{Start: 401, Count: 5, Accept: 5, HasAccept: true},
		{Start: 406, Count: 3, Accept: 5, HasAccept: true},
		{Start: 409, Count: 6, Accept: 6, HasAccept: true},
		{Start: 415, Count: 4, Accept: 6, HasAccept: true},
		{Start: 419, Count: 4, Accept: 6, HasAccept: true},
		{Start: 423, Count: 4, Accept: 6, HasAccept: true},
		{Start: 427, Count: 4, Accept: 6, HasAccept: true},
		{Start: 431, Count: 6, Accept: 6, HasAccept: true},
		{Start: 437, Count: 4, Accept: 6, HasAccept: true},
		{Start: 441, Count: 4, Accept: 6, HasAccept: true},
		{Start: 445, Count: 4, Accept: 6, HasAccept: true},
		{Start: 449, Count: 5, Accept: 6, HasAccept: true},
		{Start: 454, Count: 11, Accept: 6, HasAccept: true},
		{Start: 465, Count: 5, Accept: 6, HasAccept: true},
		{Start: 470, Count: 5, Accept: 6, HasAccept: true},
		{Start: 475, Count: 5, Accept: 6, HasAccept: true},
		{Start: 480, Count: 5, Accept: 6, HasAccept: true},
		{Start: 485, Count: 5, Accept: 6, HasAccept: true},
		{Start: 490, Count: 5, Accept: 6, HasAccept: true},
		{Start: 495, Count: 5, Accept: 6, HasAccept: true},
		{Start: 500, Count: 5, Accept: 6, HasAccept: true},
		{Start: 505, Count: 5, Accept: 6, HasAccept: true},
		{Start: 510, Count: 5, Accept: 6, HasAccept: true},
		{Start: 515, Count: 5, Accept: 6, HasAccept: true},
		{Start: 520, Count: 5, Accept: 6, HasAccept: true},
		{Start: 525, Count: 5, Accept: 6, HasAccept: true},
		{Start: 530, Count: 5, Accept: 6, HasAccept: true},
		{Start: 535, Count: 5, Accept: 6, HasAccept: true},
		{Start: 540, Count: 5, Accept: 6, HasAccept: true},
		{Start: 545, Count: 5, Accept: 6, HasAccept: true},
		{Start: 550, Count: 5, Accept: 6, HasAccept: true},
		{Start: 555, Count: 5, Accept: 6, HasAccept: true},
		{Start: 560, Count: 7, Accept: 6, HasAccept: true},
		{Start: 567, Count: 5, Accept: 6, HasAccept: true},
		{Start: 572, Count: 5, Accept: 6, HasAccept: true},
		{Start: 577, Count: 7, Accept: 6, HasAccept: true},
		{Start: 584, Count: 5, Accept: 6, HasAccept: true},
		{Start: 589, Count: 5, Accept: 6, HasAccept: true},
		{Start: 594, Count: 5, Accept: 6, HasAccept: true},
		{Start: 599, Count: 5, Accept: 6, HasAccept: true},
		{Start: 604, Count: 5, Accept: 6, HasAccept: true},
		{Start: 609, Count: 5, Accept: 6, HasAccept: true},
		{Start: 614, Count: 5, Accept: 6, HasAccept: true},
		{Start: 619, Count: 5, Accept: 6, HasAccept: true},
		{Start: 624, Count: 5, Accept: 6, HasAccept: true},
		{Start: 629, Count: 5, Accept: 6, HasAccept: true},
		{Start: 634, Count: 5, Accept: 6, HasAccept: true},
		{Start: 639, Count: 5, Accept: 6, HasAccept: true},
		{Start: 644, Count: 5, Accept: 6, HasAccept: true},
		{Start: 649, Count: 7, Accept: 6, HasAccept: true},
		{Start: 656, Count: 5, Accept: 6, HasAccept: true},
		{Start: 661, Count: 5, Accept: 6, HasAccept: true},
		{Start: 666, Count: 5, Accept: 6, HasAccept: true},
		{Start: 671, Count: 5, Accept: 6, HasAccept: true},
		{Start: 676, Count: 5, Accept: 6, HasAccept: true},
		{Start: 681, Count: 5, Accept: 6, HasAccept: true},
		{Start: 686, Count: 5, Accept: 6, HasAccept: true},
		{Start: 691, Count: 5, Accept: 6, HasAccept: true},
		{Start: 696, Count: 5, Accept: 6, HasAccept: true},
		{Start: 701, Count: 5, Accept: 6, HasAccept: true},
		{Start: 706, Count: 5, Accept: 6, HasAccept: true},
		{Start: 711, Count: 5, Accept: 6, HasAccept: true},
		{Start: 716, Count: 5, Accept: 6, HasAccept: true},
		{Start: 721, Count: 5, Accept: 6, HasAccept: true},
		{Start: 726, Count: 5, Accept: 6, HasAccept: true},
		{Start: 731, Count: 7, Accept: 6, HasAccept: true},
		{Start: 738, Count: 5, Accept: 6, HasAccept: true},
		{Start: 743, Count: 5, Accept: 6, HasAccept: true},
		{Start: 748, Count: 5, Accept: 6, HasAccept: true},
		{Start: 753, Count: 5, Accept: 6, HasAccept: true},
		{Start: 758, Count: 5, Accept: 6, HasAccept: true},
		{Start: 763, Count: 5, Accept: 6, HasAccept: true},
		{Start: 768, Count: 5, Accept: 6, HasAccept: true},
		{Start: 773, Count: 5, Accept: 6, HasAccept: true},
		{Start: 778, Count: 5, Accept: 6, HasAccept: true},
		{Start: 783, Count: 5, Accept: 6, HasAccept: true},
		{Start: 788, Count: 5, Accept: 6, HasAccept: true},
		{Start: 793, Count: 5, Accept: 6, HasAccept: true},
		{Start: 798, Count: 5, Accept: 6, HasAccept: true},
		{Start: 803, Count: 5, Accept: 6, HasAccept: true},
		{Start: 808, Count: 5, Accept: 6, HasAccept: true},
		{Start: 813, Count: 5, Accept: 6, HasAccept: true},
		{Start: 818, Count: 5, Accept: 6, HasAccept: true},
		{Start: 823, Count: 5, Accept: 6, HasAccept: true},
		{Start: 828, Count: 5, Accept: 6, HasAccept: true},
		{Start: 833, Count: 5, Accept: 6, HasAccept: true},
		{Start: 838, Count: 5, Accept: 6, HasAccept: true},
		{Start: 843, Count: 5, Accept: 6, HasAccept: true},
		{Start: 848, Count: 5, Accept: 6, HasAccept: true},
		{Start: 853, Count: 5, Accept: 6, HasAccept: true},
		{Start: 858, Count: 7, Accept: 6, HasAccept: true},
		{Start: 865, Count: 5, Accept: 6, HasAccept: true},
		{Start: 870, Count: 5, Accept: 6, HasAccept: true},
		{Start: 875, Count: 5, Accept: 6, HasAccept: true},
		{Start: 880, Count: 5, Accept: 6, HasAccept: true},
		{Start: 885, Count: 3, Accept: 6, HasAccept: true},
		{Start: 888, Accept: 7, HasAccept: true},
		{Start: 888, Accept: 8, HasAccept: true},
		{Start: 888, Count: 1, Accept: 8, HasAccept: true},
		{Start: 889, Accept: 9, HasAccept: true},
		{Start: 889, Accept: 10, HasAccept: true},
		{Start: 889, Accept: 11, HasAccept: true},
		{Start: 889, Accept: 12, HasAccept: true},
		{Start: 889, Accept: 13, HasAccept: true},
		{Start: 889, Count: 5, Accept: 14, HasAccept: true},
		{Start: 894, Count: 7, Accept: 15, HasAccept: true},
		{Start: 901, Count: 8, Accept: 15, HasAccept: true},
		{Start: 909, Count: 8, Accept: 15, HasAccept: true},
		{Start: 917, Count: 1, Accept: 16, HasAccept: true},
		{Start: 918, Accept: 17, HasAccept: true},
		{Start: 918, Count: 1, Accept: 17, HasAccept: true},
	},
	Ranges: []abi.LexRange{
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 20, Skip: true}, {Lo: '\n', Hi: '\n', State: 19, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 20, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 20, Skip: true}, {Lo: '!', Hi: '"', State: 138},
		{Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: '$', State: 135}, {Lo: '%', Hi: ')', State: 138}, {Lo: '+', Hi: '-', State: 138},
		{Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 129}, {Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127},
		{Lo: ';', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'Z', State: 135}, {Lo: '[', Hi: '[', State: 133},
		{Lo: '\\', Hi: '\\', State: 138}, {Lo: ']', Hi: ']', State: 134}, {Lo: '^', Hi: '^', State: 138}, {Lo: '_', Hi: '_', State: 135},
		{Lo: '`', Hi: '`', State: 138}, {Lo: 'a', Hi: 'z', State: 135}, {Lo: '{', Hi: '{', State: 23}, {Lo: '|', Hi: '|', State: 138},
		{Lo: '}', Hi: '}', State: 24}, {Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: '\t', Hi: '\n', State: 1, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 2, Skip: true}, {Lo: ' ', Hi: ' ', State: 1, Skip: true}, {Lo: '*', Hi: '*', State: 1, Skip: true}, {Lo: '/', Hi: '/', State: 139},
		{Lo: '@', Hi: '@', State: 18}, {Lo: ']', Hi: ']', State: 134}, {Lo: '\t', Hi: '\t', State: 2, Skip: true}, {Lo: '\n', Hi: '\n', State: 1, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 2, Skip: true}, {Lo: ' ', Hi: ' ', State: 2, Skip: true}, {Lo: '/', Hi: '/', State: 139}, {Lo: '@', Hi: '@', State: 18},
		{Lo: ']', Hi: ']', State: 134}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\n', State: 3, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 4, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 3, Skip: true}, {Lo: '!', Hi: '#', State: 138},
		{Lo: '$', Hi: '$', State: 135}, {Lo: '%', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 3, Skip: true}, {Lo: '+', Hi: '.', State: 138},
		{Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'Z', State: 135},
		{Lo: '[', Hi: '[', State: 133}, {Lo: '\\', Hi: '^', State: 138}, {Lo: '_', Hi: '_', State: 135}, {Lo: '`', Hi: '`', State: 138},
		{Lo: 'a', Hi: 'z', State: 135}, {Lo: '{', Hi: '{', State: 22}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 4, Skip: true}, {Lo: '\n', Hi: '\n', State: 3, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 4, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 4, Skip: true}, {Lo: '!', Hi: '#', State: 138},
		{Lo: '$', Hi: '$', State: 135}, {Lo: '%', Hi: ')', State: 138}, {Lo: '+', Hi: '.', State: 138}, {Lo: '/', Hi: '/', State: 140},
		{Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'Z', State: 135}, {Lo: '[', Hi: '[', State: 133},
		{Lo: '\\', Hi: '^', State: 138}, {Lo: '_', Hi: '_', State: 135}, {Lo: '`', Hi: '`', State: 138}, {Lo: 'a', Hi: 'z', State: 135},
		{Lo: '{', Hi: '{', State: 22}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138},
		{Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\n', State: 5, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 6, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138},
		{Lo: ' ', Hi: ' ', State: 5, Skip: true}, {Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: ')', State: 138},
		{Lo: '*', Hi: '*', State: 5, Skip: true}, {Lo: '+', Hi: '-', State: 138}, {Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 140},
		{Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127}, {Lo: ';', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17},
		{Lo: 'A', Hi: 'z', State: 138}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 6, Skip: true}, {Lo: '\n', Hi: '\n', State: 5, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 6, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 6, Skip: true}, {Lo: '!', Hi: '"', State: 138},
		{Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: ')', State: 138}, {Lo: '+', Hi: '-', State: 138}, {Lo: '.', Hi: '.', State: 130},
		{Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127}, {Lo: ';', Hi: '?', State: 138},
		{Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: '~', State: 132},
		{Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 6, Skip: true},
		{Lo: '\n', Hi: '\n', State: 5, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 6, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 6, Skip: true},
		{Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: ')', State: 138}, {Lo: '+', Hi: '-', State: 138},
		{Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 128}, {Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127},
		{Lo: ';', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '|', Hi: '|', State: 138},
		{Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138},
		{Lo: '\t', Hi: '\n', State: 8, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 9, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 8, Skip: true},
		{Lo: '!', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 8, Skip: true}, {Lo: '+', Hi: '.', State: 138}, {Lo: '/', Hi: '/', State: 140},
		{Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '{', Hi: '{', State: 23},
		{Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138},
		{Lo: '\t', Hi: '\t', State: 9, Skip: true}, {Lo: '\n', Hi: '\n', State: 8, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 9, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138},
		{Lo: ' ', Hi: ' ', State: 9, Skip: true}, {Lo: '!', Hi: ')', State: 138}, {Lo: '+', Hi: '.', State: 138}, {Lo: '/', Hi: '/', State: 140},
		{Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '{', Hi: '{', State: 23},
		{Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138},
		{Lo: '\t', Hi: '\n', State: 10, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 11, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 10, Skip: true},
		{Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 10, Skip: true},
		{Lo: '+', Hi: '-', State: 138}, {Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '?', State: 138},
		{Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: '~', State: 132},
		{Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 11, Skip: true},
		{Lo: '\n', Hi: '\n', State: 10, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 11, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 11, Skip: true},
		{Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131}, {Lo: '$', Hi: ')', State: 138}, {Lo: '+', Hi: '-', State: 138},
		{Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17},
		{Lo: 'A', Hi: 'z', State: 138}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\n', State: 12, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 13, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 12, Skip: true}, {Lo: '!', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 12, Skip: true},
		{Lo: '+', Hi: '?', State: 138}, {Lo: 'A', Hi: 'z', State: 138}, {Lo: '{', Hi: '{', State: 23}, {Lo: '|', Hi: '|', State: 138},
		{Lo: '}', Hi: '}', State: 24}, {Lo: '~', Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138},
		{Lo: '\t', Hi: '\t', State: 13, Skip: true}, {Lo: '\n', Hi: '\n', State: 12, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 13, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138},
		{Lo: ' ', Hi: ' ', State: 13, Skip: true}, {Lo: '!', Hi: ')', State: 138}, {Lo: '+', Hi: '?', State: 138}, {Lo: 'A', Hi: 'z', State: 138},
		{Lo: '{', Hi: '{', State: 23}, {Lo: '|', Hi: '|', State: 138}, {Lo: '}', Hi: '}', State: 24}, {Lo: '~', Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\n', State: 14, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 15, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 14, Skip: true}, {Lo: '!', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 14, Skip: true},
		{Lo: '+', Hi: '.', State: 138}, {Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17},
		{Lo: 'A', Hi: 'z', State: 138}, {Lo: '{', Hi: '{', State: 22}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 15, Skip: true}, {Lo: '\n', Hi: '\n', State: 14, Skip: true},
		{Lo: 0x0b, Hi: '\r', State: 15, Skip: true}, {Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 15, Skip: true}, {Lo: '!', Hi: ')', State: 138},
		{Lo: '+', Hi: '.', State: 138}, {Lo: '/', Hi: '/', State: 140}, {Lo: '0', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17},
		{Lo: 'A', Hi: 'z', State: 138}, {Lo: '{', Hi: '{', State: 22}, {Lo: '|', Hi: '|', State: 138}, {Lo: '~', Hi: 0x7fffffff, State: 138},
		{Lo: -2147483648, Hi: -1, State: 16}, {Lo: 0x01, Hi: '\t', State: 16}, {Lo: 0x0b, Hi: ')', State: 16}, {Lo: '*', Hi: '*', State: 137},
		{Lo: '+', Hi: 'z', State: 16}, {Lo: '|', Hi: '|', State: 16}, {Lo: '~', Hi: 0x7fffffff, State: 16}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 43}, {Lo: 'b', Hi: 'b', State: 86}, {Lo: 'c', Hi: 'c', State: 33},
		{Lo: 'd', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 121}, {Lo: 'f', Hi: 'f', State: 66}, {Lo: 'g', Hi: 'l', State: 126},
		{Lo: 'm', Hi: 'm', State: 64}, {Lo: 'n', Hi: 'n', State: 34}, {Lo: 'o', Hi: 'o', State: 126}, {Lo: 'p', Hi: 'p', State: 38},
		{Lo: 'q', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 50}, {Lo: 's', Hi: 's', State: 36}, {Lo: 't', Hi: 't', State: 63},
		{Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'z', State: 126},
		{Lo: -2147483648, Hi: -1, State: 138}, {Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\n', State: 19, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 20, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 19, Skip: true}, {Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131},
		{Lo: '$', Hi: '$', State: 135}, {Lo: '%', Hi: ')', State: 138}, {Lo: '*', Hi: '*', State: 19, Skip: true}, {Lo: '+', Hi: '-', State: 138},
		{Lo: '.', Hi: '.', State: 130}, {Lo: '/', Hi: '/', State: 141}, {Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127},
		{Lo: ';', Hi: '?', State: 138}, {Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'Z', State: 135}, {Lo: '[', Hi: '[', State: 133},
		{Lo: '\\', Hi: '\\', State: 138}, {Lo: ']', Hi: ']', State: 134}, {Lo: '^', Hi: '^', State: 138}, {Lo: '_', Hi: '_', State: 135},
		{Lo: '`', Hi: '`', State: 138}, {Lo: 'a', Hi: 'z', State: 135}, {Lo: '{', Hi: '{', State: 23}, {Lo: '|', Hi: '|', State: 138},
		{Lo: '}', Hi: '}', State: 24}, {Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 138},
		{Lo: 0x01, Hi: 0x08, State: 138}, {Lo: '\t', Hi: '\t', State: 20, Skip: true}, {Lo: '\n', Hi: '\n', State: 19, Skip: true}, {Lo: 0x0b, Hi: '\r', State: 20, Skip: true},
		{Lo: 0x0e, Hi: 0x1f, State: 138}, {Lo: ' ', Hi: ' ', State: 20, Skip: true}, {Lo: '!', Hi: '"', State: 138}, {Lo: '#', Hi: '#', State: 131},
		{Lo: '$', Hi: '$', State: 135}, {Lo: '%', Hi: ')', State: 138}, {Lo: '+', Hi: '-', State: 138}, {Lo: '.', Hi: '.', State: 130},
		{Lo: '/', Hi: '/', State: 141}, {Lo: '0', Hi: '9', State: 138}, {Lo: ':', Hi: ':', State: 127}, {Lo: ';', Hi: '?', State: 138},
		{Lo: '@', Hi: '@', State: 17}, {Lo: 'A', Hi: 'Z', State: 135}, {Lo: '[', Hi: '[', State: 133}, {Lo: '\\', Hi: '\\', State: 138},
		{Lo: ']', Hi: ']', State: 134}, {Lo: '^', Hi: '^', State: 138}, {Lo: '_', Hi: '_', State: 135}, {Lo: '`', Hi: '`', State: 138},
		{Lo: 'a', Hi: 'z', State: 135}, {Lo: '{', Hi: '{', State: 23}, {Lo: '|', Hi: '|', State: 138}, {Lo: '}', Hi: '}', State: 24},
		{Lo: '~', Hi: '~', State: 132}, {Lo: 0x7f, Hi: 0x7fffffff, State: 138}, {Lo: -2147483648, Hi: -1, State: 26}, {Lo: 0x01, Hi: '?', State: 26},
		{Lo: 'A', Hi: '|', State: 26}, {Lo: '~', Hi: 0x7fffffff, State: 26}, {Lo: -2147483648, Hi: -1, State: 26}, {Lo: 0x01, Hi: '?', State: 26},
		{Lo: 'A', Hi: '|', State: 26}, {Lo: '}', Hi: '}', State: 25}, {Lo: '~', Hi: 0x7fffffff, State: 26}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 105}, {Lo: 'f', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'r', State: 126}, {Lo: 's', Hi: 's', State: 94},
		{Lo: 't', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'c', State: 126}, {Lo: 'd', Hi: 'd', State: 56},
		{Lo: 'e', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'r', State: 126},
		{Lo: 's', Hi: 's', State: 32}, {Lo: 't', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 74},
		{Lo: 'b', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 79}, {Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 76}, {Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 75}, {Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 115}, {Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 44}, {Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 106}, {Lo: 'b', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 88},
		{Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 72},
		{Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 107},
		{Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 47},
		{Lo: 'b', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'a', State: 126},
		{Lo: 'b', Hi: 'b', State: 37}, {Lo: 'c', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'b', State: 126}, {Lo: 'c', Hi: 'c', State: 45}, {Lo: 'd', Hi: 'k', State: 126}, {Lo: 'l', Hi: 'l', State: 67},
		{Lo: 'm', Hi: 'o', State: 126}, {Lo: 'p', Hi: 'p', State: 65}, {Lo: 'q', Hi: 't', State: 126}, {Lo: 'u', Hi: 'u', State: 62},
		{Lo: 'v', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'b', State: 126},
		{Lo: 'c', Hi: 'c', State: 71}, {Lo: 'd', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'b', State: 126}, {Lo: 'c', Hi: 'c', State: 55}, {Lo: 'd', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'b', State: 126}, {Lo: 'c', Hi: 'c', State: 118}, {Lo: 'd', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'b', State: 126}, {Lo: 'c', Hi: 'c', State: 51},
		{Lo: 'd', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'b', State: 126},
		{Lo: 'c', Hi: 'c', State: 116}, {Lo: 'd', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'c', State: 126}, {Lo: 'd', Hi: 'd', State: 107}, {Lo: 'e', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 112}, {Lo: 'f', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 29},
		{Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126},
		{Lo: 'e', Hi: 'e', State: 80}, {Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 28}, {Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 30}, {Lo: 'f', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 110},
		{Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126},
		{Lo: 'e', Hi: 'e', State: 60}, {Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 83}, {Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 107}, {Lo: 'f', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'd', State: 126}, {Lo: 'e', Hi: 'e', State: 85},
		{Lo: 'f', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'e', State: 126},
		{Lo: 'f', Hi: 'f', State: 29}, {Lo: 'g', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'e', State: 126}, {Lo: 'f', Hi: 'f', State: 70}, {Lo: 'g', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'f', State: 126}, {Lo: 'g', Hi: 'g', State: 77}, {Lo: 'h', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'g', State: 126}, {Lo: 'h', Hi: 'h', State: 99},
		{Lo: 'i', Hi: 'x', State: 126}, {Lo: 'y', Hi: 'y', State: 95}, {Lo: 'z', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126}, {Lo: 'i', Hi: 'i', State: 124}, {Lo: 'j', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126}, {Lo: 'i', Hi: 'i', State: 29},
		{Lo: 'j', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126},
		{Lo: 'i', Hi: 'i', State: 101}, {Lo: 'j', Hi: 't', State: 126}, {Lo: 'u', Hi: 'u', State: 82}, {Lo: 'v', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126}, {Lo: 'i', Hi: 'i', State: 40},
		{Lo: 'j', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126},
		{Lo: 'i', Hi: 'i', State: 108}, {Lo: 'j', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'h', State: 126}, {Lo: 'i', Hi: 'i', State: 91}, {Lo: 'j', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'h', State: 126}, {Lo: 'i', Hi: 'i', State: 58}, {Lo: 'j', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'j', State: 126}, {Lo: 'k', Hi: 'k', State: 29},
		{Lo: 'l', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'k', State: 126},
		{Lo: 'l', Hi: 'l', State: 29}, {Lo: 'm', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'k', State: 126}, {Lo: 'l', Hi: 'l', State: 42}, {Lo: 'm', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'k', State: 126}, {Lo: 'l', Hi: 'l', State: 73}, {Lo: 'm', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'l', State: 126}, {Lo: 'm', Hi: 'm', State: 29},
		{Lo: 'n', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'l', State: 126},
		{Lo: 'm', Hi: 'm', State: 53}, {Lo: 'n', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'l', State: 126}, {Lo: 'm', Hi: 'm', State: 59}, {Lo: 'n', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 29}, {Lo: 'o', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 109},
		{Lo: 'o', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126},
		{Lo: 'n', Hi: 'n', State: 49}, {Lo: 'o', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 84}, {Lo: 's', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 31},
		{Lo: 'o', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126},
		{Lo: 'n', Hi: 'n', State: 48}, {Lo: 'o', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 111}, {Lo: 'o', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 39}, {Lo: 'o', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'm', State: 126}, {Lo: 'n', Hi: 'n', State: 114},
		{Lo: 'o', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'n', State: 126},
		{Lo: 'o', Hi: 'o', State: 102}, {Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 122}, {Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 93}, {Lo: 'p', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 123},
		{Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'n', State: 126},
		{Lo: 'o', Hi: 'o', State: 104}, {Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 78}, {Lo: 'p', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'n', State: 126}, {Lo: 'o', Hi: 'o', State: 97}, {Lo: 'p', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'o', State: 126}, {Lo: 'p', Hi: 'p', State: 27},
		{Lo: 'q', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'o', State: 126},
		{Lo: 'p', Hi: 'p', State: 41}, {Lo: 'q', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'o', State: 126}, {Lo: 'p', Hi: 'p', State: 54}, {Lo: 'q', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'o', State: 126}, {Lo: 'p', Hi: 'p', State: 90}, {Lo: 'q', Hi: 's', State: 126},
		{Lo: 't', Hi: 't', State: 52}, {Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 29}, {Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 120}, {Lo: 's', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 87},
		{Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126},
		{Lo: 'r', Hi: 'r', State: 89}, {Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 58}, {Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 100}, {Lo: 's', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 81},
		{Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126},
		{Lo: 'r', Hi: 'r', State: 114}, {Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 113}, {Lo: 's', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'q', State: 126}, {Lo: 'r', Hi: 'r', State: 35}, {Lo: 's', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'r', State: 126}, {Lo: 's', Hi: 's', State: 29},
		{Lo: 't', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'r', State: 126},
		{Lo: 's', Hi: 's', State: 61}, {Lo: 't', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'r', State: 126}, {Lo: 's', Hi: 's', State: 117}, {Lo: 't', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'r', State: 126}, {Lo: 's', Hi: 's', State: 107}, {Lo: 't', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 29},
		{Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126},
		{Lo: 't', Hi: 't', State: 119}, {Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 125}, {Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 107}, {Lo: 'u', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 68},
		{Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126},
		{Lo: 't', Hi: 't', State: 69}, {Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 98}, {Lo: 'u', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 's', State: 126}, {Lo: 't', Hi: 't', State: 92}, {Lo: 'u', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 't', State: 126}, {Lo: 'u', Hi: 'u', State: 103},
		{Lo: 'v', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 't', State: 126},
		{Lo: 'u', Hi: 'u', State: 46}, {Lo: 'v', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'u', State: 126}, {Lo: 'v', Hi: 'v', State: 57}, {Lo: 'w', Hi: 'w', State: 126}, {Lo: 'x', Hi: 'x', State: 96},
		{Lo: 'y', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'v', State: 126},
		{Lo: 'w', Hi: 'w', State: 31}, {Lo: 'x', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126},
		{Lo: 'a', Hi: 'v', State: 126}, {Lo: 'w', Hi: 'w', State: 107}, {Lo: 'x', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126},
		{Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'w', State: 126}, {Lo: 'x', Hi: 'x', State: 58}, {Lo: 'y', Hi: 'z', State: 126},
		{Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'x', State: 126}, {Lo: 'y', Hi: 'y', State: 29},
		{Lo: 'z', Hi: 'z', State: 126}, {Lo: 'A', Hi: 'Z', State: 126}, {Lo: '_', Hi: '_', State: 126}, {Lo: 'a', Hi: 'z', State: 126},
		{Lo: '*', Hi: '*', State: 139}, {Lo: '$', Hi: '$', State: 135}, {Lo: '0', Hi: '9', State: 135}, {Lo: 'A', Hi: 'Z', State: 135},
		{Lo: '_', Hi: '_', State: 135}, {Lo: 'a', Hi: 'z', State: 135}, {Lo: -2147483648, Hi: -1, State: 136}, {Lo: 0x01, Hi: '\t', State: 136},
		{Lo: 0x0b, Hi: ')', State: 136}, {Lo: '*', Hi: '*', State: 137}, {Lo: '+', Hi: 'z', State: 136}, {Lo: '|', Hi: '|', State: 136},
		{Lo: '~', Hi: 0x7fffffff, State: 136}, {Lo: -2147483648, Hi: -1, State: 16}, {Lo: 0x01, Hi: '\t', State: 16}, {Lo: 0x0b, Hi: ')', State: 16},
		{Lo: '*', Hi: '*', State: 137}, {Lo: '+', Hi: '.', State: 16}, {Lo: '0', Hi: 'z', State: 16}, {Lo: '|', Hi: '|', State: 16},
		{Lo: '~', Hi: 0x7fffffff, State: 16}, {Lo: -2147483648, Hi: -1, State: 136}, {Lo: 0x01, Hi: '\t', State: 136}, {Lo: 0x0b, Hi: ')', State: 136},
		{Lo: '+', Hi: '.', State: 136}, {Lo: '/', Hi: '/', State: 138}, {Lo: '0', Hi: 'z', State: 136}, {Lo: '|', Hi: '|', State: 136},
		{Lo: '~', Hi: 0x7fffffff, State: 136}, {Lo: '*', Hi: '*', State: 139}, {Lo: '*', Hi: '*', State: 139},
	},
}
