// Code generated by transit. DO NOT EDIT.

package oracle_test

import (
	"fmt"
	"io/fs"
	"log"
	"path"

	"github.com/xo/transit"
	"github.com/xo/transit/grammars/oracle"
)

// This example compiles each query of the package oracle, and prints the number
// of its patterns.
func ExampleLanguage() {
	language := oracle.Language()
	walk := func(name string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || path.Ext(name) != ".scm" {
			return err
		}
		text, err := fs.ReadFile(oracle.Queries, name)
		if err != nil {
			return err
		}
		query, err := transit.NewQuery(language, string(text))
		if err != nil {
			return fmt.Errorf("compiling %s: %w", name, err)
		}
		fmt.Printf("patterns in %s: %d\n", name, query.PatternCount())
		return nil
	}
	if err := fs.WalkDir(oracle.Queries, "queries", walk); err != nil {
		log.Fatal(err)
	}
	// Output:
	// patterns in queries/highlights.scm: 37
}
